Repository pingcap/docs-tidb-operator, pull requests merged in 2020-09, with the labels that each got.

#668 en: add sections for taking binlog offline
  en/deploy-tidb-binlog.md
Labels: needs-cherry-pick-1.1, size/large, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#666 en: bump tidb version to 4.0.4
  en/access-dashboard.md
  en/access-tidb.md
  en/advanced-statefulset.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-gcs.md
  en/backup-to-s3.md
  en/configure-a-tidb-cluster.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-enterprise-edition.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/monitor-using-tidbmonitor.md
  en/notes-tidb-operator-v1.1.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs-using-br.md
  en/restore-from-gcs.md
  en/restore-from-s3.md
  en/upgrade-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#672 zh: simplify gcp/gke deployment guide
  zh/deploy-on-gcp-gke.md
Labels: needs-cherry-pick-1.1, size/large, status/LGT2, status/PTAL, status/can-merge, status/require-change, translation/doing

#682 release-1.1: zh: simplify gcp/gke deployment guide (#672)
  zh/deploy-on-gcp-gke.md
Labels: status/LGT1

#684 en,zh: add note about cluster name in monitor
  en/monitor-using-tidbmonitor.md
  zh/monitor-using-tidbmonitor.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/done

#680 zh: add recommended configurations
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#687 add ci job to check unclosed tags; fix some inline codes
  .github/workflows/ci.yaml
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs.md
  en/backup-to-s3.md
  en/deploy-on-gcp-gke.md
  hack/check-tags.py
  zh/backup-to-s3.md
Labels: status/LGT1, translation/no-need

#683 zh: improvements from Queeny Test
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL, status/can-merge, translation/doing

#690 Add 8 aliases to fix dead links
  en/backup-and-restore-using-helm-charts.md
  en/get-started.md
  zh/access-tidb.md
  zh/configure-a-tidb-cluster.md
  zh/logs-collection.md
  zh/monitor-a-tidb-cluster.md
  zh/prerequisites.md
  zh/tips.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#691 Add 7 more aliases to fix dead links
  en/configure-a-tidb-cluster.md
  en/deploy-tidb-binlog.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/destroy-a-tidb-cluster.md
  zh/tidb-operator-overview.md
  zh/tips.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#692 en: add recommended configs for cluster deployment
  en/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL, translation/from-zh

#663 en: simplify deployment on aws eks
  en/configure-a-tidb-cluster.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/deploy-ticdc.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-enterprise-edition.md
  en/deploy-tiflash.md
  en/upgrade-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, size/large, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#700 Add 6 aliases to fix dead links
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-general-kubernetes.md
  en/get-started.md
  zh/deploy-on-gcp-gke.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#696 Modify the description of tikv scale-in
  zh/use-auto-failover.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/welcome

#699 zh: update backup & restore table filter usage and bump tidb cluster version to v4.0.6
  zh/access-dashboard.md
  zh/access-tidb.md
  zh/advanced-statefulset.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-gcs.md
  zh/backup-to-s3.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-enterprise-edition.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
  zh/monitor-using-tidbmonitor.md
  zh/notes-tidb-operator-v1.1.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-data-using-tidb-lightning.md
  zh/restore-from-aws-s3-using-br.md
  zh/restore-from-gcs-using-br.md
  zh/restore-from-gcs.md
  zh/upgrade-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#698 en, zh: add config notes for tiflash
  en/deploy-tiflash.md
  zh/deploy-tiflash.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#711 en, zh: update doc for pd-ctl and tikv-ctl when tls enabled
  en/configure-a-tidb-cluster.md
  en/enable-tls-between-components.md
  zh/configure-a-tidb-cluster.md
  zh/enable-tls-between-components.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#710 zh, en: release tidb-operator v1.1.5
  en/TOC.md
  en/releases/release-1.1.5.md
  zh/TOC.md
  zh/releases/release-1.1.5.md
Labels: DNM until Ansible tag is ready, needs-cherry-pick-1.1, status/LGT2, translation/done

#712 en, zh: update failover recover procedure for tikv and tiflash
  en/use-auto-failover.md
  zh/use-auto-failover.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#717 zh, en/: update tidb-operator chart version to v1.1.5
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#713 zh/: update br usage documents for aws and gcs
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/restore-from-aws-s3-using-br.md
  zh/restore-from-gcs-using-br.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#708 en: update tableFilter usage and bump tidb to 4.0.6
  en/access-dashboard.md
  en/access-tidb.md
  en/advanced-statefulset.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-gcs.md
  en/backup-to-s3.md
  en/configure-a-tidb-cluster.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-enterprise-edition.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/monitor-using-tidbmonitor.md
  en/notes-tidb-operator-v1.1.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs-using-br.md
  en/restore-from-gcs.md
  en/upgrade-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#722 Add 7 aliases to fix dead links
  en/backup-and-restore-using-helm-charts.md
  en/deploy-on-gcp-gke.md
  en/prerequisites.md
  zh/access-tidb.md
  zh/deploy-on-aws-eks.md
  zh/deploy-tidb-operator.md
  zh/tips.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#725 [testing].github: add an action to auto label stale issues
  .github/workflows/assign-to-project.yml
  .github/workflows/stale.yaml
Labels: status/LGT1, translation/no-need, type/enhancement

#701 en: simplify gke deployment doc
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
Labels: needs-cherry-pick-1.1, size/large, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#709 zh: add create heterogeneous cluster doc
  zh/TOC.md
  zh/deploy-heterogeneous-tidb-cluster.md
Labels: contribution, status/LGT2

#730 zh: update how to change tidb configs when we try to remove pump node
  zh/deploy-tidb-binlog.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#721 en: update br usage documents for aws and gcs
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs-using-br.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#735 zh: update pump doc to change warning to step
  zh/deploy-tidb-binlog.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#737 en, zh: add a step for removing Pump nodes
  en/deploy-tidb-binlog.md
  zh/deploy-tidb-binlog.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/from-zh

#731 .github: modify the action to label stale issues
  .github/workflows/stale.yaml
Labels: status/LGT2, translation/no-need, type/enhancement

#739 zh: update unsupported dashboard functions
  zh/access-dashboard.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/doing

#744 zh: update toc for heterogeneous cluster
  zh/TOC.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/doing

#743 en, zh: add note for mysql 8.0
  en/access-tidb.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/enable-tls-for-mysql-client.md
  en/get-started.md
  zh/access-tidb.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/enable-tls-for-mysql-client.md
  zh/get-started.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge

#747 en: add doc for deploying heterogeneous cluster
  en/TOC.md
  en/deploy-heterogeneous-tidb-cluster.md
Labels: follow-up, needs-cherry-pick-1.1, size/large, status/LGT2, status/can-merge, translation/from-zh
