Repository pingcap/docs-tidb-operator, pull requests merged in 2020-07, with the labels that each got.

#514 en: update the eks deployment doc
  en/deploy-on-aws-eks.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/from-zh

#517 en: tidb opreator offline installation
  en/deploy-tidb-operator.md
  en/tidb-toolkit.md
  zh/tidb-toolkit.md
Labels: needs-cherry-pick-1.1, size/large, status/LGT2, translation/from-zh

#530 Add scripts to verify link anchors
  .github/workflows/ci.yaml
  en/notes-tidb-operator-v1.1.md
  en/restore-from-s3.md
  en/tidb-operator-overview.md
  en/tidb-scheduler.md
  en/upgrade-a-tidb-cluster.md
  hack/verify-link-anchors.sh
  hack/verify-links.sh
  zh/backup-to-gcs-using-br.md
  zh/deploy-on-aws-eks.md
  zh/notes-tidb-operator-v1.1.md
  zh/restore-from-gcs-using-br.md
  zh/tidb-operator-overview.md
  zh/upgrade-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT1, status/can-merge, translation/no-need

#521 en: tidb cluster offline installation
  en/deploy-on-general-kubernetes.md
  en/deploy-ticdc.md
  en/deploy-tidb-binlog.md
  en/deploy-tiflash.md
  en/initialize-a-cluster.md
  en/monitor-using-tidbmonitor.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/from-zh

#477 en: update monitor and faq
  en/faq.md
  en/monitor-using-tidbmonitor.md
Labels: needs-cherry-pick-1.1, size/small, status/LGT1, status/can-merge, translation/from-zh

#529 zh: add enterprise usage
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-ticdc.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tiflash.md
  zh/upgrade-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/doing

#523 zh: add more hints for deployment on aws
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-gcs.md
  zh/backup-to-s3.md
  zh/deploy-on-aws-eks.md
Labels: needs-cherry-pick-1.1, size/small, status/LGT1, translation/doing

#540 add 2 aliases to 2 files to avoid 404 urls in Google
  en/architecture.md
  en/view-logs.md
Labels: status/LGT2, translation/no-need

#541 add 2 aliases to 2 files to avoid 404 urls in Google
  en/architecture.md
  en/view-logs.md
Labels: status/LGT2, translation/no-need

#526 zh: update get-started and related tutorials
  zh/TOC.md
  zh/_index.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-from-kubernetes-kind.md
  zh/deploy-tidb-from-kubernetes-minikube.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-operator-overview.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/from-en

#548 chore: update docs format
  en/get-started.md
Labels: needs-cherry-pick-1.1, status/LGT1

#542 en: update doc to use ali image for kube-scheduler
  en/get-started.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/done

#543 en, zh: add note about pvc deletion
  en/backup-to-gcs.md
  en/backup-to-s3.md
  en/restore-from-gcs.md
  en/restore-from-s3.md
  zh/backup-to-gcs.md
  zh/backup-to-s3.md
  zh/restore-from-gcs.md
  zh/restore-from-s3.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/done

#553 en: fix typo Temple->template
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs.md
  en/backup-to-s3.md
Labels: needs-cherry-pick-1.1, status/LGT1

#480 en: add local-volume-provisioner offline installation
  en/configure-storage-class.md
Labels: needs-cherry-pick-1.1, status/LGT1, status/can-merge, translation/from-zh

#557 add aliases in 2 docs
  en/configure-a-tidb-cluster.md
  zh/get-started.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/no-need, version-specific-changes-required

#527 en: improve GKE cloud shell docs
  en/deploy-tidb-from-kubernetes-gke.md
Labels: needs-cherry-pick-1.1, status/LGT1, status/PTAL, translation/done

#470 en: split troubleshoot to several docs
  en/TOC.md
  en/deploy-failures.md
  en/exceptions.md
  en/faq.md
  en/network-issues.md
  en/scale-a-tidb-cluster.md
  en/tidb-operator-overview.md
  en/tidb-scheduler.md
  en/tidb-toolkit.md
  en/tips.md
  en/troubleshoot.md
  zh/tips.md
  zh/troubleshoot.md
Labels: needs-cherry-pick-1.1, size/large, status/LGT3, translation/from-zh, version-specific-changes-required

#535 zh: stop tidb gracefully
  zh/access-tidb.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL, translation/doing

#544 zh: refine TiDB cluster configuration
  zh/TOC.md
  zh/configure-a-tidb-cluster.md
  zh/configure-cluster-using-tidbcluster.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/notes-tidb-operator-v1.1.md
  zh/tidb-operator-overview.md
Labels: needs-cherry-pick-1.1, size/large, status/LGT2, translation/from-en

#570 zh: fix a typo in aliases
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, require-LGT1, status/LGT2, status/can-merge, translation/no-need

#562 zh: update backup documents for newly added PRs
  zh/TOC.md
  zh/backup-and-restore-using-helm-charts.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-gcs.md
  zh/backup-to-s3.md
  zh/notes-tidb-operator-v1.1.md
  zh/restore-data-using-tidb-lightning.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL, translation/doing

#569 zh,en: fix wrong image url
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, require-LGT1, status/LGT1, translation/done

#566 zh: document handle backup gc behavior and how to delete backup
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-gcs.md
  zh/backup-to-s3.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL, status/can-merge

#576 chore: update pdf name
  .circleci/config.yml
Labels: status/LGT1, translation/no-need

#577 zh: fix the API doc link
  zh/configure-a-tidb-cluster.md
Labels: size/small, status/LGT2, translation/no-need

#578 zh: fix a broken link
  zh/configure-a-tidb-cluster.md
Labels: size/small, status/LGT1, translation/no-need

#574 zh: update links from 3.0/3.1 to stable
  zh/backup-and-restore-using-helm-charts.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs.md
  zh/backup-to-s3.md
  zh/configure-backup.md
  zh/deploy-tidb-binlog.md
  zh/enable-tls-for-mysql-client.md
  zh/faq.md
  zh/monitor-a-tidb-cluster.md
  zh/restore-data-using-tidb-lightning.md
  zh/restore-from-aws-s3-using-br.md
  zh/tidb-cluster-chart-config.md
  zh/tidb-toolkit.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/from-en

#581 zh: update warning about deleting PVs
  zh/configure-storage-class.md
Labels: needs-cherry-pick-1.1, require-LGT1, status/LGT1, translation/from-en

#589 document how to set tls config between drainer and upstream database
  zh/deploy-tidb-binlog.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#591 revise cleanData to cleanPolicy
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-gcs.md
  zh/backup-to-s3.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#590 zh: TiCDC TLS document
  zh/deploy-ticdc.md
  zh/enable-tls-between-components.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#595 en: set TLS config between drainer and downstream
  en/deploy-tidb-binlog.md
Labels: needs-cherry-pick-1.1, require-LGT1, status/LGT1, status/can-merge, translation/from-zh

#585 en: improve format and fix errors in existing files
  en/access-dashboard.md
  en/access-tidb.md
  en/architecture.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs.md
  en/backup-to-s3.md
  en/benchmark-sysbench.md
  en/configure-a-tidb-cluster.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  en/deploy-ticdc.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-operator.md
  en/deploy-tiflash.md
  en/destroy-a-tidb-cluster.md
  en/enable-admission-webhook.md
  en/enable-tidb-cluster-auto-scaling.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/exceptions.md
  en/faq.md
  en/get-started.md
  en/monitor-using-tidbmonitor.md
Labels: needs-cherry-pick-1.1, size/large, status/LGT2, status/can-merge, translation/no-need, type/bug-fix

#597 en: add enterprise image in deployment/upgrade docs
  en/configure-a-tidb-cluster.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/deploy-ticdc.md
  en/deploy-tidb-binlog.md
  en/deploy-tiflash.md
  en/upgrade-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, require-LGT1, size/medium, status/LGT1, status/can-merge, translation/from-zh

#583 en, zh: do not recommend local ssds for tikv storage
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#582 en: add backup&restore to gcs using br
  en/TOC.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs-using-br.md
  zh/backup-to-gcs-using-br.md
Labels: needs-cherry-pick-1.1, size/large, status/LGT2, translation/from-zh

#599 en: replace Mydumper with Dumpling
  en/TOC.md
  en/backup-and-restore-using-helm-charts.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs.md
  en/backup-to-s3.md
  en/notes-tidb-operator-v1.1.md
  en/restore-data-using-tidb-lightning.md
Labels: needs-cherry-pick-1.1, size/large, status/LGT2, translation/from-zh

#605 chore: update list indent and make tag closed
  en/backup-to-gcs-using-br.md
  en/backup-to-s3.md
Labels: status/LGT1

#607 en: fix aliases in get-started
  en/get-started.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/no-need, type/bug-fix

#609 en: add a slash in aliases
  en/get-started.md
Labels: status/LGT1, translation/no-need, type/bug-fix
