Repository pingcap/docs-tidb-operator, pull requests merged in 2020-04, with the labels that each got.

#145 README: update doc version and branch info
  README.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, translation/no-need

#150 zh: use issuer instead of clusterissuer
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
Labels: needs-cherry-pick-1.1, translation/doing

#133 en: reload tidb tls document
  en/enable-tls-for-mysql-client.md
Labels: needs-cherry-pick-1.1, size/small, translation/from-zh

#144 en: add `cert-allowed-cn` option
  en/enable-tls-between-components.md
Labels: needs-cherry-pick-1.1, translation/from-zh

#153 en: use Issuer instead of ClusterIssuer in TLS docs
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/from-zh

#117 en: update docs for getting started
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-from-kubernetes-kind.md
  en/deploy-tidb-from-kubernetes-minikube.md
Labels: needs-cherry-pick-1.1, translation/from-zh

#156 zh, en: fix TLS for client typo
  en/enable-tls-for-mysql-client.md
  zh/enable-tls-for-mysql-client.md
Labels: needs-cherry-pick-1.1, translation/no-need

#161 update local labels description for pd
  zh/configure-a-tidb-cluster.md
Labels: size/small, translation/welcome

#164 Add notes for tidb-operator version
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
Labels: needs-cherry-pick-1.1, translation/welcome

#159 Add api references
  en/TOC.md
  en/api-references.md
  zh/TOC.md
  zh/api-references.md
Labels: needs-cherry-pick-1.1

#170 docs: change failurePolicy from Failure to Fail
  en/enable-admission-webhook.md
  zh/enable-admission-webhook.md
Labels: contribution, needs-cherry-pick-1.1, translation/no-need

#169 en: add notes for tidb-operator version
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
Labels: needs-cherry-pick-1.1, translation/from-zh

#174 en, zh: update link for api reference
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  en/initialize-a-cluster.md
  en/monitor-using-tidbmonitor.md
  en/notes-tidb-operator-v1.1.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/initialize-a-cluster.md
  zh/monitor-using-tidbmonitor.md
  zh/notes-tidb-operator-v1.1.md
Labels: needs-cherry-pick-1.1

#178 zh, en: remove tab
  en/api-references.md
  zh/api-references.md
Labels: needs-cherry-pick-1.1, translation/no-need

#167 zh: the certificate commonName should be the same
  zh/enable-tls-between-components.md
Labels: needs-cherry-pick-1.0, translation/welcome

#182 en, zh: update doc for destroy failure on aws
  en/deploy-on-aws-eks.md
  zh/deploy-on-aws-eks.md
Labels: needs-cherry-pick-1.1, translation/no-need

#183 en: fix commonName of all certificate
  en/enable-tls-between-components.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/from-zh

#168 en: update location label description for pd
  en/configure-a-tidb-cluster.md
Labels: status/can-merge, translation/from-zh

#186 update doc of tidb-operator upgrade for v1.1 notes
  en/upgrade-tidb-operator.md
  zh/upgrade-tidb-operator.md
Labels: needs-cherry-pick-1.1, translation/done

#171 zh: update Webhook TLS document
  zh/enable-admission-webhook.md
Labels: needs-cherry-pick-1.1, translation/welcome

#192 *: add markdownlint in CI-v1.0
  .circleci/config.yml
  .markdownlint.yaml
Labels: translation/no-need

#196 zh, en: improve aws and ack docs
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
Labels: needs-cherry-pick-1.1, translation/done

#199 fix conflict
  zh/enable-admission-webhook.md
Labels: translation/no-need

#202 en: remove extra line in the table
  en/tidb-scheduler.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, translation/no-need

#193 zh,en: remove shell-regular for tls document
  en/enable-tls-for-mysql-client.md
  zh/enable-tls-for-mysql-client.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/done

#206 zh: add two commas
  zh/collect-tidb-logs.md
Labels: translation/no-need

#189 en: update TLS certificate for the admission controller
  en/enable-admission-webhook.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/from-zh

#210 Markdown lint in github action
  .github/workflows/ci.yaml
  en/backup-to-aws-s3-using-br.md
  en/upgrade-tidb-operator.md
  zh/backup-to-aws-s3-using-br.md
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, translation/no-need

#208 zh: add restart component of tidb cluster
  zh/restart-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/require-change, translation/doing

#197 zh, en: update api references in toc
  en/TOC.md
  zh/TOC.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/done

#212 .github: add markdownlint in ci
  .github/workflows/ci.yaml
  zh/configure-a-tidb-cluster.md
Labels: translation/no-need

#209 en: update helm content in aws deployment doc
  en/deploy-on-aws-eks.md
Labels: status/can-merge, translation/from-zh

#215 zh, en: update dns names list in tls certificate
  en/enable-tls-for-mysql-client.md
  zh/enable-tls-for-mysql-client.md
Labels: needs-cherry-pick-1.1, translation/done

#218 zh, en: uniq CN to `TiDB` in TLS
  en/enable-tls-between-components.md
  zh/enable-tls-between-components.md
Labels: needs-cherry-pick-1.1, translation/done

#220 zh,en: Update the api-references link error
  en/api-references.md
  zh/api-references.md
Labels: needs-cherry-pick-1.1, translation/done

#222 Fix tls configuration typo
  en/enable-tls-between-components.md
  zh/enable-tls-between-components.md
Labels: needs-cherry-pick-1.1, translation/done

#224 zh, en: use 3.1 in tls related documents
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
Labels: needs-cherry-pick-1.1, translation/done

#227 zh: update maintain-a-kubernetes-node.md
  zh/maintain-a-kubernetes-node.md
Labels: contribution, translation/doing

#228 zh, en: fix a typo in maintain-a-kubernetes-node.md
  en/maintain-a-kubernetes-node.md
  zh/maintain-a-kubernetes-node.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, translation/from-zh

#216 en: add restart component of tidb cluster
  en/restart-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT1, status/PTAL, translation/from-zh

#236 zh: update doc for tiflash
  zh/TOC.md
  zh/configure-cluster-using-tidbcluster.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tiflash.md
  zh/scale-a-tidb-cluster.md
  zh/use-auto-failover.md
Labels: needs-cherry-pick-1.1, translation/doing
