Repository pingcap/docs-tidb-operator, pull requests merged in 2020-06, with the labels that each got.

#317 zh: revise TidbCluster Scaling
  zh/enable-tidb-cluster-auto-scaling.md
  zh/scale-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, priority/P2, status/can-merge, translation/doing

#324 zh: Refine prerequisites.md
  zh/prerequisites.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/doing

#339 zh: refine logs query
  zh/TOC.md
  zh/collect-tidb-logs.md
  zh/logs-collection.md
  zh/tidb-operator-overview.md
  zh/view-logs.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/welcome

#371 en, zh: add sysbench in TOC
  en/TOC.md
  zh/TOC.md
Labels: needs-cherry-pick-1.1, translation/done

#365 zh: update initialization procedure
  zh/initialize-a-cluster.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/welcome

#341 zh: update disaster recovery doc
  zh/TOC.md
  zh/recover-deleted-cluster.md
  zh/troubleshoot.md
Labels: needs-cherry-pick-1.1, translation/welcome

#366 zh: update doc for tidb operator and tidb cluster upgrade
  zh/upgrade-a-tidb-cluster.md
  zh/upgrade-tidb-operator.md
Labels: needs-cherry-pick-1.1, translation/welcome

#328 en: restructure the TiDB cluster configuration document
  en/TOC.md
  en/configure-a-tidb-cluster.md
  en/configure-cluster-using-tidbcluster.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  en/notes-tidb-operator-v1.1.md
  en/tidb-operator-overview.md
  en/upgrade-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, translation/welcome

#363 zh: add cdc document on eks/ecs
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
Labels: needs-cherry-pick-1.1, translation/doing

#362 Reorganize Get Started
  en/TOC.md
  en/_index.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-from-kubernetes-kind.md
  en/deploy-tidb-from-kubernetes-minikube.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-operator-overview.md
Labels: needs-cherry-pick-1.1, translation/welcome

#326 zh: add using br to backup to gcs and restore from gcs document
  zh/TOC.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/restore-from-aws-s3-using-br.md
  zh/restore-from-gcs-using-br.md
Labels: needs-cherry-pick-1.1, translation/doing

#340 zh: add warning to cluster deletion
  zh/destroy-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, translation/doing

#369 zh: fix indent error in secret yaml
  zh/restore-data-using-tidb-lightning.md
Labels: needs-cherry-pick-1.1, translation/doing

#389 en: add doc for ingress in tidbmonitor
  en/monitor-using-tidbmonitor.md
Labels: needs-cherry-pick-1.1, translation/from-zh

#396 Fix config setting in document
  zh/configure-cluster-using-tidbcluster.md
Labels: needs-cherry-pick-1.1, translation/doing

#358 zh: refine troubleshooting
  zh/TOC.md
  zh/deploy-failures.md
  zh/exceptions.md
  zh/faq.md
  zh/network-issues.md
  zh/scale-a-tidb-cluster.md
  zh/tidb-operator-overview.md
  zh/tidb-scheduler.md
  zh/tidb-toolkit.md
  zh/tips.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/doing

#378 zh: helm offline document
  zh/tidb-toolkit.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/doing

#406 en: remove extra lines
  en/get-started.md
Labels: needs-cherry-pick-1.1, size/small, translation/no-need

#402 zh: fix a broken link
  zh/deploy-tidb-operator.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, size/small, translation/doing, translation/done

#404 en: fix a broken link for CustomResourceDefinition
  en/deploy-tidb-from-kubernetes-gke.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, size/small, translation/from-zh

#412 en: fix a broken link
  en/deploy-tidb-operator.md
Labels: needs-cherry-pick-1.1, size/small, translation/from-zh

#413 en: fix a broken link
  en/deploy-tidb-operator.md
Labels: size/small, status/can-merge

#415 zh: fix a broken link
  zh/deploy-tidb-from-kubernetes-gke.md
Labels: needs-cherry-pick-1.1, size/small, status/can-merge, translation/from-en

#405 en: add aliases in get-started
  en/get-started.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/no-need, version-split-changes-required

#379 en, zh: Update tidb-operator version to v1.1.0 in kind tutorial
  zh/deploy-tidb-from-kubernetes-kind.md
Labels: needs-cherry-pick-1.1, translation/done

#390 en: revise the tidbcluster scaling doc
  en/enable-tidb-cluster-auto-scaling.md
  en/scale-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT1, status/can-merge, translation/from-zh

#424 zh: update the api-reference link
  zh/TOC.md
  zh/api-references.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/initialize-a-cluster.md
  zh/monitor-using-tidbmonitor.md
  zh/notes-tidb-operator-v1.1.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/doing

#400 zh: tidb-operator offline installation
  zh/deploy-tidb-operator.md
  zh/tidb-toolkit.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/doing

#420 zh: tidb cluster offline installation
  zh/deploy-on-general-kubernetes.md
  zh/deploy-ticdc.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tiflash.md
  zh/initialize-a-cluster.md
  zh/monitor-using-tidbmonitor.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/doing

#436 Update 1.1 api-reference document
  zh/TOC.md
  zh/api-references.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/initialize-a-cluster.md
  zh/monitor-using-tidbmonitor.md
  zh/notes-tidb-operator-v1.1.md
Labels: status/can-merge, translation/no-need

#438 zh: fix monitor
  zh/monitor-using-tidbmonitor.md
Labels: needs-cherry-pick-1.1

#421 zh: update eks doc for demo and product deployments
  zh/deploy-on-aws-eks.md
Labels: needs-cherry-pick-1.1, translation/doing

#437 en: describe how to use alternative images in get started tutorial
  en/get-started.md
Labels: needs-cherry-pick-1.1, translation/doing

#445 en: udpate index with new format and fix links
  en/TOC.md
  en/_index.md
  en/deploy-on-general-kubernetes.md
Labels: needs-cherry-pick-1.1, status/PTAL, translation/from-zh

#432 zh: revise access-dashboard document
  zh/access-dashboard.md
Labels: needs-cherry-pick-1.1, translation/doing

#439 en: fix tidb-operator chart notes
  en/get-started.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/no-need

#453 en: update get-started
  en/get-started.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/welcome

#452 en: update access-dashboard
  en/access-dashboard.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/from-zh

#449 zh: fix timezone
  zh/faq.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/doing

#394 zh: add local-volume-provisioner offline installation document
  zh/configure-storage-class.md
Labels: needs-cherry-pick-1.1, translation/doing

#448 en: add ticdc to ack and eks
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/from-zh

#460 en: update operator version
  en/get-started.md
Labels: needs-cherry-pick-1.1, translation/welcome

#462 en: fix the "Debugging DNS Resolution" link
  en/troubleshoot.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, size/small, status/DNM, translation/done

#463 zh: fix a DNS debugging link
  zh/troubleshoot.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, size/small, status/can-merge, translation/from-en

#464 zh: update the API reference link
  zh/_index.md
Labels: needs-cherry-pick-1.1, size/small, status/can-merge, translation/no-need

#475 en: fix indent error in secret yaml
  en/restore-data-using-tidb-lightning.md
Labels: needs-cherry-pick-1.1, size/small, status/can-merge, translation/from-zh

#469 en: optimize the upgrade doc for tidb and operator
  en/upgrade-a-tidb-cluster.md
  en/upgrade-tidb-operator.md
Labels: needs-cherry-pick-1.1, translation/from-zh

#467 en: reorg the disaster recovery part
  en/TOC.md
  en/recover-deleted-cluster.md
  en/troubleshoot.md
Labels: needs-cherry-pick-1.1, size/medium, translation/from-zh

#468 en: remove steps in initialization headings
  en/initialize-a-cluster.md
Labels: needs-cherry-pick-1.1, size/small, translation/from-zh

#428 en: add what's new in v1.1
  en/TOC.md
  en/whats-new-in-v1.1.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/from-zh

#496 en: batch add aliases to dev
  en/_index.md
  en/access-dashboard.md
  en/access-tidb.md
  en/advanced-statefulset.md
  en/api-references.md
  en/backup-and-restore-using-helm-charts.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs.md
  en/backup-to-s3.md
  en/benchmark-sysbench.md
  en/cheat-sheet.md
  en/collect-tidb-logs.md
  en/configure-a-tidb-cluster.md
  en/configure-backup.md
  en/configure-storage-class.md
  en/configure-tidb-binlog-drainer.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  en/deploy-ticdc.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/deploy-tiflash.md
  en/destroy-a-tidb-cluster.md
  en/enable-admission-webhook.md
  en/enable-tidb-cluster-auto-scaling.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/faq.md
  en/get-started.md
  en/initialize-a-cluster.md
  en/maintain-a-kubernetes-node.md
  en/monitor-a-tidb-cluster.md
  en/monitor-using-tidbmonitor.md
  en/notes-tidb-operator-v1.1.md
  en/pd-recover.md
  en/prerequisites.md
  en/recover-deleted-cluster.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs.md
  en/restore-from-s3.md
  en/scale-a-tidb-cluster.md
  en/tidb-cluster-chart-config.md
  en/tidb-operator-overview.md
  en/tidb-scheduler.md
  en/tidb-toolkit.md
  en/troubleshoot.md
  en/upgrade-a-tidb-cluster.md
  en/upgrade-tidb-operator.md
  en/use-auto-failover.md
  en/use-tkctl.md
  en/whats-new-in-v1.1.md
Labels: size/large, status/can-merge, translation/no-need

#497 en: batch add aliases to 1.1 branch
  en/_index.md
  en/access-dashboard.md
  en/access-tidb.md
  en/advanced-statefulset.md
  en/api-references.md
  en/backup-and-restore-using-helm-charts.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs.md
  en/backup-to-s3.md
  en/benchmark-sysbench.md
  en/cheat-sheet.md
  en/collect-tidb-logs.md
  en/configure-a-tidb-cluster.md
  en/configure-backup.md
  en/configure-storage-class.md
  en/configure-tidb-binlog-drainer.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  en/deploy-ticdc.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/deploy-tiflash.md
  en/destroy-a-tidb-cluster.md
  en/enable-admission-webhook.md
  en/enable-tidb-cluster-auto-scaling.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/faq.md
  en/get-started.md
  en/initialize-a-cluster.md
  en/maintain-a-kubernetes-node.md
  en/monitor-a-tidb-cluster.md
  en/monitor-using-tidbmonitor.md
  en/notes-tidb-operator-v1.1.md
  en/pd-recover.md
  en/prerequisites.md
  en/recover-deleted-cluster.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs.md
  en/restore-from-s3.md
  en/scale-a-tidb-cluster.md
  en/tidb-cluster-chart-config.md
  en/tidb-operator-overview.md
  en/tidb-scheduler.md
  en/tidb-toolkit.md
  en/troubleshoot.md
  en/upgrade-a-tidb-cluster.md
  en/upgrade-tidb-operator.md
  en/use-auto-failover.md
  en/use-tkctl.md
  en/whats-new-in-v1.1.md
Labels: translation/no-need

#498 en: batch add aliases to 1.0 branch
  en/_index.md
  en/access-tidb.md
  en/backup-and-restore-using-helm-charts.md
  en/benchmark-sysbench.md
  en/collect-tidb-logs.md
  en/configure-a-tidb-cluster.md
  en/configure-backup.md
  en/configure-storage-class.md
  en/configure-tidb-binlog-drainer.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-from-kubernetes-kind.md
  en/deploy-tidb-from-kubernetes-minikube.md
  en/deploy-tidb-operator.md
  en/destroy-a-tidb-cluster.md
  en/faq.md
  en/initialize-a-cluster.md
  en/maintain-a-kubernetes-node.md
  en/monitor-a-tidb-cluster.md
  en/pd-recover.md
  en/prerequisites.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/scale-a-tidb-cluster.md
  en/tidb-operator-overview.md
  en/tidb-scheduler.md
  en/tidb-toolkit.md
  en/troubleshoot.md
  en/upgrade-a-tidb-cluster.md
  en/upgrade-tidb-operator.md
  en/use-auto-failover.md
  en/use-tkctl.md
Labels: translation/no-need

#483 en, zh: add scheduler scheduling based on customer topology
  en/tidb-scheduler.md
  zh/tidb-scheduler.md
Labels: contribution, needs-cherry-pick-1.1, status/can-merge

#501 Remove _index/ in the alias
  en/_index.md
Labels: needs-cherry-pick-1.0, translation/no-need

#500 en: add stable aliases to 1.1 branch files
  en/_index.md
  en/access-dashboard.md
  en/access-tidb.md
  en/advanced-statefulset.md
  en/api-references.md
  en/backup-and-restore-using-helm-charts.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs.md
  en/backup-to-s3.md
  en/benchmark-sysbench.md
  en/cheat-sheet.md
  en/collect-tidb-logs.md
  en/configure-a-tidb-cluster.md
  en/configure-backup.md
  en/configure-storage-class.md
  en/configure-tidb-binlog-drainer.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  en/deploy-ticdc.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/deploy-tiflash.md
  en/destroy-a-tidb-cluster.md
  en/enable-admission-webhook.md
  en/enable-tidb-cluster-auto-scaling.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/faq.md
  en/get-started.md
  en/initialize-a-cluster.md
  en/maintain-a-kubernetes-node.md
  en/monitor-a-tidb-cluster.md
  en/monitor-using-tidbmonitor.md
  en/notes-tidb-operator-v1.1.md
  en/pd-recover.md
  en/prerequisites.md
  en/recover-deleted-cluster.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs.md
  en/restore-from-s3.md
  en/scale-a-tidb-cluster.md
  en/tidb-cluster-chart-config.md
  en/tidb-operator-overview.md
  en/tidb-scheduler.md
  en/tidb-toolkit.md
  en/troubleshoot.md
  en/upgrade-a-tidb-cluster.md
  en/upgrade-tidb-operator.md
  en/use-auto-failover.md
  en/use-tkctl.md
  en/whats-new-in-v1.1.md
Labels: translation/no-need

#459 en: update view logs and collect logs
  en/TOC.md
  en/collect-tidb-logs.md
  en/logs-collection.md
  en/tidb-operator-overview.md
  en/view-logs.md
  zh/logs-collection.md
Labels: needs-cherry-pick-1.1, translation/from-zh

#388 en, zh: move tidb-operator architecture section to a new page
  en/TOC.md
  en/architecture.md
  en/tidb-operator-overview.md
  zh/TOC.md
  zh/architecture.md
  zh/tidb-operator-overview.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/done

#393 en: updated docs links to stable instead of version-specific URLs
  en/backup-and-restore-using-helm-charts.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs.md
  en/backup-to-s3.md
  en/configure-a-tidb-cluster.md
  en/configure-backup.md
  en/deploy-tidb-binlog.md
  en/enable-tls-for-mysql-client.md
  en/faq.md
  en/monitor-a-tidb-cluster.md
  en/prerequisites.md
  en/restore-data-using-tidb-lightning.md
  en/restore-from-aws-s3-using-br.md
  en/tidb-cluster-chart-config.md
  en/tidb-toolkit.md
  en/troubleshoot.md
  en/use-auto-failover.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/doing

#440 en: add warning in cluster deletion
  en/destroy-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, translation/from-zh

#444 en: reorg prerequisites
  en/prerequisites.md
Labels: needs-cherry-pick-1.1, status/can-merge, status/require-change, translation/from-zh

#476 en: update config; update api reference link
  en/api-references.md
  en/configure-a-tidb-cluster.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/initialize-a-cluster.md
  en/monitor-using-tidbmonitor.md
  en/notes-tidb-operator-v1.1.md
  zh/whats-new-in-v1.1.md
Labels: needs-cherry-pick-1.1, size/small, translation/from-zh

#513 en: fix the affinity link
  en/configure-a-tidb-cluster.md
Labels: size/small, status/can-merge, translation/from-zh

#515 en, zh: add warning for configuring multiple pvs for tiflash
  en/configure-a-tidb-cluster.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-tiflash.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tiflash.md
Labels: needs-cherry-pick-1.1, translation/done

#512 zh: fix the affinity link
  zh/configure-a-tidb-cluster.md
Labels: size/small, status/can-merge, translation/done

#471 en: changed warning message about deleting PVs
  en/configure-storage-class.md
Labels: needs-cherry-pick-1.1, translation/welcome

#511 en, zh: Add telemetry notes
  en/access-dashboard.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/upgrade-tidb-operator.md
  zh/access-dashboard.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-from-kubernetes-kind.md
  zh/deploy-tidb-from-kubernetes-minikube.md
  zh/upgrade-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, translation/done

#503 en: add helm offline doc
  en/tidb-toolkit.md
Labels: needs-cherry-pick-1.1, translation/from-zh

#522 zh: add aliases for kind deployment
  zh/deploy-tidb-from-kubernetes-kind.md
Labels: status/can-merge, translation/no-need
