Repository pingcap/docs-tidb-operator, pull requests merged in 2020-11, with the labels that each got.

#813 en: remove dead link for tiflash
  en/deploy-tiflash.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/from-zh

#791 zh: add 1.1-ga chinese release notes
  zh/releases/release-1.1-ga.md
Labels: needs-cherry-pick-1.1, require-LGT1, status/LGT1, translation/from-en

#694 .github: add external link check
  .github/workflows/ci.yaml
  .github/workflows/link-check.yaml
  en/configure-a-tidb-cluster.md
  en/enable-admission-webhook.md
  zh/configure-a-tidb-cluster.md
  zh/enable-admission-webhook.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/LGT1, status/PTAL, translation/no-need

#819 update roadmap
  en/TOC.md
  en/roadmap.md
  zh/TOC.md
  zh/roadmap.md
Labels: require-LGT1, status/LGT1, status/can-merge, translation/done

#821 Add 4 aliases to fix broken links
  en/backup-and-restore-using-helm-charts.md
  en/configure-storage-class.md
  zh/logs-collection.md
  zh/upgrade-a-tidb-cluster.md
  zh/use-auto-failover.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#822 filter one external link to pass ci check
  .github/workflows/link-check.yaml
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/LGT1, translation/no-need

#825 readme: add google translate links of French, Japanese, Korean
  README.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/LGT1, status/PTAL, translation/no-need

#798 zh: add 1.1-beta.1 release notes
  zh/releases/release-1.1.0-beta.1.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/from-en

#807 zh: fix deploy-tidb-binlog.md
  zh/deploy-tidb-binlog.md
Labels: first-time-contributor, needs-cherry-pick-1.1, status/LGT2, status/PTAL, status/can-merge, translation/doing

#810 zh: Improve deploy tidb monitor docs
  zh/access-dashboard.md
  zh/monitor-a-tidb-cluster.md
  zh/monitor-using-tidbmonitor.md
  zh/pd-recover.md
Labels: first-time-contributor, needs-cherry-pick-1.1, require-LGT1, status/LGT1, status/PTAL, status/can-merge, translation/doing

#820 zh: fix pdAddresses
  zh/migrate-tidb-to-kubernetes.md
Labels: needs-cherry-pick-1.1, require-LGT1, status/LGT1, status/PTAL, status/can-merge, translation/doing

#833 en: fix pdAddresses
  en/migrate-tidb-to-kubernetes.md
Labels: status/LGT1, translation/from-zh

#801 zh: refactor get-started.md
  zh/get-started.md
Labels: first-time-contributor, needs-cherry-pick-1.1, status/LGT2, status/PTAL, status/can-merge, translation/doing

#812 zh, en: update BR doc about omitting the spec.from/to when using new version
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-gcs.md
  en/backup-to-s3.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs-using-br.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-gcs.md
  zh/backup-to-s3.md
  zh/restore-from-aws-s3-using-br.md
  zh/restore-from-gcs-using-br.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#802 zh: Improve deploy on AWS EKS
  zh/deploy-on-aws-eks.md
Labels: first-time-contributor, needs-cherry-pick-1.1, status/LGT2, status/PTAL, status/can-merge, translation/doing, version-specific-changes-required

#803 zh: improve deploy-on-gcp-gke.md as in aws doc
  zh/deploy-on-gcp-gke.md
Labels: first-time-contributor, needs-cherry-pick-1.1, status/LGT1, status/PTAL, translation/doing, version-specific-changes-required

#804 zh: Improve self-hosted k8s deployment
  zh/configure-a-tidb-cluster.md
  zh/configure-storage-class.md
  zh/deploy-tidb-operator.md
  zh/prerequisites.md
Labels: first-time-contributor, needs-cherry-pick-1.1, status/LGT2, status/PTAL, status/can-merge, translation/doing

#847 en, zh: update release note for v1.1.6
  en/releases/release-1.1.6.md
  zh/releases/release-1.1.6.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/done

#844 en, zh: bump tidb version to 4.0.8
  en/access-dashboard.md
  en/access-tidb.md
  en/advanced-statefulset.md
  en/configure-a-tidb-cluster.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-enterprise-edition.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/monitor-using-tidbmonitor.md
  en/notes-tidb-operator-v1.1.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/access-tidb.md
  zh/advanced-statefulset.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-enterprise-edition.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
  zh/monitor-using-tidbmonitor.md
  zh/notes-tidb-operator-v1.1.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-data-using-tidb-lightning.md
  zh/upgrade-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, require-LGT1, status/LGT2, status/can-merge, translation/done

#851 en, zh: bump tidb operator charts version to v1.1.7
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#845 en, zh: add release notes for v1.1.7
  en/TOC.md
  en/releases/release-1.1.7.md
  zh/TOC.md
  zh/releases/release-1.1.7.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#854 CI: update conflicts check to support yml and yaml files
  .github/workflows/ci.yaml
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/LGT1, status/PTAL, translation/no-need

#857 releases: fix full-width hash sign resulting in lint failure
  zh/releases/release-1.1.0-rc.4.md
Labels: needs-cherry-pick-1.1, require-LGT1, status/LGT1, status/can-merge, translation/no-need

#837 en: Improve deploy tidb monitor docs
  en/access-dashboard.md
  en/monitor-a-tidb-cluster.md
  en/monitor-using-tidbmonitor.md
  en/pd-recover.md
  zh/access-dashboard.md
  zh/pd-recover.md
Labels: needs-cherry-pick-1.1, status/LGT1, status/PTAL, translation/from-zh

#842 en: Improve self-hosted k8s deployment
  en/configure-a-tidb-cluster.md
  en/configure-storage-class.md
  en/deploy-tidb-operator.md
  en/prerequisites.md
Labels: needs-cherry-pick-1.1, status/LGT1, status/PTAL, translation/from-zh

#843 en: improve deploy on aws eks
  en/deploy-on-aws-eks.md
  zh/deploy-on-aws-eks.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/from-zh, version-specific-changes-required

#840 en: refactor get-started
  en/get-started.md
  zh/get-started.md
Labels: needs-cherry-pick-1.1, status/LGT1, status/PTAL, translation/from-zh

#846 zh: mount multiple pv for tidbcluster
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/doing

#838 en: fix deploy-tidb-binlog.md
  en/deploy-tidb-binlog.md
Labels: needs-cherry-pick-1.1, status/LGT1, status/PTAL, translation/from-zh

#868 Add 3 aliases to fix broken links
  en/logs-collection.md
  en/use-tkctl.md
  zh/restore-data-using-tidb-lightning.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#870 en: mount multiple pv for tidbcluster
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/from-zh

#863 en: improve deploy-on-gcp-gke
  en/deploy-on-gcp-gke.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/from-zh, version-specific-changes-required

#873 chore: remove copyable snippet code when generate PDF
  .circleci/config.yml
  scripts/merge_by_toc.py
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/LGT1, translation/no-need

#879 Media: Delete images that involve third-party logos
  media/tidb-operator-control-flow.png
  media/tidb-operator-overview.png
Labels: needs-cherry-pick-1.1, status/LGT1, translation/no-need
