Repository pingcap/docs-tidb-operator, pull requests merged in 2020-08, with the labels that each got.

#610 .github: add cherry-pick checklist in pr template
  .github/pull_request_template.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/LGT1, translation/no-need

#614 en: fix a broken link
  en/initialize-a-cluster.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/LGT1, translation/no-need, type/bug-fix, version-specific-changes-required

#616 en: fix a dead link
  en/access-tidb.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#619 en, zh: get rid of evil words
  en/deploy-tidb-binlog.md
  zh/deploy-tidb-binlog.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#623 Add aliases to 36 files on release-1.0 branch
  zh/_index.md
  zh/access-tidb.md
  zh/backup-and-restore-using-helm-charts.md
  zh/benchmark-sysbench.md
  zh/collect-tidb-logs.md
  zh/configure-a-tidb-cluster.md
  zh/configure-backup.md
  zh/configure-storage-class.md
  zh/configure-tidb-binlog-drainer.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-from-kubernetes-kind.md
  zh/deploy-tidb-from-kubernetes-minikube.md
  zh/deploy-tidb-operator.md
  zh/destroy-a-tidb-cluster.md
  zh/faq.md
  zh/initialize-a-cluster.md
  zh/maintain-a-kubernetes-node.md
  zh/monitor-a-tidb-cluster.md
  zh/pd-recover.md
  zh/prerequisites.md
  zh/restart-a-tidb-cluster.md
  zh/restore-data-using-tidb-lightning.md
  zh/scale-a-tidb-cluster.md
  zh/tidb-operator-overview.md
  zh/tidb-scheduler.md
  zh/tidb-toolkit.md
  zh/troubleshoot.md
  zh/upgrade-a-tidb-cluster.md
  zh/upgrade-tidb-operator.md
  zh/use-auto-failover.md
  zh/use-tkctl.md
Labels: status/LGT1, translation/no-need

#603 en: add how to delete backup cr
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-gcs.md
  en/backup-to-s3.md
  en/deploy-on-aws-eks.md
Labels: needs-cherry-pick-1.1, require-LGT1, status/LGT1, status/can-merge, translation/from-zh

#626 en, zh: update index to include what's new in v1.1
  en/_index.md
  zh/_index.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/done

#630 Add an alias to fix a dead link
  en/get-started.md
  zh/get-started.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#611 en: stop tidb gracefully
  en/access-tidb.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#628 en: enable tls for ticdc
  en/deploy-ticdc.md
  en/enable-tls-between-components.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#631 en, zh: update wording to include elastic scheduling
  en/enable-tidb-cluster-auto-scaling.md
  zh/enable-tidb-cluster-auto-scaling.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/done

#636 en,zh: update what's new title
  en/whats-new-in-v1.1.md
  zh/whats-new-in-v1.1.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/done

#641 Add aliases to fix 2 dead links
  en/get-started.md
  zh/get-started.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#638 zh: add single page to describe enterprise edition deployment
  zh/TOC.md
  zh/deploy-tidb-enterprise-edition.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/doing

#643 en: add single page to describe enterprise edition deployment
  en/TOC.md
  en/deploy-tidb-enterprise-edition.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL, status/require-change, translation/from-zh

#647 zh: remove an extra line in code block
  zh/get-started.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/no-need

#584 zh: simplify AWS/EKS deployment guide
  zh/deploy-on-aws-eks.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL, status/can-merge, translation/doing

#639 zh: add debug section for backup restore, comment storageClassName by default
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-gcs.md
  zh/backup-to-s3.md
  zh/deploy-failures.md
  zh/restore-from-aws-s3-using-br.md
  zh/restore-from-gcs-using-br.md
  zh/restore-from-gcs.md
  zh/restore-from-s3.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL, status/can-merge, status/require-change, translation/doing

#653 cherry-pick #584 to release-1.1: zh: simplify AWS/EKS deployment guide
  zh/deploy-on-aws-eks.md
Labels: status/LGT2

#654 zh: update tls doc for tiflash
  zh/enable-tls-between-components.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#660 en: update instance type for tikv
  en/deploy-on-aws-eks.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/no-need

#658 en: update tls doc for tiflash
  en/enable-tls-between-components.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/from-zh

#655 zh: add prompt to offline tidb-binlog components
  zh/deploy-tidb-binlog.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#659 en: add debug section for backup & restore
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-gcs.md
  en/backup-to-s3.md
  en/deploy-failures.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs-using-br.md
  en/restore-from-gcs.md
  en/restore-from-s3.md
Labels: needs-cherry-pick-1.1, status/LGT1, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#670 Add 7 aliases to fix dead links
  en/get-started.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/initialize-a-cluster.md
  zh/restore-from-aws-s3-using-br.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#675 Add 8 aliases to fix dead links
  en/destroy-a-tidb-cluster.md
  en/get-started.md
  en/maintain-a-kubernetes-node.md
  en/monitor-a-tidb-cluster.md
  en/tips.md
  zh/initialize-a-cluster.md
  zh/restore-from-gcs.md
  zh/tips.md
Labels: status/LGT1, translation/no-need, type/bug-fix
