Repository pingcap/docs-tidb-operator, pull requests merged in 2020-05, with the labels that each got.

#239 ci: update media.yml
  .github/workflows/media.yml
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1

#237 zh,en: fix tls directory issue
  en/deploy-on-gcp-gke.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/done

#242 Fixed tlsClient -> tlsCluster
  en/enable-tls-between-components.md
Labels: needs-cherry-pick-1.1, translation/doing

#231 en: update a title in toc
  en/TOC.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs.md
  en/backup-to-s3.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-s3.md
Labels: needs-cherry-pick-1.1, translation/no-need

#245 zh: add pd-recover doc
  zh/TOC.md
  zh/pd-recover.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1

#233 en, zh: update doc for backup and restore
  en/TOC.md
  en/backup-and-restore-using-helm-charts.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-s3.md
  en/notes-tidb-operator-v1.1.md
  en/restore-data-using-tidb-lightning.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs.md
  en/restore-from-s3.md
  zh/TOC.md
  zh/backup-and-restore-using-helm-charts.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs.md
  zh/backup-to-s3.md
  zh/notes-tidb-operator-v1.1.md
  zh/restore-data-using-tidb-lightning.md
  zh/restore-from-aws-s3-using-br.md
  zh/restore-from-gcs.md
  zh/restore-from-s3.md
Labels: needs-cherry-pick-1.1, status/require-change, translation/done

#252 zh: rewording for cluster id
  zh/pd-recover.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1

#250 en: add pd-recover doc
  en/TOC.md
  en/pd-recover.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, priority/P1, translation/from-zh

#261 fix: add closing tag for 'br'
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, translation/done

#264 zh, en: change <br> to <br/>
  en/tidb-cluster-chart-config.md
  zh/tidb-cluster-chart-config.md
Labels: translation/done

#259 zh: fix typo in deploy tiflash
  zh/deploy-tiflash.md
Labels: translation/doing

#265 zh: fix typo in deploy tiflash
  zh/deploy-tiflash.md
Labels: translation/no-need

#269 en, zh: update helm version and command to search chart
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-from-kubernetes-kind.md
  en/deploy-tidb-from-kubernetes-minikube.md
  en/deploy-tidb-operator.md
  en/tidb-toolkit.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-from-kubernetes-kind.md
  zh/deploy-tidb-from-kubernetes-minikube.md
  zh/deploy-tidb-operator.md
  zh/tidb-toolkit.md
Labels: needs-cherry-pick-1.1

#268 zh: update doc for tiflash on eks and ack
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/scale-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, translation/doing

#263 zh: simplify kind tutorial
  zh/deploy-tidb-from-kubernetes-kind.md
Labels: needs-cherry-pick-1.1, status/can-merge, status/require-change, translation/doing

#234 zh: Add TidbMonitor Ingress in monitor document
  zh/monitor-using-tidbmonitor.md
Labels: needs-cherry-pick-1.1, status/require-change, translation/doing

#277 zh: add doc to enable cross-zone load balancing for nlb
  zh/deploy-on-aws-eks.md
Labels: needs-cherry-pick-1.1, translation/doing

#279 en: simplify kind tutorial
  en/deploy-tidb-from-kubernetes-kind.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/from-zh

#282 en: add a link in kind tutorial
  en/deploy-tidb-from-kubernetes-kind.md
Labels: size/small, translation/no-need, type/bug-fix

#273 zh: Update mydumper backup docs
  zh/backup-to-gcs.md
  zh/backup-to-s3.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/doing

#235 zh: Add TiDB Dashboard document
  zh/TOC.md
  zh/access-dashboard.md
Labels: needs-cherry-pick-1.1, translation/doing

#272 en: update doc for tiflash
  en/TOC.md
  en/configure-cluster-using-tidbcluster.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tiflash.md
  en/scale-a-tidb-cluster.md
  en/use-auto-failover.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/from-zh

#286 zh: fix a broken link
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, size/small, translation/doing

#289 en: fix a broken link
  en/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, size/small, translation/from-zh

#275 zh: separate client certificates for each component
  zh/enable-tls-for-mysql-client.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/doing

#293 scripts: add a script to run markdownlint check locally
  scripts/markdownlint
Labels: status/can-merge, translation/no-need

#294 en, zh: update hostname to host
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, translation/done

#296 en, zh: update toc
  en/TOC.md
  zh/TOC.md
Labels: needs-cherry-pick-1.1, translation/done

#299 en, zh: update toc
  en/TOC.md
  zh/TOC.md
Labels: needs-cherry-pick-1.1, translation/done

#301 trigger pull request CI on all branches
  .github/workflows/ci.yaml
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, translation/no-need

#307 .github: add workflow to auto assign to projects
  .github/workflows/assign-to-project.yml
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1

#311 configure-tidb-binlog-drainer: fix the nodeselector links
  en/configure-tidb-binlog-drainer.md
  en/tidb-cluster-chart-config.md
  zh/configure-tidb-binlog-drainer.md
  zh/tidb-cluster-chart-config.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, size/small, translation/done

#305 en: add doc for access tidb dashboard
  en/TOC.md
  en/access-dashboard.md
Labels: needs-cherry-pick-1.1, translation/from-zh, v1.1

#314 zh: add tikv-ctl document
  zh/enable-tls-between-components.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/doing

#298 zh: cdc document
  zh/TOC.md
  zh/configure-cluster-using-tidbcluster.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-ticdc.md
  zh/scale-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, translation/doing, v1.1

#320 en, zh: add tikv-ctl in tls document
  en/enable-tls-between-components.md
  zh/enable-tls-between-components.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/from-zh

#276 en: update doc for tiflash on eks and ack
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/scale-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, translation/from-zh

#327 zh: fix a typo in backup-to-gcs
  zh/backup-to-gcs.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/done

#321 zh: refine tls document
  zh/enable-tls-for-mysql-client.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/done, v1.1

#304 en: update doc to enable cross-zone load balancing
  en/deploy-on-aws-eks.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/from-zh, v1.1

#318 en: update mydumper backup docs
  en/backup-to-gcs.md
  en/backup-to-s3.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/from-zh, v1.1

#334 zh: fix build issue in release 1.0
  zh/configure-backup.md
Labels: translation/no-need

#335 en, zh: fix build issues in toc
  en/TOC.md
  zh/TOC.md
Labels: needs-cherry-pick-1.1, translation/done

#331 en: add ticdc doc
  en/TOC.md
  en/configure-cluster-using-tidbcluster.md
  en/deploy-on-general-kubernetes.md
  en/deploy-ticdc.md
  en/scale-a-tidb-cluster.md
  zh/configure-cluster-using-tidbcluster.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/from-zh, v1.1

#322 en: separate client certificates for each component
  en/enable-tls-for-mysql-client.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/from-zh, v1.1

#343 en, zh: update toc
  en/TOC.md
  zh/TOC.md
Labels: needs-cherry-pick-1.1, status/can-merge

#338 zh: add cheat sheet
  zh/TOC.md
  zh/cheat-sheet.md
Labels: needs-cherry-pick-1.1, translation/doing

#349 Update landing page _index.md for TiDB Operator
  zh/_index.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, translation/doing

#355 Revert "Update landing page _index.md for TiDB Operator (#349)"
  zh/_index.md
Labels: translation/no-need

#325 zh: what's new in v1.1
  zh/TOC.md
  zh/whats-new-in-v1.1.md
Labels: needs-cherry-pick-1.1, translation/doing

#359 tidb-cluster-chart-config: fix affinity links
  en/configure-tidb-binlog-drainer.md
  en/tidb-cluster-chart-config.md
  zh/configure-tidb-binlog-drainer.md
  zh/tidb-cluster-chart-config.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, size/small, translation/done
