Repository pingcap/docs-tidb-operator, pull requests merged in 2020-10, with the labels that each got.

#753 zh: update steps for heterogeneous cluster deployment
  zh/deploy-heterogeneous-tidb-cluster.md
Labels: hacktoberfest-accepted, needs-cherry-pick-1.1, status/LGT1, translation/no-need

#755 en, zh: add roadmap
  en/TOC.md
  en/roadmap.md
  zh/TOC.md
  zh/roadmap.md
Labels: require-LGT1, status/LGT2, status/PTAL, status/can-merge, translation/done, v1.2

#756 Add 12 aliases to fix dead links
  en/deploy-tidb-operator.md
  en/get-started.md
  en/upgrade-tidb-operator.md
  zh/benchmark-sysbench.md
  zh/deploy-on-alibaba-cloud.md
  zh/initialize-a-cluster.md
  zh/logs-collection.md
  zh/restore-from-gcs.md
  zh/scale-a-tidb-cluster.md
  zh/upgrade-tidb-operator.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#757 zh: Doc update for monitoring multiple TiDB clusters with one TidbMonitor
  zh/monitor-using-tidbmonitor.md
Labels: contribution, needs-cherry-pick-1.1, status/LGT2, translation/doing

#758 zh: update for logs of tiflash
  zh/configure-a-tidb-cluster.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tiflash.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#760 en, zh: Add incremental backup
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-gcs.md
  en/backup-to-s3.md
  en/notes-tidb-operator-v1.1.md
  en/restore-from-gcs-using-br.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-gcs.md
  zh/backup-to-s3.md
  zh/notes-tidb-operator-v1.1.md
  zh/restore-from-gcs-using-br.md
Labels: first-time-contributor, needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#765 en, zh: Add docs about passing raw TOML config
  en/configure-a-tidb-cluster.md
  en/deploy-tidb-binlog.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-tidb-binlog.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#766 en, zh: update notes for tidb-cluster chart
  en/notes-tidb-operator-v1.1.md
  zh/notes-tidb-operator-v1.1.md
Labels: needs-cherry-pick-1.1, require-LGT1, status/LGT1, status/can-merge, translation/done

#769 en, zh: bump tidb version to 4.0.7
  en/access-dashboard.md
  en/access-tidb.md
  en/advanced-statefulset.md
  en/configure-a-tidb-cluster.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-enterprise-edition.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/monitor-using-tidbmonitor.md
  en/notes-tidb-operator-v1.1.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/access-tidb.md
  zh/advanced-statefulset.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-enterprise-edition.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
  zh/monitor-using-tidbmonitor.md
  zh/notes-tidb-operator-v1.1.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-data-using-tidb-lightning.md
  zh/upgrade-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#763 en, zh: Add v1.1.6 release notes
  en/TOC.md
  en/releases/release-1.1.6.md
  zh/TOC.md
  zh/releases/release-1.1.6.md
Labels: needs-cherry-pick-1.1, status/DNM, status/LGT3, status/can-merge, translation/done

#772 zh, en: update tidb-operator chart version to v1.1.6
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/LGT3

#704 zh: migrate-tidb-to-kubernetes
  zh/migrate-tidb-to-kubernetes.md
Labels: contribution, status/LGT2, status/can-merge, translation/doing, v1.2

#775 zh: update toc
  zh/TOC.md
Labels: require-LGT1, status/LGT1, translation/no-need

#750 zh: translate release-1.1.1 document
  zh/releases/release-1.1.1.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, status/require-change, translation/from-en

#777 en, zh: update release notes for v1.1.6
  en/releases/release-1.1.6.md
  zh/releases/release-1.1.6.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/done

#724 en, zh: update documentation about PodRestarter
  en/restart-a-tidb-cluster.md
  zh/restart-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/require-change, translation/done

#742 zh: add dmcluster usage document
  zh/TOC.md
  zh/deploy-tidb-dm.md
  zh/enable-tls-for-dm.md
Labels: status/LGT2, status/can-merge, translation/doing, v1.2

#752 en: update unsupported tidb dashboard functions
  en/access-dashboard.md
Labels: hacktoberfest-accepted, needs-cherry-pick-1.1, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#780 en, zh: add a doc for migrating tidb to k8s
  en/TOC.md
  en/migrate-tidb-to-kubernetes.md
  zh/migrate-tidb-to-kubernetes.md
Labels: status/LGT2, status/PTAL, status/can-merge, translation/from-zh, v1.2

#764 zh: add v1.1-rc.1 release notes
  zh/releases/release-1.1.0-rc.1.md
Labels: needs-cherry-pick-1.1, require-LGT1, status/LGT1, status/can-merge, translation/from-en

#774 .github: add 2 exempt issue labels
  .github/workflows/stale.yaml
Labels: status/LGT1, status/PTAL, translation/no-need, type/enhancement

#782 en: Doc update for monitoring multiple TiDB clusters with one TidbMonitor
  en/monitor-using-tidbmonitor.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/from-zh

#786 CI: Add conflicts check and test files
  .github/workflows/ci.yaml
  hack/check-conflicts.py
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/LGT1, status/PTAL, translation/no-need

#789 fix: trim trailing whitespace
  en/migrate-tidb-to-kubernetes.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#785 en: update for logs of tiflash
  en/configure-a-tidb-cluster.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tiflash.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#794 zh: delete docs about using kubectl apply to update tidb cluster configurations
  zh/deploy-failures.md
  zh/deploy-tidb-enterprise-edition.md
  zh/restart-a-tidb-cluster.md
  zh/scale-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#796 Add 6 aliases to fix dead links
  en/backup-and-restore-using-helm-charts.md
  en/configure-tidb-binlog-drainer.md
  zh/configure-backup.md
  zh/deploy-on-general-kubernetes.md
  zh/get-started.md
  zh/prerequisites.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#797 en: delete docs about using kubectl apply to update tidb cluster configurations
  en/deploy-failures.md
  en/deploy-tidb-enterprise-edition.md
  en/restart-a-tidb-cluster.md
  en/scale-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/from-zh

#800 en: fix a sentence
  en/restart-a-tidb-cluster.md
Labels: require-LGT1, status/LGT2, translation/no-need

#792 en: add dmcluster usage document
  en/TOC.md
  en/access-tidb.md
  en/deploy-tidb-dm.md
  en/enable-tls-for-dm.md
Labels: status/LGT2, translation/from-zh, v1.2

#740 zh: translate for release note 1.1rc.4
  zh/releases/release-1.1.0-rc.4.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/from-en

#723 zh: translate TiDB Operator 1.1 Beta.2 Release Notes to Chinese
  zh/releases/release-1.1.0-beta.2.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/from-en

#806 zh: remove dead link for tiflash
  zh/deploy-tiflash.md
Labels: first-time-contributor, needs-cherry-pick-1.1, status/LGT1, translation/doing
