Repository pingcap/docs-tidb-operator, pull requests merged in 2020-12, with the labels that each got.

#881 add guide of signing CLA
  .github/pull_request_template.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/LGT1, status/PTAL, translation/no-need

#884 .github: update contributing guide link
  .github/pull_request_template.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/LGT1, translation/no-need

#887 s3: fix restore yaml example
  en/restore-from-s3.md
  zh/restore-from-s3.md
Labels: first-time-contributor, needs-cherry-pick-1.1, status/LGT2

#876 en, zh: fix indentation in Backup yaml
  en/backup-to-gcs-using-br.md
  zh/backup-to-gcs-using-br.md
Labels: needs-cherry-pick-1.1, require-LGT1, status/LGT1, status/can-merge, translation/done

#850 zh: add example to access dashboard via NodePort Service
  zh/access-dashboard.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/doing

#878 en, zh: add expected output after upgrading tidb operator
  en/upgrade-tidb-operator.md
  zh/upgrade-tidb-operator.md
Labels: first-time-contributor, needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#892 chore: add script to upload file to s3
  .circleci/config.yml
  scripts/upload.py
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/LGT1, translation/no-need

#877 zh: Translate release notes v1.1.2, v1.1.3, v1.1.4
  zh/releases/release-1.1.0-beta.1.md
  zh/releases/release-1.1.0-rc.1.md
  zh/releases/release-1.1.2.md
  zh/releases/release-1.1.3.md
  zh/releases/release-1.1.4.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/from-en

#898 en, zh: update tkctl debug usage
  en/use-tkctl.md
  zh/use-tkctl.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/done

#900 readme: change google translate links to appropriate version
  README.md
Labels: needs-cherry-pick-1.0, status/LGT1, status/PTAL, translation/no-need

#904 en, zh: fix tiflash deployment example
  en/configure-a-tidb-cluster.md
  en/deploy-tiflash.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-tiflash.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/done

#902 en, zh: update aws deploy doc
  en/deploy-on-aws-eks.md
  zh/deploy-on-aws-eks.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/done

#909 zh: fix tidb storageVolumes doc
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#914 fix storageVolumes demo config error
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/doing

#917 en, zh: v1.1 abandon "tkctl" tool
  en/maintain-a-kubernetes-node.md
  en/tips.md
  en/use-tkctl.md
  zh/maintain-a-kubernetes-node.md
  zh/tips.md
  zh/use-tkctl.md
Labels: first-time-contributor, needs-cherry-pick-master, status/LGT2, translation/done

#919 Update cdc cli capture list output
  en/deploy-ticdc.md
  zh/deploy-ticdc.md
Labels: first-time-contributor, needs-cherry-pick-master, status/LGT2, translation/done

#901 en: Add an example to access dashboard via NodePort Service
  en/access-dashboard.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/from-zh

#907 Media: Improve two images involving third-party logos
  media/tidb-operator-control-flow-1.1.png
  media/tidb-operator-overview-1.1.png
Labels: needs-cherry-pick-1.1, status/LGT1, translation/doing

#922 zh: add docs about TiDB-Lightning with TLS
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
  zh/restore-data-using-tidb-lightning.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#925 Add 7 aliases to fix broken links
  en/get-started.md
  zh/configure-storage-class.md
  zh/deploy-on-aws-eks.md
  zh/get-started.md
  zh/logs-collection.md
  zh/scale-a-tidb-cluster.md
  zh/tidb-operator-overview.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#932 remove procedure about monitoring multiple clusters
  en/monitor-using-tidbmonitor.md
  zh/monitor-using-tidbmonitor.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/done

#931 en: fix tidb and pd storageVolumes config
  en/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT1, status/PTAL, translation/from-zh

#927 add disable auto failover
  en/TOC.md
  en/use-auto-failover.md
  zh/use-auto-failover.md
Labels: needs-cherry-pick-1.1, require-LGT1, status/LGT1, status/can-merge, translation/done

#928 en, zh: bump tidb version to v4.0.9
  en/access-dashboard.md
  en/access-tidb.md
  en/advanced-statefulset.md
  en/configure-a-tidb-cluster.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-enterprise-edition.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/monitor-using-tidbmonitor.md
  en/notes-tidb-operator-v1.1.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/access-tidb.md
  zh/advanced-statefulset.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-enterprise-edition.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
  zh/monitor-using-tidbmonitor.md
  zh/notes-tidb-operator-v1.1.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-data-using-tidb-lightning.md
  zh/upgrade-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/DNM, status/LGT2, status/can-merge, translation/done

#930 en, zh: add release notes for v1.1.8
  en/TOC.md
  en/releases/release-1.1.8.md
  zh/TOC.md
  zh/releases/release-1.1.8.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#939 en, zh: bump TiDB Operator charts version to v1.1.8
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#947 fix typos and refine language
  en/destroy-a-tidb-cluster.md
  en/enable-tidb-cluster-auto-scaling.md
  en/scale-a-tidb-cluster.md
  zh/monitor-using-tidbmonitor.md
Labels: needs-cherry-pick-1.1, require-LGT1, status/LGT1, translation/no-need

#954 en, zh: add release notes for 1.1.9
  en/TOC.md
  en/releases/release-1.1.9.md
  zh/TOC.md
  zh/releases/release-1.1.9.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#906 en,zh: add pause deployment docs of tidb cluster
  en/TOC.md
  en/pause-sync-of-tidb-cluster.md
  zh/TOC.md
  zh/pause-sync-of-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#942 zh: add hosts for TiKV-Importer TLS
  zh/enable-tls-between-components.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#943 Update upgrade-tidb-operator.md
  zh/upgrade-tidb-operator.md
Labels: first-time-contributor, needs-cherry-pick-master, status/LGT2, status/can-merge, translation/doing

#956 zh: add the doc about Ad hoc mode for TiDB-Lightning
  zh/restore-data-using-tidb-lightning.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#963 zh: add contents about TiDB Lightning backend
  zh/restore-data-using-tidb-lightning.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/doing

#964 fix var name
  en/scale-a-tidb-cluster.md
  zh/scale-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#967 en: add a command to update helm repo
  en/upgrade-tidb-operator.md
Labels: needs-cherry-pick-1.1, require-LGT1, status/LGT1, translation/from-zh

#968 en: add tidb lightning backend info
  en/restore-data-using-tidb-lightning.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/from-zh

#973 add option "--wait=false" when delete PVC
  zh/maintain-a-kubernetes-node.md
Labels: first-time-contributor, needs-cherry-pick-master, status/LGT2, translation/doing

#972 zh: add a note about update PD config
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#976 en, zh: bump TiDB Operator charts version to v1.1.9
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#941 Update scale-a-tidb-cluster.md
  zh/scale-a-tidb-cluster.md
Labels: first-time-contributor, needs-cherry-pick-master, status/LGT2, status/can-merge, translation/doing

#983 zh: link deployment docs
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-operator.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#946 zh; Add section 'Remove TiFlash' in deploy-tiflash.md
  zh/deploy-tiflash.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing
