Repository pingcap/docs-tidb-operator, pull requests merged in 2020-03, with the labels that each got.

#3 .github: add pr and issue templates
  .github/ISSUE_TEMPLATE/change-request.md
  .github/ISSUE_TEMPLATE/error-report.md
  .github/ISSUE_TEMPLATE/question.md
  .github/pull_request_template.md
Labels: translation/no-need

#13 zh: update docs for get-started deployments
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-from-kubernetes-kind.md
  zh/deploy-tidb-from-kubernetes-minikube.md
Labels: priority/P1, size/medium, translation/welcome

#7 zh: update for tidb-operator upgrade
  zh/upgrade-tidb-operator.md
Labels: needs-cherry-pick-1.0, priority/P1, size/small, status/LGT1, translation/welcome

#10 zh: update docs for tidb deploy
  zh/deploy-on-general-kubernetes.md
  zh/initialize-cluster.md
Labels: priority/P1, size/medium, translation/welcome

#5 zh: add backup and restore aws br doc
  zh/backup-to-aws-s3.md
  zh/restore-from-aws-s3.md
Labels: priority/P1, size/large, translation/doing

#12 zh: add tidbcluster configuration document
  zh/TOC.md
  zh/configure-cluster-using-tidbcluster.md
Labels: priority/P2, size/medium, status/LGT1, translation/welcome

#20 zh: add one-sentence summary for Chinese documents
  zh/access-tidb.md
  zh/backup-and-restore-using-helm-charts.md
  zh/backup-to-aws-s3.md
  zh/backup-to-gcs.md
  zh/backup-to-s3.md
  zh/collect-tidb-binlogs.md
  zh/configure-a-tidb-cluster.md
  zh/configure-backup.md
  zh/configure-storage-class.md
  zh/configure-tidb-binlog-drainer.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-from-kubernetes-kind.md
  zh/deploy-tidb-from-kubernetes-minikube.md
  zh/deploy-tidb-operator.md
  zh/destroy-a-tidb-cluster.md
  zh/faq.md
  zh/initialize-a-cluster.md
  zh/maintain-a-kubernetes-node.md
  zh/monitor-a-tidb-cluster.md
  zh/prerequisites.md
  zh/restore-from-aws-s3.md
  zh/restore-from-gcs.md
  zh/restore-from-s3.md
  zh/scale-a-tidb-cluster.md
  zh/tidb-operator-overview.md
  zh/tidb-toolkit.md
  zh/troubleshoot.md
  zh/upgrade-a-tidb-cluster.md
  zh/upgrade-tidb-operator.md
  zh/use-auto-failover.md
  zh/use-tkctl.md
Labels: translation/welcome

#6 zh: add doc for monitoring by tidbmonitor
  zh/TOC.md
  zh/monitoring-using-tidb-monitor.md
Labels: priority/P2, translation/welcome

#29 zh: update doc for tidbmonitor
  zh/TOC.md
  zh/monitor-using-tidbmonitor.md
Labels: size/small, translation/no-need

#27 zh: fix typo in tidbcluster config
  zh/configure-cluster-using-tidbcluster.md
Labels: size/small, translation/no-need

#22 zh: update docs for tidb cluster upgrade with CR
  zh/deploy-on-general-kubernetes.md
  zh/upgrade-a-tidb-cluster.md
Labels: priority/P2, size/medium, translation/welcome

#19 zh: add notes about v1.1
  zh/TOC.md
  zh/backup-to-aws-s3-using-br.md
  zh/notes-tidb-operator-v1.1.md
  zh/restore-from-aws-s3-using-br.md
Labels: priority/P2, translation/welcome

#25 zh: update doc for deploy tidb cluster on aws eks
  zh/deploy-on-aws-eks.md
Labels: priority/P2, status/LGT1, translation/welcome

#30 zh: update doc for deploy tidb cluster on ack with cr
  zh/deploy-on-alibaba-cloud.md
Labels: priority/P2, translation/welcome

#26 zh: TLS for MySQL Client
  zh/TOC.md
  zh/enable-tls-for-mysql-client.md
Labels: priority/P2, translation/welcome

#36 zh: update for alert and monitoring
  zh/monitor-a-tidb-cluster.md
Labels: priority/P2, translation/welcome

#41 zh: update doc to enable tls for binlog
  zh/deploy-tidb-binlog.md
Labels: size/small

#40 zh: add IAM ENV for import and export in backup
  zh/backup-to-s3.md
  zh/restore-from-s3.md
Labels: priority/P2, translation/welcome

#39 zh: TLS between TiDB components
  zh/TOC.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
Labels: priority/P2, translation/welcome

#33 zh: update scaling document
  zh/scale-a-tidb-cluster.md
Labels: translation/welcome

#46 zh: update doc for importer deploy
  zh/restore-data-using-tidb-lightning.md
Labels: priority/P2, translation/welcome

#47 zh: add lightning deploy with S3 IAM
  zh/backup-to-aws-s3-using-br.md
  zh/restore-data-using-tidb-lightning.md
  zh/restore-from-aws-s3-using-br.md
Labels: priority/P2, translation/welcome

#42 zh: Update GKE terraform deployment docs
  zh/deploy-on-gcp-gke.md
Labels: priority/P2, translation/welcome

#32 zh: enable TidbCluster Auto-scaling
  zh/TOC.md
  zh/enable-tidb-cluster-auto-scaling.md
Labels: priority/P2, translation/welcome

#43 zh: update restart tidbcluster document
  zh/restart-a-tidb-cluster.md
Labels: priority/P2

#15 en: update docs in get started
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-from-kubernetes-kind.md
  en/deploy-tidb-from-kubernetes-minikube.md
Labels: priority/P1, status/LGT1, translation/from-zh

#16 en: update doc for tidb-operator upgrade
  en/upgrade-tidb-operator.md
Labels: needs-cherry-pick-1.0, priority/P1, translation/from-zh

#21 zh: add numbers in steps
  zh/initialize-a-cluster.md
Labels: translation/no-need

#17 en: update docs for tidb deployment
  en/deploy-on-general-kubernetes.md
  en/initialize-a-cluster.md
Labels: priority/P1, translation/from-zh

#1 en: add crd-based backup and restore docs
  en/TOC.md
  en/backup-and-restore-using-helm-charts.md
  en/backup-to-gcs.md
  en/backup-to-s3.md
  en/configure-storage-class.md
  en/restore-from-gcs.md
  en/restore-from-s3.md
  en/tidb-operator-overview.md
  zh/backup-and-restore-using-helm-charts.md
Labels: size/large, translation/from-zh

#18 zh: update file name of initialize-a-cluster
  zh/deploy-on-general-kubernetes.md
Labels: translation/no-need

#50 zh: add admission webhook document
  zh/TOC.md
  zh/enable-admission-webhook.md
  zh/enable-tidb-cluster-auto-scaling.md
  zh/restart-a-tidb-cluster.md
Labels: translation/welcome

#31 en: add doc for tidbmonitor
  en/TOC.md
  en/monitor-using-tidbmonitor.md
Labels: priority/P2, translation/from-zh

#28 en: add doc for tidbcluster config
  en/TOC.md
  en/configure-cluster-using-tidbcluster.md
Labels: priority/P2, status/LGT1, translation/from-zh

#44 en: add doc for enabling TLS for MySQL client
  en/TOC.md
  en/enable-tls-for-mysql-client.md
Labels: priority/P2, translation/from-zh

#49 en: update doc for deploying TiDB cluster on AWS EKS
  en/deploy-on-aws-eks.md
Labels: priority/P2, translation/from-zh

#37 en: update doc for upgrade TiDB cluster with CR
  en/_index.md
  en/deploy-on-general-kubernetes.md
  en/upgrade-a-tidb-cluster.md
  zh/backup-and-restore-using-helm-charts.md
Labels: priority/P2, translation/from-zh

#55 zh: lock helm version
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-kind.md
  zh/deploy-tidb-operator.md
  zh/tidb-toolkit.md
Labels: translation/welcome

#61 zh: update v1.1 notes for monitor
  zh/notes-tidb-operator-v1.1.md
Labels: size/small, translation/welcome

#60 en: update doc for importer deploy
  en/restore-data-using-tidb-lightning.md
Labels: priority/P2, translation/from-zh

#67 zh, en: update auto-failover default setting
  en/use-auto-failover.md
  zh/use-auto-failover.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, translation/no-need

#69 zh, en: add doc for tidb scheduler
  en/TOC.md
  en/tidb-scheduler.md
  media/tidb-scheduler-overview.png
  zh/TOC.md
  zh/tidb-scheduler.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, translation/no-need

#82 .github: add v1.1 version in PR template
  .github/pull_request_template.md
Labels: needs-cherry-pick-1.1, translation/no-need

#87 *: copy files from master to 1.0-branch
  .editorconfig
  .github/ISSUE_TEMPLATE/change-request.md
  .github/ISSUE_TEMPLATE/error-report.md
  .github/ISSUE_TEMPLATE/question.md
  .github/workflows/ci.yaml
  .github/workflows/media.yml
  en/_index.md
  en/backup-and-restore-using-helm-charts.md
  en/configure-storage-class.md
  en/tidb-operator-overview.md
  hack/markdown-link-check.tpl
  hack/verify-links.sh
  zh/_index.md
  zh/backup-and-restore-using-helm-charts.md
  zh/tidb-operator-overview.md
Labels: translation/no-need

#88 en, zh: add tidb-operator relation with tidb
  en/_index.md
  en/tidb-operator-overview.md
  zh/_index.md
  zh/tidb-operator-overview.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, translation/no-need

#92 en, zh: update all absolute paths from `stable` to `v3.0`
  README.md
  en/backup-and-restore-using-helm-charts.md
  en/backup-to-gcs.md
  en/backup-to-s3.md
  en/configure-a-tidb-cluster.md
  en/configure-backup.md
  en/enable-tls-for-mysql-client.md
  en/faq.md
  en/maintain-tidb-binlog.md
  en/monitor-a-tidb-cluster.md
  en/prerequisites.md
  en/restore-data-using-tidb-lightning.md
  en/restore-from-gcs.md
  en/restore-from-s3.md
  en/tidb-toolkit.md
  en/troubleshoot.md
  en/use-auto-failover.md
  zh/backup-and-restore-using-helm-charts.md
  zh/backup-to-gcs.md
  zh/backup-to-s3.md
  zh/configure-a-tidb-cluster.md
  zh/configure-backup.md
  zh/deploy-tidb-binlog.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
  zh/faq.md
  zh/monitor-a-tidb-cluster.md
  zh/prerequisites.md
  zh/restore-data-using-tidb-lightning.md
  zh/restore-from-gcs.md
  zh/restore-from-s3.md
  zh/tidb-cluster-chart-config.md
  zh/tidb-toolkit.md
  zh/troubleshoot.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, translation/no-need

#63 en: enable TidbCluster Auto-scaling
  en/TOC.md
  en/enable-tidb-cluster-auto-scaling.md
Labels: needs-cherry-pick-1.1, priority/P2, translation/from-zh

#58 en: update restart tidbcluster document
  en/restart-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, priority/P2, translation/from-zh

#99 zh: fix typo in backup and restore using br
  zh/backup-to-aws-s3-using-br.md
  zh/restore-from-aws-s3-using-br.md
Labels: needs-cherry-pick-1.1, translation/no-need

#45 en: add docs for backup and restore aws using BR
  en/backup-to-aws-s3-using-br.md
  en/restore-from-aws-s3-using-br.md
Labels: needs-cherry-pick-1.1, priority/P1, translation/from-zh

#91 zh: update get-started docs
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-from-kubernetes-kind.md
  zh/deploy-tidb-from-kubernetes-minikube.md
Labels: needs-cherry-pick-1.1

#94 update docs for br tls
  zh/backup-to-aws-s3-using-br.md
  zh/enable-tls-between-components.md
  zh/restore-from-aws-s3-using-br.md
Labels: needs-cherry-pick-1.1, translation/welcome

#62 en: update doc for deploying TiDB cluster on ACK
  en/deploy-on-alibaba-cloud.md
Labels: needs-cherry-pick-1.1, translation/from-zh, v1.1

#56 en: update tidb operator overview
  en/tidb-operator-overview.md
  en/upgrade-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, translation/from-zh

#52 zh: add Advanced StatefulSet
  zh/TOC.md
  zh/advanced-statefulset.md
Labels: needs-cherry-pick-1.1, size/medium, translation/doing

#104 en: lock helm version
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-kind.md
  en/deploy-tidb-operator.md
  en/tidb-toolkit.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/can-merge, translation/from-zh

#78 en: update doc for gke deployment
  en/deploy-on-gcp-gke.md
Labels: needs-cherry-pick-1.1, priority/P2, translation/from-zh

#113 en: add admission webhook document
  en/TOC.md
  en/enable-admission-webhook.md
  en/enable-tidb-cluster-auto-scaling.md
  en/restart-a-tidb-cluster.md
  zh/enable-admission-webhook.md
Labels: needs-cherry-pick-1.1, translation/from-zh

#83 en: update doc for alert and monitor
  en/monitor-a-tidb-cluster.md
  en/monitor-using-tidbmonitor.md
Labels: needs-cherry-pick-1.1, priority/P2, status/can-merge, translation/from-zh

#111 en: update doc for tidb cluster scaling
  en/scale-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, translation/from-zh

#64 en: add doc for enable TLS between TiDB components
  en/TOC.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
Labels: needs-cherry-pick-1.1, status/DNM, translation/from-zh, v1.1

#53 en: update doc for deploy binlog
  en/TOC.md
  en/backup-and-restore-using-helm-charts.md
  en/collect-tidb-logs.md
  en/configure-tidb-binlog-drainer.md
  en/deploy-tidb-binlog.md
  zh/TOC.md
  zh/_index.md
  zh/collect-tidb-logs.md
  zh/tidb-operator-overview.md
Labels: needs-cherry-pick-1.1, priority/P2, status/can-merge, translation/from-zh

#86 en: update lightning deployment using S3 IAM
  en/backup-to-aws-s3-using-br.md
  en/restore-data-using-tidb-lightning.md
Labels: needs-cherry-pick-1.1, priority/P2, translation/from-zh

#112 en: update docs for br and tls
  en/backup-to-aws-s3-using-br.md
  en/enable-tls-between-components.md
  en/restore-from-aws-s3-using-br.md
Labels: needs-cherry-pick-1.1, status/can-merge, translation/from-zh

#34 en: add notes for v1.1
  en/TOC.md
  en/notes-tidb-operator-v1.1.md
Labels: needs-cherry-pick-1.1, priority/P2, status/LGT1, translation/from-zh

#59 en: update toc and reorganize some v1.1 content
  en/TOC.md
  en/access-tidb.md
  en/backup-and-restore-using-helm-charts.md
  en/configure-a-tidb-cluster.md
  en/configure-backup.md
  en/deploy-tidb-operator.md
  en/destroy-a-tidb-cluster.md
  en/monitor-a-tidb-cluster.md
  en/prerequisites.md
  en/tidb-cluster-chart-config.md
Labels: needs-cherry-pick-1.1, size/large, translation/from-zh

#118 zh: reload tidb tls document
  zh/enable-tls-for-mysql-client.md
Labels: needs-cherry-pick-1.1, size/small, translation/doing

#120 zh: fix link and indent issues
  zh/monitor-a-tidb-cluster.md
  zh/prerequisites.md
Labels: needs-cherry-pick-1.1, size/small, status/can-merge, translation/no-need

#54 en: add IAM ENV for backup and restore of s3
  en/backup-to-s3.md
  en/restore-from-s3.md
Labels: needs-cherry-pick-1.1, priority/P2, translation/from-zh

#110 en: add doc for advanced statefulset
  en/TOC.md
  en/advanced-statefulset.md
  zh/advanced-statefulset.md
Labels: status/can-merge, translation/from-zh

#131 zh: revise auto-scaling document
  zh/enable-tidb-cluster-auto-scaling.md
Labels: translation/doing

#134 update PDF title
  scripts/generate_pdf.sh
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1

#139 en: revise auto-scaling doc
  en/enable-tidb-cluster-auto-scaling.md
Labels: needs-cherry-pick-1.1, translation/from-zh

#128 zh, en: add omitted benchmark files
  en/TOC.md
  en/benchmark-sysbench.md
  media/cos-vs-ubuntu-latency.png
  media/cos-vs-ubuntu-qps.png
  media/n1-standard-16-vs-c2-standard-16-latency.png
  media/n1-standard-16-vs-c2-standard-16-qps.png
  media/oltp-read-write-latency.png
  media/oltp-read-write-qps.png
  media/oltp-update-index-latency.png
  media/oltp-update-index-qps.png
  media/oltp-update-no-index-latency.png
  media/oltp-update-no-index-qps.png
  media/pod-vs-host-network-latency.png
  media/pod-vs-host-network-qps.png
  media/service-vs-load-balancer-latency.png
  media/service-vs-load-balancer-qps.png
  media/single-zonal-vs-regional-latency.png
  media/single-zonal-vs-regional-qps.png
  zh/TOC.md
  zh/benchmark-sysbench.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/can-merge, translation/no-need

#115 zh: add `cert-allowed-cn` option
  zh/enable-tls-between-components.md
Labels: needs-cherry-pick-1.1, size/small, translation/doing
