Repository pingcap/docs-tidb-operator, pull requests merged in 2021-01, with the labels that each got.

#970 zh: add contents about troubleshoot for TiDB Lightning
  zh/restore-data-using-tidb-lightning.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#978 zh: refine docs about TidbMonitorand add contents about Prometheus config
  zh/TOC.md
  zh/access-dashboard.md
  zh/enable-tidb-cluster-auto-scaling.md
  zh/get-started.md
  zh/monitor-a-tidb-cluster.md
  zh/monitor-kubernetes.md
  zh/monitor-using-tidbmonitor.md
  zh/notes-tidb-operator-v1.1.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/doing

#994 en, zh: add description for gp3
  en/deploy-on-aws-eks.md
  zh/deploy-on-aws-eks.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#912 en,zh: optimize catalog structure of Restore Data into TiDB in Kubern…
  en/restore-data-using-tidb-lightning.md
  zh/restore-data-using-tidb-lightning.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#988 zh: add contents about modify tidb cluster config
  zh/upgrade-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#996 zh: refine contents about local-storage
  zh/configure-storage-class.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#1002 zh: fix missing notes of monitor
  zh/monitor-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/doing

#929 en, zh: Add content about spec.tidb.service in config-a-tidb-cluster.md
  zh/access-tidb.md
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-master, status/LGT2, status/can-merge, translation/doing

#998 zh: add contents about hostNetwork
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing

#1009 en: add --wait=false when deleting pvc in k8s
  en/maintain-a-kubernetes-node.md
Labels: needs-cherry-pick-1.1, require-LGT1, status/LGT1, status/can-merge, translation/from-zh

#1016 Fix 12 broken links
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/destroy-a-tidb-cluster.md
  en/get-started.md
  en/initialize-a-cluster.md
  en/tidb-operator-overview.md
  zh/upgrade-tidb-operator.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#1010 update doc for tikv-ctl
  en/tidb-toolkit.md
  zh/tidb-toolkit.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/done

#1012 en: update pd config; link deployment docs
  en/configure-a-tidb-cluster.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-operator.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/from-zh

#1008 en: add contents for enabling tidb lightning tls and troubleshooting
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/restore-data-using-tidb-lightning.md
Labels: needs-cherry-pick-1.1, size/large, status/LGT2, translation/from-zh

#1019 zh, en: update the CA expiration date to 10 years
  en/enable-tls-between-components.md
  en/enable-tls-for-dm.md
  en/enable-tls-for-mysql-client.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-dm.md
  zh/enable-tls-for-mysql-client.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#1014 zh: add the doc about migrating to Helm3; update commands for Helm3
  zh/TOC.md
  zh/backup-and-restore-using-helm-charts.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-operator.md
  zh/destroy-a-tidb-cluster.md
  zh/enable-tls-between-components.md
  zh/migrate-to-helm3.md
  zh/recover-deleted-cluster.md
  zh/restore-data-using-tidb-lightning.md
  zh/roadmap.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/doing

#1020 en: refactor monitoring docs
  en/TOC.md
  en/access-dashboard.md
  en/enable-tidb-cluster-auto-scaling.md
  en/get-started.md
  en/monitor-a-tidb-cluster.md
  en/monitor-kubernetes.md
  en/monitor-using-tidbmonitor.md
  en/notes-tidb-operator-v1.1.md
  zh/monitor-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/from-zh, version-specific-changes-required

#1027 en,zh; Fix link description
  en/restart-a-tidb-cluster.md
  zh/restart-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#993 Update scale-a-tidb-cluster.md
  en/scale-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, require-LGT1, status/LGT1, status/can-merge, status/require-change, translation/from-zh

#1026 zh: add the doc about renewing TLS certs
  zh/TOC.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-dm.md
  zh/enable-tls-for-mysql-client.md
  zh/renew-tls-certificate.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/doing

#1032 en: add contents about hostNetwork
  en/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/from-zh

#1033 en: add contents about modify tidb cluster config
  en/upgrade-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/from-zh

#1022 Update deploy-on-gcp-gke.md
  en/deploy-on-gcp-gke.md
Labels: first-time-contributor, needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#1021 Update deploy-on-aws-eks.md
  en/deploy-on-aws-eks.md
Labels: first-time-contributor, status/LGT2, status/can-merge, translation/done

#1038 Update deploy-on-aws-eks.md
  zh/deploy-on-aws-eks.md
Labels: first-time-contributor, status/LGT2, translation/from-en

#1037 Update deploy-on-gcp-gke.md
  zh/deploy-on-gcp-gke.md
Labels: first-time-contributor, needs-cherry-pick-master, status/LGT2, status/can-merge, translation/from-en

#974 zh: Deploy a TiDB Cluster across Multiple Kubernetes clusters
  zh/TOC.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
Labels: first-time-contributor, status/LGT2, translation/doing

#1043 zh: add canary-deployment-tidb-operator doc
  zh/TOC.md
  zh/canary-deployment-tidb-operator.md
Labels: first-time-contributor, status/LGT2, translation/doing

#1050 en, zh: bump TiDB Operator charts version to v1.2.0-alpha.1
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/LGT3, status/can-merge, translation/done

#1049 zh: update auto-scaling doc for master branch
  zh/enable-tidb-cluster-auto-scaling.md
Labels: status/LGT2, status/PTAL, status/can-merge, translation/doing

#1051 en, zh: add release notes for v1.2.0-alpha.1
  en/TOC.md
  en/releases/release-1.2.0-alpha.1.md
  zh/TOC.md
  zh/releases/release-1.2.0-alpha.1.md
Labels: status/LGT2, status/can-merge, translation/done

#1047 en: add the doc about migrating to helm 3
  en/TOC.md
  en/backup-and-restore-using-helm-charts.md
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-operator.md
  en/destroy-a-tidb-cluster.md
  en/enable-tls-between-components.md
  en/migrate-to-helm3.md
  en/recover-deleted-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/roadmap.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/from-zh

#1053 en: refine contents about local-storage
  en/configure-storage-class.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/from-zh

#1055 en: Add content about spec.tidb.service in config-a-tidb-cluster.md
  en/access-tidb.md
  en/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/from-zh

#1060 Add 8 aliases to fix broken links
  en/configure-a-tidb-cluster.md
  en/deploy-on-alibaba-cloud.md
  zh/access-tidb.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/scale-a-tidb-cluster.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#1061 .github: update stale action version
  .github/workflows/stale.yaml
Labels: require-LGT1, status/LGT1, status/can-merge, translation/done

#1058 update doc for adding another disk for tiflash
  en/deploy-tiflash.md
  zh/deploy-tiflash.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#1015 en: Add section 'Remove TiFlash' in deploy-tiflash.md
  en/deploy-tiflash.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/from-zh

#991 Improve backup restore docs
  zh/TOC.md
  zh/_index.md
  zh/backup-restore-overview.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-gcs.md
  zh/backup-to-pv-using-br.md
  zh/backup-to-s3.md
  zh/configure-storage-class.md
  zh/grant-permissions-to-remote-storage.md
  zh/notes-tidb-operator-v1.1.md
  zh/restore-data-using-tidb-lightning.md
  zh/restore-from-aws-s3-using-br.md
  zh/restore-from-gcs-using-br.md
  zh/restore-from-gcs.md
  zh/restore-from-pv-using-br.md
  zh/restore-from-s3.md
  zh/tidb-operator-overview.md
Labels: size/large, status/LGT2, status/PTAL, status/can-merge, translation/doing

#1063 update doc for deploy multiple operator
  zh/TOC.md
  zh/deploy-multiple-tidb-operator.md
Labels: status/LGT2, status/can-merge, translation/doing

#640 zh: aggregate multiple TiDB Monitor data by thanos query
  zh/TOC.md
  zh/aggregate-multiple-cluster-monitor-data.md
Labels: contribution, status/LGT2, translation/doing

#1057 en: add doc for deploying multiple tidb operator
  en/TOC.md
  en/deploy-multiple-tidb-operator.md
Labels: status/LGT2, status/PTAL, translation/from-zh

#1065 en, zh: add tikv conf for using br with pv
  en/backup-to-pv-using-br.md
  zh/backup-to-pv-using-br.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/done

#1070 en: update auto-scaling doc for tidb 5.0
  en/enable-tidb-cluster-auto-scaling.md
Labels: status/LGT2, translation/from-zh

#1072 chore: update dispatch event type
  .github/workflows/dispatch.yml
Labels: status/LGT1

#1076 chore: update CDN refresh cache
  .github/workflows/media.yml
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/LGT1, translation/no-need

#1067 en: Add the doc about renewing TLS certs
  en/TOC.md
  en/enable-tls-between-components.md
  en/enable-tls-for-dm.md
  en/enable-tls-for-mysql-client.md
  en/renew-tls-certificate.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/from-zh

#1073 zh, en: fix uninstall command for Helm 3
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-operator.md
  en/destroy-a-tidb-cluster.md
  en/prerequisites.md
  en/recover-deleted-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/tidb-toolkit.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-operator.md
  zh/destroy-a-tidb-cluster.md
  zh/prerequisites.md
  zh/recover-deleted-cluster.md
  zh/restore-data-using-tidb-lightning.md
  zh/tidb-toolkit.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#1083 zh, en: fix table format
  en/prerequisites.md
  zh/prerequisites.md
Labels: status/LGT1, translation/done

#1085 Add 5 aliases to fix broken links
  zh/backup-to-gcs.md
  zh/configure-storage-class.md
  zh/deploy-on-aws-eks.md
  zh/monitor-a-tidb-cluster.md
  zh/use-tkctl.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#1086 en, zh: add multiple tidb-operator doc to release-1.1
  en/TOC.md
  en/deploy-multiple-tidb-operator.md
  zh/TOC.md
  zh/deploy-multiple-tidb-operator.md
Labels: require-LGT1, status/LGT1, status/can-merge, translation/done, type/1.1-cherry-pick

#1087 en,zh; Bump tidb components to v4.0.10
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/configure-a-tidb-cluster.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-enterprise-edition.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/monitor-a-tidb-cluster.md
  en/notes-tidb-operator-v1.1.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-enterprise-edition.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
  zh/monitor-a-tidb-cluster.md
  zh/notes-tidb-operator-v1.1.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-data-using-tidb-lightning.md
  zh/upgrade-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, status/LGT2, translation/done

#1090 add release notes for v1.1.10
  en/TOC.md
  en/releases/release-1.1.10.md
  zh/TOC.md
  zh/releases/release-1.1.10.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/done

#1088 en,zh; Bump Operator to v1.1.10
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/LGT2, status/can-merge, translation/done

#1071 en: Refactor backup restore
  en/TOC.md
  en/_index.md
  en/backup-restore-overview.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-gcs.md
  en/backup-to-pv-using-br.md
  en/backup-to-s3.md
  en/configure-storage-class.md
  en/grant-permissions-to-remote-storage.md
  en/restore-data-using-tidb-lightning.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs-using-br.md
  en/restore-from-gcs.md
  en/restore-from-pv-using-br.md
  en/restore-from-s3.md
  en/tidb-operator-overview.md
  zh/TOC.md
  zh/backup-restore-overview.md
  zh/backup-to-gcs-using-br.md
  zh/configure-storage-class.md
  zh/grant-permissions-to-remote-storage.md
  zh/restore-data-using-tidb-lightning.md
  zh/restore-from-gcs-using-br.md
Labels: needs-cherry-pick-1.1, size/large, status/LGT2, status/can-merge, translation/from-zh

#1094 zh: fix create a namespace for Helm 3
  zh/deploy-tidb-operator.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/doing
