Repository pingcap/docs-tidb-operator, pull requests merged in 2021-02, with the labels that each got.

#1097 en: fix create a namespace for Helm 3
  en/deploy-tidb-operator.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/from-zh

#1100 Add 4 aliases to filter broken links
  en/benchmark-sysbench.md
  zh/backup-to-gcs.md
  zh/backup-to-s3.md
  zh/restore-data-using-tidb-lightning.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#1099 en: support slowlog PV config
  en/configure-a-tidb-cluster.md
  en/logs-collection.md
  zh/logs-collection.md
Labels: needs-cherry-pick-1.1, status/LGT1, status/PTAL, translation/from-zh

#1103 zh: fix format
  zh/backup-to-gcs.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/no-need

#1107 Update destroy-a-tidb-cluster.md
  zh/destroy-a-tidb-cluster.md
Labels: first-time-contributor, needs-cherry-pick-1.1, status/LGT2, translation/doing

#1102 en, zh: recommend not to use local storage in production
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#1109 en, zh: add release notes for v1.1.11
  en/TOC.md
  en/releases/release-1.1.11.md
  zh/TOC.md
  zh/releases/release-1.1.11.md
Labels: needs-cherry-pick-1.1, status/LGT2, status/can-merge, translation/done

#1108 en, zh: Bump Operator to v1.1.11
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/DNM, status/LGT2, status/can-merge, translation/done
