Repository pingcap/docs-tidb-operator, pull requests merged in 2021-05, with the labels that each got.

#1207 en, zh: Add evict tikv leader timeout part
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-release-1.1, size/S, status/LGT2, status/can-merge, status/require-change, translation/done

#1206 zh: add faq about data reliability
  zh/faq.md
Labels: needs-cherry-pick-release-1.1, size/XS, status/LGT2, status/PTAL, status/can-merge, translation/doing

#1210 en: backup-to-s3, deploy-on-aws-eks: various small changes
  en/backup-to-s3.md
  en/deploy-on-aws-eks.md
Labels: needs-cherry-pick-release-1.1, size/M, status/LGT2, status/can-merge, translation/doing

#1200 en, zh: add upgrade TiDB Operator offline
  en/upgrade-tidb-operator.md
  zh/upgrade-tidb-operator.md
Labels: first-time-contributor, needs-cherry-pick-release-1.1, size/L, status/LGT2, status/can-merge, status/require-change, translation/done

#1216 en: add faq about data reliability #1206
  en/faq.md
Labels: needs-cherry-pick-release-1.1, size/XS, status/LGT2, status/can-merge, translation/from-zh

#1212 en: Update info on EKS and dashboard access
  en/access-dashboard.md
  en/deploy-on-aws-eks.md
Labels: needs-cherry-pick-release-1.1, size/S, status/LGT2, status/can-merge, translation/doing

#1234 en: update notes
  en/upgrade-a-tidb-cluster.md
  en/upgrade-tidb-operator.md
Labels: needs-cherry-pick-release-1.1, size/XS, status/LGT2, status/can-merge, translation/no-need

#1231 Remove the helm section - Eng+CN
  en/upgrade-a-tidb-cluster.md
  zh/upgrade-a-tidb-cluster.md
Labels: contribution, needs-cherry-pick-master, size/L, status/LGT1, status/can-merge, translation/done

#1217 zh: improve the doc of tidb-lightning
  zh/cheat-sheet.md
  zh/deploy-tidb-binlog.md
  zh/destroy-a-tidb-cluster.md
  zh/restore-data-using-tidb-lightning.md
  zh/restore-from-gcs.md
  zh/restore-from-s3.md
  zh/tidb-toolkit.md
Labels: needs-cherry-pick-release-1.1, size/M, status/LGT2, status/can-merge, translation/doing

#1218 zh: update docs about data mount path for DM-worker
  zh/deploy-tidb-dm.md
  zh/enable-tls-for-dm.md
Labels: size/S, status/LGT2, status/can-merge, translation/doing, v1.2

#1223 zh: backup-to-s3, deploy-on-aws-eks: various small changes
  zh/backup-to-s3.md
  zh/deploy-on-aws-eks.md
Labels: needs-cherry-pick-release-1.1, size/M, status/LGT2, status/can-merge, translation/from-en

#1233 en, zh: add release notes for v1.2.0-rc.1
  en/TOC.md
  en/releases/release-1.2.0-rc.1.md
  zh/TOC.md
  zh/releases/release-1.2.0-rc.1.md
Labels: missing-translation-status, size/M, status/LGT2, status/can-merge

#1232 zh: update info on EKS and dashboard access
  zh/access-dashboard.md
  zh/deploy-on-aws-eks.md
Labels: needs-cherry-pick-release-1.1, size/S, status/LGT2, status/can-merge, translation/from-en
