Repository pingcap/docs-tidb-operator, pull requests merged in 2021-09, with the labels that each got.

#1371 en,zh; Bump tidb components to v5.2.0
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/backup-restore-overview.md
  en/configure-a-tidb-cluster.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-enterprise-edition.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/monitor-a-tidb-cluster.md
  en/notes-tidb-operator-v1.1.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/backup-restore-overview.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-enterprise-edition.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
  zh/monitor-a-tidb-cluster.md
  zh/notes-tidb-operator-v1.1.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-data-using-tidb-lightning.md
  zh/upgrade-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, missing-translation-status, size/L, needs-cherry-pick-release-1.2

#1372 en,zh: add release notes for v1.2.2
  en/TOC.md
  en/releases/release-1.2.2.md
  zh/TOC.md
  zh/releases/release-1.2.2.md
Labels: status/can-merge, status/LGT2, missing-translation-status, size/M, needs-cherry-pick-release-1.2

#1375 en,zh: add release notes for v1.2.3
  en/TOC.md
  en/releases/release-1.2.3.md
  zh/TOC.md
  zh/releases/release-1.2.3.md
Labels: status/can-merge, status/LGT2, missing-translation-status, size/S, needs-cherry-pick-release-1.2

#1377 fix link of v1.2.3 release note
  zh/TOC.md
Labels: status/can-merge, status/LGT2, missing-translation-status, size/XS, needs-cherry-pick-release-1.2

#1379 en,zh; Bump Operator to v1.2.3
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, missing-translation-status, size/L, needs-cherry-pick-release-1.2

#1383 chore: remove markdown lint from circleci
  .circleci/config.yml
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/no-need, require-LGT1, missing-translation-status, size/S, needs-cherry-pick-release-1.2

#1382 en, zh: update support releases
  en/_index.md
  en/tidb-operator-overview.md
  zh/_index.md
  zh/tidb-operator-overview.md
Labels: status/can-merge, status/LGT2, missing-translation-status, size/S, needs-cherry-pick-release-1.2

#1381 .github: fix github action config
  .github/workflows/ci.yaml
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/no-need, require-LGT1, size/XS, needs-cherry-pick-release-1.2

#1369 en,zh: Fix broken link and modify description about TiDBMonitor
  en/monitor-a-tidb-cluster.md
  zh/monitor-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/done, size/S, needs-cherry-pick-release-1.2

#1398 chore: remove circleci config
  .circleci/config.yml
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/no-need, size/M, needs-cherry-pick-release-1.2
