Repository pingcap/docs-tidb-operator, pull requests merged in 2021-11, with the labels that each got.

#1428 en, zh: tidb-toolkit: Fix tikv-ctl local mode
  en/tidb-toolkit.md
  zh/tidb-toolkit.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/done, size/XS, needs-cherry-pick-release-1.2

#1433 Fix typo in the index
  en/_index.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/no-need, size/XS, needs-cherry-pick-release-1.2

#1435 fix typo in /en/enable-tls-for-mysql-client.md
  en/enable-tls-for-mysql-client.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/no-need, size/XS, needs-cherry-pick-release-1.2

#1441 chore: list as the first child in TOC
  en/TOC.md
  zh/TOC.md
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/L, needs-cherry-pick-release-1.2

#1440 en,zh: add doc about upgrade tidb across multi kubernetes
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, needs-cherry-pick-release-1.2

#1301 zh: add doc about deploy cluster on ARM64
  zh/TOC.md
  zh/deploy-cluster-on-arm64.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/get-started.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/doing, size/L

#1424 en, zh: split the instructions of DM deployment and usage
  en/TOC.md
  en/deploy-tidb-dm.md
  en/enable-tls-for-dm.md
  en/use-tidb-dm.md
  zh/TOC.md
  zh/deploy-tidb-dm.md
  zh/enable-tls-for-dm.md
  zh/use-tidb-dm.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.2

#1370 en,zh: add FAQ about Ready field of TiDBCluster
  en/faq.md
  zh/faq.md
Labels: status/can-merge, status/LGT2, translation/done, size/S, needs-cherry-pick-release-1.2

#1453 update TOC.md parse method since TOC.md structure has been changed
  scripts/merge_by_toc.py
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/no-need, size/S, needs-cherry-pick-release-1.2

#1458 en,zh; Use version-specific url
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
Labels: status/can-merge, status/LGT1, translation/done, size/S

#1414 zh:add tidbmonitor dynamic configuration
  zh/TOC.md
  zh/enable-monitor-dynamic-configuration.md
Labels: status/can-merge, status/LGT2, translation/doing, size/M, v1.3

#1427 zh: Add AWS instance type recommendation
  en/deploy-on-aws-eks.md
  zh/deploy-on-aws-eks.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/doing, size/L, needs-cherry-pick-release-1.2
