Repository pingcap/docs-tidb-operator, pull requests merged in 2021-08, with the labels that each got.

#1346 chore: lock lint plugin versions
  hack/verify-link-anchors.sh
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, needs-cherry-pick-release-1.2, size/XS, status/LGT2, status/can-merge, translation/no-need

#1345 en, zh: update docs for canary upgrade
  en/canary-upgrade-tidb-operator.md
  en/deploy-multiple-tidb-operator.md
  zh/canary-upgrade-tidb-operator.md
  zh/deploy-multiple-tidb-operator.md
Labels: needs-cherry-pick-release-1.1, needs-cherry-pick-release-1.2, size/M, status/LGT2, status/can-merge, translation/done

#1356 en,zh; Bump DM to v2.0.6
  en/deploy-tidb-dm.md
  en/enable-tls-for-dm.md
  zh/deploy-tidb-dm.md
  zh/enable-tls-for-dm.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, needs-cherry-pick-release-1.2

#1355 en,zh; Bump tidb components to v5.1.1
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/backup-restore-overview.md
  en/configure-a-tidb-cluster.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-aws-eks.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-enterprise-edition.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/monitor-a-tidb-cluster.md
  en/notes-tidb-operator-v1.1.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/backup-restore-overview.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-enterprise-edition.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
  zh/monitor-a-tidb-cluster.md
  zh/notes-tidb-operator-v1.1.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-data-using-tidb-lightning.md
  zh/upgrade-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/done, size/XL, needs-cherry-pick-release-1.2

#1359 en, zh: add release notes for v1.2.1
  en/TOC.md
  en/releases/release-1.2.1.md
  zh/TOC.md
  zh/releases/release-1.2.1.md
Labels: status/can-merge, status/LGT2, translation/done, size/M

#1353 en: update the failover doc
  en/configure-a-tidb-cluster.md
  en/use-auto-failover.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/from-zh, size/L, needs-cherry-pick-release-1.2

#1363 en, zh: Bump Operator to v1.2.1
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.2
