Repository pingcap/docs-tidb-operator, pull requests merged in 2021-07, with the labels that each got.

#1275 en, zh: Update the doc of setting kube-prometheus and AlertManager
  en/monitor-a-tidb-cluster.md
  zh/monitor-a-tidb-cluster.md
Labels: needs-cherry-pick-release-1.1, size/XS, status/LGT2, status/can-merge, translation/done

#1266 zh: add the section "Custom Operator"
  en/deploy-tidb-operator.md
  zh/deploy-tidb-operator.md
Labels: first-time-contributor, needs-cherry-pick-release-1.1, size/S, status/LGT2, status/can-merge, translation/no-need

#1264 zh,en: Use drop-in directory to configure docker service
  en/prerequisites.md
  zh/prerequisites.md
Labels: first-time-contributor, needs-cherry-pick-release-1.1, size/M, status/LGT2, status/can-merge, translation/done

#1281 en,zh: Add warning about `spec.tikv.evictLeaderTimeout` field
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-release-1.1, size/XS, status/LGT2, status/can-merge, translation/done

#1290 en,zh; Bump tidb components to v4.0.13
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/configure-a-tidb-cluster.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-enterprise-edition.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/monitor-a-tidb-cluster.md
  en/notes-tidb-operator-v1.1.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-enterprise-edition.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
  zh/monitor-a-tidb-cluster.md
  zh/notes-tidb-operator-v1.1.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-data-using-tidb-lightning.md
  zh/upgrade-a-tidb-cluster.md
Labels: missing-translation-status, size/L, status/LGT1, status/can-merge

#1271 en, zh: update doc about deploying initializer
  en/initialize-a-cluster.md
  zh/initialize-a-cluster.md
Labels: first-time-contributor, needs-cherry-pick-release-1.1, size/M, status/LGT2, status/can-merge, translation/done

#1298 en, zh: Bump Operator to v1.1.13
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: size/XL, status/LGT1, status/can-merge, translation/done

#1297 en, zh: Bump Operator to v1.2.0-rc.2
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: size/L, status/LGT2, status/can-merge, translation/done

#1294 en,zh; Bump DM to v2.0.4
  en/deploy-tidb-dm.md
  en/enable-tls-for-dm.md
  zh/deploy-tidb-dm.md
  zh/enable-tls-for-dm.md
Labels: size/M, status/LGT2, status/can-merge, translation/done

#1293 en,zh; Bump tidb components to v5.1.0
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/backup-restore-overview.md
  en/configure-a-tidb-cluster.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-enterprise-edition.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/monitor-a-tidb-cluster.md
  en/notes-tidb-operator-v1.1.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/backup-restore-overview.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-enterprise-edition.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
  zh/monitor-a-tidb-cluster.md
  zh/notes-tidb-operator-v1.1.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-data-using-tidb-lightning.md
  zh/upgrade-a-tidb-cluster.md
Labels: size/XL, status/LGT2, status/can-merge, translation/done

#1287 en, zh: Update description about `toolImage` field of BR
  en/backup-restore-overview.md
  zh/backup-restore-overview.md
Labels: needs-cherry-pick-release-1.1, size/S, status/LGT2, status/can-merge, translation/done

#1295 en, zh: add release notes for v1.1.13
  en/TOC.md
  en/releases/release-1.1.13.md
  zh/TOC.md
  zh/releases/release-1.1.13.md
Labels: needs-cherry-pick-release-1.1, size/M, status/LGT2, status/can-merge, translation/done

#1296 en, zh: add release notes for v1.2.0-rc.2
  en/TOC.md
  en/releases/release-1.2.0-rc.2.md
  zh/TOC.md
  zh/releases/release-1.2.0-rc.2.md
Labels: size/M, status/LGT2, status/can-merge, translation/done

#1272 en, zh: prompt user not to modify names of Secret objects.
  en/enable-tls-between-components.md
  en/enable-tls-for-dm.md
  en/enable-tls-for-mysql-client.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-dm.md
  zh/enable-tls-for-mysql-client.md
Labels: first-time-contributor, needs-cherry-pick-release-1.1, size/M, status/LGT2, status/can-merge, translation/done

#1205 zh; Add doc about RBAC roles that TiDB Operator requires
  zh/TOC.md
  zh/tidb-operator-rbac.md
Labels: needs-cherry-pick-release-1.1, size/L, status/LGT2, status/can-merge, translation/doing, v1.2

#1215 zh: update Thanos
  zh/aggregate-multiple-cluster-monitor-data.md
Labels: size/M, status/LGT2, status/can-merge, translation/doing, v1.2

#1305 en, zh: remove two controlled characters from the index pages
  en/_index.md
  zh/_index.md
Labels: size/XS, status/LGT2, status/can-merge, translation/done

#1288 en, zh: update the doc of configuring tidb cluster
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-release-1.1, size/XL, status/LGT2, status/can-merge, translation/done

#1274 zh: Add doc enable_tls_for_ticdc.md
  zh/TOC.md
  zh/enable_tls_for_ticdc_sink.md
Labels: needs-cherry-pick-release-1.1, size/M, status/LGT2, status/can-merge, translation/doing, v1.2

#1308 zh, en: update doc for tidb cluster config
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: size/L, status/LGT2, status/can-merge, translation/done, v1.2

#1317 fix a typo
  zh/enable-tls-for-mysql-client.md
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, size/XS, status/LGT2, status/can-merge, translation/no-need

#1311 zh: update the failover doc
  zh/configure-a-tidb-cluster.md
  zh/use-auto-failover.md
Labels: needs-cherry-pick-release-1.1, size/L, status/LGT2, status/can-merge, translation/doing

#1315 en: update Thanos
  en/aggregate-multiple-cluster-monitor-data.md
Labels: size/M, status/LGT2, status/can-merge, translation/from-zh, v1.2

#1322 Add v1.2 in pull_request_template.md
  .github/pull_request_template.md
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, size/XS, status/LGT2, status/can-merge, translation/no-need

#1329 zh: add what's new in v1.2
  zh/TOC.md
  zh/whats-new-in-v1.2.md
Labels: missing-translation-status, needs-cherry-pick-release-1.2, size/M, status/LGT2, status/can-merge

#1313 en: Add monitor multiplecluster and thanos doc
  en/monitor-a-tidb-cluster.md
  zh/monitor-a-tidb-cluster.md
Labels: needs-cherry-pick-release-1.2, size/M, status/LGT2, status/can-merge, translation/from-zh, v1.2

#1314 en: Add doc enable_tls_for_ticdc.md
  en/TOC.md
  en/enable-tls-for-ticdc-sink.md
  zh/TOC.md
  zh/enable-tls-for-ticdc-sink.md
Labels: needs-cherry-pick-release-1.2, size/M, status/LGT2, status/can-merge, translation/from-zh, v1.2

#1316 en: Add doc about RBAC roles that TiDB Operator requires
  en/tidb-operator-rbac.md
  zh/tidb-operator-rbac.md
Labels: needs-cherry-pick-release-1.1, needs-cherry-pick-release-1.2, size/L, status/LGT2, status/can-merge, translation/from-zh

#1330 en, zh: Bump Operator to v1.2.0
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: missing-translation-status, needs-cherry-pick-release-1.2, size/L, status/LGT2, status/can-merge

#1328 en, zh: add release notes for v1.2.0
  en/TOC.md
  en/releases/release-1.2.0.md
  zh/TOC.md
  zh/releases/release-1.2.0.md
Labels: missing-translation-status, size/M, status/LGT2, status/can-merge

#1332 remove doc `deploy-tidb-cluster-across-multiple-kubernetes.md`
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
Labels: size/XXL, status/LGT2, status/can-merge, translation/no-need

#1334 en: add what's new in v1.2
  en/TOC.md
  en/whats-new-in-v1.2.md
Labels: needs-cherry-pick-release-1.2, size/M, status/LGT2, status/can-merge, translation/from-zh

#1325 add v1.2 to the product index page
  en/_index.md
  zh/_index.md
Labels: needs-cherry-pick-master, size/S, status/LGT2, status/can-merge, translation/done

#1323 Update the CI configs for release-1.2
  .circleci/config.yml
  .github/workflows/ci.yaml
  .github/workflows/dispatch.yml
Labels: size/S, status/LGT1, status/can-merge, translation/no-need

#1343 en, zh: Update TiDB Operator version on the overview page
  en/tidb-operator-overview.md
  zh/tidb-operator-overview.md
Labels: size/XS, status/LGT2, status/can-merge, translation/done
