Repository pingcap/docs-tidb-operator, pull requests merged in 2021-06, with the labels that each got.

#1244 en: update docs about data mount path for DM-worker
  en/deploy-tidb-dm.md
  en/enable-tls-for-dm.md
Labels: size/S, status/LGT2, status/can-merge, translation/from-zh

#1246 zh,en: add deploy DM min operator version note
  en/deploy-tidb-dm.md
  zh/deploy-tidb-dm.md
Labels: first-time-contributor, size/XS, status/LGT2, status/can-merge, translation/done

#1224 zh: Update configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: contribution, first-time-contributor, needs-cherry-pick-release-1.1, size/S, status/LGT2, status/can-merge, translation/doing, translation/done

#1247 zh,en: fix spelling mistake
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: first-time-contributor, size/XS, status/LGT2, status/can-merge, translation/done

#1243 en: improve the doc of tidb-lightning
  en/cheat-sheet.md
  en/deploy-tidb-binlog.md
  en/destroy-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/restore-from-gcs.md
  en/restore-from-s3.md
  en/tidb-toolkit.md
Labels: needs-cherry-pick-release-1.1, size/M, status/LGT2, status/can-merge, translation/from-zh

#1249 en: Update configure-a-tidb-cluster.md
  en/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-release-1.1, size/S, status/LGT2, status/can-merge, translation/from-zh

#1260 en, zh: remote the note for single operator
  en/tidb-operator-overview.md
  zh/tidb-operator-overview.md
Labels: needs-cherry-pick-release-1.1, size/XS, status/LGT2, status/can-merge, translation/done

#1267 en, zh: Use the recommended method to enter a TiCDC Pod
  en/deploy-ticdc.md
  zh/deploy-ticdc.md
Labels: first-time-contributor, needs-cherry-pick-release-1.1, size/XS, status/LGT2, status/can-merge, translation/done

#1265 zh, en: update command of tidb-operator upgrade
  en/deploy-tidb-operator.md
  zh/deploy-tidb-operator.md
Labels: first-time-contributor, needs-cherry-pick-release-1.1, size/S, status/LGT2, status/can-merge, translation/done

#1278 en, zh: Update the docs to fix two broken links
  en/deploy-on-aws-eks.md
  en/logs-collection.md
  zh/deploy-on-aws-eks.md
  zh/logs-collection.md
Labels: needs-cherry-pick-release-1.1, size/XS, status/LGT2, status/can-merge, translation/done

#1254 zh: Add monitor multiplecluster and thanos doc.
  zh/monitor-a-tidb-cluster.md
Labels: contribution, size/M, status/LGT2, status/can-merge, status/require-change, translation/doing, v1.2

#1277 en, zh: Update the compatible TiDB versions for TiDB Operator
  en/_index.md
  zh/_index.md
Labels: needs-cherry-pick-release-1.1, size/XS, status/LGT2, status/can-merge, translation/done
