Repository pingcap/docs-tidb-operator, pull requests merged in 2021-03, with the labels that each got.

#1052 en: Deploy a TiDB Cluster across Multiple Kubernetes clusters
  en/TOC.md
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
Labels: status/LGT1, translation/from-zh

#1115 media: add 2 images for v1.0
  media/tidb-operator-control-flow-1.0.png
  media/tidb-operator-overview-1.0.png
Labels: follow-up, needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/LGT1, translation/no-need, version-specific-changes-required

#1116 en, zh: fix 1.0 docs image display error
  en/tidb-operator-overview.md
  zh/tidb-operator-overview.md
Labels: status/LGT1, translation/done

#1092 en: aggregate multiple TiDB Monitor data by thanos query
  en/TOC.md
  en/aggregate-multiple-cluster-monitor-data.md
  zh/aggregate-multiple-cluster-monitor-data.md
Labels: status/LGT1, translation/from-zh

#1120 media: update v1.0 overview and control flow images
  media/tidb-operator-control-flow-1.0.png
  media/tidb-operator-overview-1.0.png
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/LGT1, translation/no-need

#1124 en, zh: update release notes for v1.1.10
  en/releases/release-1.1.10.md
  zh/releases/release-1.1.10.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/done

#1127 en, zh: update capitalization of "Region"
  en/benchmark-sysbench.md
  en/collect-tidb-logs.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-gcp-gke.md
  zh/benchmark-sysbench.md
  zh/collect-tidb-logs.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-gcp-gke.md
Labels: needs-cherry-pick-1.1, needs-cherry-pick-master, status/DNM, status/LGT1, translation/done

#1126 CI: add file format lint script to check manual line breaks and file encoding
  .github/workflows/ci.yaml
  en/configure-a-tidb-cluster.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/enable-tls-between-components.md
  hack/check-conflicts.py
  hack/check-tags.py
  zh/configure-a-tidb-cluster.md
  zh/deploy-failures.md
  zh/deploy-on-general-kubernetes.md
  zh/enable-admission-webhook.md
  zh/scale-a-tidb-cluster.md
  zh/tidb-scheduler.md
  zh/upgrade-a-tidb-cluster.md
  zh/whats-new-in-v1.1.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, status/LGT2, translation/no-need

#1123 zh: doc for canary upgrade of tidb-operator
  zh/TOC.md
  zh/canary-upgrade-tidb-operator.md
  zh/deploy-multiple-tidb-operator.md
Labels: needs-cherry-pick-1.1, status/LGT1, translation/doing

#1134 en: remove extra spaces and test TiChi
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
Labels: needs-cherry-pick-1.1, size/XS, status/LGT2, status/PTAL, status/can-merge, status/require-change, translation/no-need

#1136 .github: delete stale workflow
  .github/workflows/stale.yaml
Labels: size/S, status/LGT2, status/can-merge, translation/no-need

#1130 en, zh: change "Region" capitalization
  en/benchmark-sysbench.md
  en/deploy-on-alibaba-cloud.md
  zh/benchmark-sysbench.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-gcp-gke.md
Labels: needs-cherry-pick-1.1, require-LGT1, size/S, status/LGT1, status/PTAL, status/can-merge, translation/done

#1143 .github: add workflow for semantic pr title
  .github/workflows/lint-pr-title.yml
Labels: require-LGT1, size/M, status/LGT1, status/can-merge, translation/no-need

#1144 .github: delete workflow for pr title lint
  .github/workflows/lint-pr-title.yml
Labels: require-LGT1, size/M, status/LGT1, status/can-merge, translation/no-need
