Repository pingcap/docs-tidb-operator, pull requests merged in 2021-04, with the labels that each got.

#1147 Fix format error in "copyable" codeblocks and other type error
  en/advanced-statefulset.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-gcs.md
  en/backup-to-pv-using-br.md
  en/backup-to-s3.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-aws-eks.md
  en/deploy-tidb-operator.md
  en/deploy-tiflash.md
  en/enable-tls-between-components.md
  en/initialize-a-cluster.md
  en/migrate-tidb-to-kubernetes.md
  zh/advanced-statefulset.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-pv-using-br.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-aws-eks.md
  zh/deploy-tidb-operator.md
  zh/enable-tls-between-components.md
  zh/initialize-a-cluster.md
Labels: needs-cherry-pick-1.1, require-LGT1, size/M, status/LGT1, status/can-merge, translation/no-need

#1142 .github: enable manual rebase
  .github/workflows/rebase.yml
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, require-LGT1, size/S, status/LGT1, status/can-merge, translation/no-need

#1137 en: add doc for canary upgrade tidb operator
  en/TOC.md
  en/canary-upgrade-tidb-operator.md
  en/deploy-multiple-tidb-operator.md
Labels: needs-cherry-pick-1.1, size/L, status/LGT2, status/can-merge, translation/from-zh

#1153 en, zh: bump TiDB Operator charts version to v1.2.0-beta.1
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: size/L, status/LGT2, status/can-merge, translation/done

#1154 en, zh: add release notes for v1.2.0-beta.1
  en/releases/release-1.2.0-beta.1.md
  zh/releases/release-1.2.0-beta.1.md
Labels: size/M, status/LGT2, status/can-merge, translation/done

#1155 Fix release note TOC for v1.2.0-beta.1
  en/TOC.md
  zh/TOC.md
Labels: require-LGT1, size/XS, status/LGT1, status/can-merge, translation/done

#1156 Correct some release notes in v1.2.0-beta.1
  en/releases/release-1.2.0-beta.1.md
  zh/releases/release-1.2.0-beta.1.md
Labels: require-LGT1, size/M, status/LGT1, status/can-merge, translation/done

#1157 Add rolling upgrade notice for v1.2.0-beta.1
  en/releases/release-1.2.0-beta.1.md
  zh/releases/release-1.2.0-beta.1.md
Labels: require-LGT1, size/XS, status/LGT2, status/can-merge, translation/done

#1160 en,zh; Bump tidb components to v4.0.12
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/configure-a-tidb-cluster.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-enterprise-edition.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/monitor-a-tidb-cluster.md
  en/notes-tidb-operator-v1.1.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-enterprise-edition.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
  zh/monitor-a-tidb-cluster.md
  zh/notes-tidb-operator-v1.1.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-data-using-tidb-lightning.md
  zh/upgrade-a-tidb-cluster.md
Labels: size/L, status/LGT1, status/can-merge, translation/done

#1161 en, zh: add release notes for v1.1.12
  en/TOC.md
  en/releases/release-1.1.12.md
  zh/TOC.md
  zh/releases/release-1.1.12.md
Labels: needs-cherry-pick-1.1, sig/docs, sig/k8s, size/M, status/LGT2, status/can-merge, translation/done

#1162 en, zh: Bump Operator to v1.1.12
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: size/L, status/LGT1, status/can-merge, translation/done

#1158 en,zh: fix wrong dmctl command
  en/enable-tls-for-dm.md
  zh/enable-tls-for-dm.md
Labels: first-time-contributor, sig/docs, sig/migrate, size/XS, status/LGT2, status/can-merge, translation/done

#1168 zh, en: update docs about configure namespace scoped TiDB operator
  en/deploy-tidb-operator.md
  zh/deploy-tidb-operator.md
Labels: size/S, status/LGT2, status/PTAL, status/can-merge, translation/done

#1169 zh, en: update docs for DM
  en/deploy-tidb-dm.md
  en/enable-tls-for-dm.md
  zh/deploy-tidb-dm.md
  zh/enable-tls-for-dm.md
Labels: size/L, status/LGT2, status/PTAL, status/can-merge, translation/done

#1165 zh, en: fix initialCommitTs for drainer
  en/configure-tidb-binlog-drainer.md
  en/deploy-tidb-binlog.md
  zh/configure-tidb-binlog-drainer.md
  zh/deploy-tidb-binlog.md
Labels: needs-cherry-pick-1.1, size/S, status/LGT2, status/PTAL, status/can-merge, translation/done

#1167 zh,en: Update deploy-tidb-cluster-across-multiple-kubernetes.md
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
Labels: size/S, status/LGT2, status/PTAL, status/can-merge, translation/done

#1173 get-started: explain what `tc` means
  en/get-started.md
Labels: first-time-contributor, needs-cherry-pick-1.1, size/XS, status/LGT2, status/can-merge, translation/doing

#1171 Include TiDB v5.0 in supported versions
  en/_index.md
  en/tidb-operator-overview.md
Labels: first-time-contributor, needs-cherry-pick-1.1, size/XS, status/LGT2, status/can-merge, translation/doing

#1178 zh, en: refine docs for deploying TiDB on GKE
  en/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-1.1, size/S, status/LGT2, status/can-merge, translation/no-need

#1179 en, zh: Update the warning for demonstration purposes
  en/get-started.md
  zh/get-started.md
Labels: first-time-contributor, needs-cherry-pick-1.0, needs-cherry-pick-1.1, size/XS, status/LGT2, status/can-merge, translation/no-need

#1164 en, zh: add what's next for get-started.md
  en/get-started.md
  zh/get-started.md
Labels: needs-cherry-pick-1.1, size/S, status/LGT2, status/can-merge, translation/done

#1172 get-started: add alias for kubectl in minikube
  en/get-started.md
Labels: first-time-contributor, needs-cherry-pick-1.1, size/XS, status/LGT2, status/can-merge, translation/doing

#1176 zh: Include TiDB v5.0 in supported versions #1171
  zh/_index.md
  zh/get-started.md
  zh/tidb-operator-overview.md
Labels: first-time-contributor, needs-cherry-pick-1.1, size/S, status/LGT2, status/PTAL, status/can-merge, translation/from-en

#1177 en,zh: update linked docs version in tls
  en/enable-tls-between-components.md
  zh/enable-tls-between-components.md
Labels: needs-cherry-pick-1.1, requires-version-specific-changes, size/XS, status/LGT2, status/can-merge, translation/done

#1187 en, zh: add clarify for additionalVolumeMounts
  en/backup-to-pv-using-br.md
  en/configure-a-tidb-cluster.md
  zh/backup-to-pv-using-br.md
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, size/S, status/LGT2, status/can-merge, translation/done

#1192 zh: get-started: add alias for kubectl in minikube #1172
  zh/get-started.md
Labels: needs-cherry-pick-1.1, size/XS, status/LGT2, status/can-merge, translation/from-en

#1195 en,zh; Bump tidb components to v5.0.1
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/configure-a-tidb-cluster.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-enterprise-edition.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/monitor-a-tidb-cluster.md
  en/notes-tidb-operator-v1.1.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-enterprise-edition.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
  zh/monitor-a-tidb-cluster.md
  zh/notes-tidb-operator-v1.1.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-data-using-tidb-lightning.md
  zh/upgrade-a-tidb-cluster.md
Labels: size/L, status/LGT2, status/can-merge, translation/done

#1196 en, zh: add release notes for v1.2.0-beta.2
  en/TOC.md
  en/releases/release-1.2.0-beta.2.md
  zh/TOC.md
  zh/releases/release-1.2.0-beta.2.md
Labels: size/M, status/LGT2, status/can-merge, translation/done

#1198 en, zh: Bump Operator to v1.2.0-beta.2
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: size/L, status/LGT2, status/can-merge, translation/done

#1184 en, zh: add docs of topology spread constraints and security context
  en/TOC.md
  en/_index.md
  en/configure-a-tidb-cluster.md
  en/containers-run-as-non-root-user.md
  en/deploy-tidb-dm.md
  en/tidb-scheduler.md
  zh/TOC.md
  zh/_index.md
  zh/configure-a-tidb-cluster.md
  zh/containers-run-as-non-root-user.md
  zh/deploy-tidb-dm.md
  zh/tidb-scheduler.md
Labels: size/XL, status/LGT2, status/can-merge, translation/done

#1186 en, zh: add some clarify for dashboard
  en/access-dashboard.md
  zh/access-dashboard.md
Labels: needs-cherry-pick-1.1, size/S, status/LGT2, status/can-merge, translation/done

#1191 en, zh: add clarify for storageVolumes
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-1.1, size/XS, status/LGT2, status/can-merge, translation/done

#1146 en, zh: Add description about spec.toolImage
  en/backup-restore-overview.md
  zh/backup-restore-overview.md
Labels: needs-cherry-pick-1.1, size/S, status/LGT2, status/can-merge, status/require-change, translation/done

#1194 en, zh: explain TidbCluster spec.discovery
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: contribution, first-time-contributor, needs-cherry-pick-1.1, requires-version-specific-changes, size/M, status/LGT2, status/can-merge, translation/done
