Repository pingcap/docs-tidb-operator, pull requests merged in 2021-12, with the labels that each got.

#1467 fix typos 'reqeust'
  zh/configure-a-tidb-cluster.md
  zh/deploy-tiflash.md
Labels: status/can-merge, status/LGT1, translation/no-need, type/bug-fix, require-LGT1, size/XS

#1366 add deploy-on-azure-aks.md for Azure AKS cluster
  en/TOC.md
  en/deploy-on-azure-aks.md
  zh/TOC.md
  zh/deploy-on-azure-aks.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/done, size/XXL, needs-cherry-pick-release-1.2, type/compatibility-or-feature-change

#1399 zh:add tibdmonitor remote write introduction
  zh/aggregate-multiple-cluster-monitor-data.md
Labels: status/can-merge, status/LGT2, status/PTAL, translation/doing, size/M, needs-cherry-pick-release-1.2, type/compatibility-or-feature-change

#1472 .github: enable lychee external link checker
  .github/exclude-links.txt
  .github/workflows/link-check.yaml
  .github/workflows/link.yml
  README.md
  en/backup-restore-overview.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/L

#1452 en: add a doc and notes about deploying a cluster on ARM64
  en/TOC.md
  en/deploy-cluster-on-arm64.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  en/get-started.md
Labels: type/enhancement, needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/from-zh, first-time-contributor, size/L, needs-cherry-pick-release-1.2

#1463 en: add tidbmonitor dynamic configuration
  .gitignore
  en/TOC.md
  en/enable-dynamic-configuration-for-tidbmonitor.md
Labels: status/can-merge, status/LGT2, translation/from-zh, size/M, v1.3

#1480 chore: update dispatch for latest docs site
  .github/workflows/dispatch.yml
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/no-need, needs-cherry-pick-release-1.2

#1476 Update deploy-on-aws-eks.md
  zh/deploy-on-aws-eks.md
Labels: contribution, needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/doing, first-time-contributor, size/XS, needs-cherry-pick-release-1.2

#1466 en,zh: Use `mysql --comments` everywhere
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/enable-tls-for-mysql-client.md
  en/get-started.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/enable-tls-for-mysql-client.md
  zh/get-started.md
Labels: type/enhancement, status/can-merge, status/LGT1, translation/done, require-LGT1, size/M

#1415 zh:add tidbmonitor shards doc
  zh/TOC.md
  zh/enable-monitor-shards.md
Labels: status/can-merge, status/LGT2, translation/doing, size/M, v1.3, type/compatibility-or-feature-change

#1403 zh: doc for how to evict tikv pod
  en/monitor-kubernetes.md
  zh/maintain-a-kubernetes-node.md
  zh/monitor-kubernetes.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/doing, size/XL, needs-cherry-pick-release-1.2, type/compatibility-or-feature-change

#1465 en: add aws instance type recommendation
  en/deploy-on-aws-eks.md
  zh/deploy-on-aws-eks.md
Labels: type/enhancement, needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/from-zh, require-LGT1, size/XL, needs-cherry-pick-release-1.2

#1478 en, zh: reorganize TOC topics
  en/TOC.md
  zh/TOC.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.2

#1484 en,zh: graceful restart tikv
  en/restart-a-tidb-cluster.md
  zh/restart-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/done, size/M

#1482 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/no-need, first-time-contributor, size/XS, needs-cherry-pick-release-1.2

#1481 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/no-need, first-time-contributor, size/XS

#1473 en: add tidbmonitor remote write
  en/aggregate-multiple-cluster-monitor-data.md
Labels: status/can-merge, status/LGT2, translation/from-zh, size/M, needs-cherry-pick-release-1.2, type/compatibility-or-feature-change

#1498 en: rename tidbmonitor dynamic config to align with zh
  en/TOC.md
  en/enable-monitor-dynamic-configuration.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS, v1.3

#1434 en,zh: Adjust for v1 CRD
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/upgrade-tidb-operator.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, status/PTAL, translation/done, size/L, v1.3, type/compatibility-or-feature-change

#1515 en, zh: add ebs-csi-node toleration
  en/deploy-on-aws-eks.md
  zh/deploy-on-aws-eks.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, needs-cherry-pick-release-1.2

#1518 en: fix aliases in monitor dynamic config
  en/enable-monitor-dynamic-configuration.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS

#1519 change file mode
  scripts/generate_pdf.sh
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS

#1499 Refine get-started.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
Labels: status/can-merge, status/LGT2, translation/done, first-time-contributor, size/XXL, needs-cherry-pick-release-1.2

#1522 deleted font tags
  en/get-started.md
  zh/get-started.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/L, needs-cherry-pick-release-1.2

#1524 fix <pre><code> tags
  en/get-started.md
  zh/get-started.md
Labels: status/can-merge, status/LGT1, translation/done, require-LGT1, size/XS, needs-cherry-pick-release-1.2

#1526 corrected a typo in get-started
  zh/get-started.md
Labels: status/can-merge, status/LGT1, translation/no-need, type/bug-fix, require-LGT1, needs-cherry-pick-release-1.2

#1528 en: update eks storagclass config
  en/deploy-on-aws-eks.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/from-zh, require-LGT1, size/XS, needs-cherry-pick-release-1.2

#1511 Optimize deploy multiple operator
  en/TOC.md
  en/deploy-multiple-tidb-operator.md
  zh/TOC.md
  zh/deploy-multiple-tidb-operator.md
Labels: type/enhancement, status/can-merge, status/LGT2, translation/no-need, size/L, needs-cherry-pick-release-1.2

#1531 en,zh: Bump TiDB and DM to v5.3.0
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-restore-overview.md
  en/configure-a-tidb-cluster.md
  en/deploy-cluster-on-arm64.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-dm.md
  en/deploy-tidb-enterprise-edition.md
  en/enable-tls-between-components.md
  en/enable-tls-for-dm.md
  en/enable-tls-for-mysql-client.md
  en/get-started.md
  en/monitor-a-tidb-cluster.md
  en/notes-tidb-operator-v1.1.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-restore-overview.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-cluster-on-arm64.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-dm.md
  zh/deploy-tidb-enterprise-edition.md
  zh/enable-monitor-shards.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-dm.md
  zh/enable-tls-for-mysql-client.md
  zh/get-started.md
  zh/monitor-a-tidb-cluster.md
  zh/notes-tidb-operator-v1.1.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-data-using-tidb-lightning.md
  zh/upgrade-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/done, size/XL, needs-cherry-pick-release-1.2

#1536 Fix links and code block format
  en/get-started.md
  zh/get-started.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, needs-cherry-pick-release-1.2

#1533 en,zh: Bump operator to v1.2.5
  en/cheat-sheet.md
  en/deploy-cluster-on-arm64.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-cluster-on-arm64.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.2

#1532 en,zh: add release notes for v1.2.5
  en/TOC.md
  en/releases/release-1.2.5.md
  zh/TOC.md
  zh/releases/release-1.2.5.md
Labels: status/can-merge, status/LGT2, translation/done, missing-translation-status, size/M, needs-cherry-pick-release-1.2

#1513 Optimizer disaster recovery docs
  zh/TOC.md
  zh/pd-recover.md
  zh/recover-deleted-cluster.md
Labels: type/enhancement, status/can-merge, status/LGT2, translation/doing, size/M, needs-cherry-pick-release-1.2

#1545 Add a stop
  zh/get-started.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, needs-cherry-pick-release-1.2

#1547 Polished format in details
  en/get-started.md
  zh/get-started.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, needs-cherry-pick-release-1.2

#1549 Updated descriptions about minikube
  zh/get-started.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS, needs-cherry-pick-release-1.2

#1507 zh, en: optimize access-dashboard.md
  en/access-dashboard.md
  zh/access-dashboard.md
Labels: type/enhancement, status/can-merge, status/LGT2, translation/no-need, size/L, needs-cherry-pick-release-1.2

#1553 update get-started doc
  zh/get-started.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, needs-cherry-pick-release-1.2

#1503 en, zh: optimize upgrade-tidb-operator
  en/upgrade-tidb-operator.md
  zh/upgrade-tidb-operator.md
Labels: type/enhancement, status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.2

#1557 Verified the doc and made changes
  en/get-started.md
Labels: status/can-merge, status/LGT2, translation/from-zh, size/M, needs-cherry-pick-release-1.2

#1554 Optimizer disaster recovery docs
  en/pd-recover.md
  en/recover-deleted-cluster.md
Labels: type/enhancement, status/can-merge, status/LGT1, translation/from-zh, require-LGT1, size/M, needs-cherry-pick-release-1.2

#1496 zh, en: optimze Dumpling/TiDB Lightning backup and restore docs
  en/backup-to-gcs.md
  en/backup-to-s3.md
  en/restore-from-gcs.md
  en/restore-from-s3.md
  zh/backup-to-gcs.md
  zh/backup-to-s3.md
  zh/restore-from-gcs.md
  zh/restore-from-s3.md
Labels: type/enhancement, status/can-merge, status/LGT2, translation/doing, size/XXL

#1567 Update get-started.md
  zh/get-started.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS, needs-cherry-pick-release-1.2

#1555 en, zh: improve scaling documents
  en/enable-tidb-cluster-auto-scaling.md
  en/scale-a-tidb-cluster.md
  zh/enable-tidb-cluster-auto-scaling.md
  zh/scale-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/done, size/XL, needs-cherry-pick-release-1.2

#1542 en, zh: improve security documents
  en/containers-run-as-non-root-user.md
  en/deploy-ticdc.md
  en/enable-tls-for-ticdc-sink.md
  zh/containers-run-as-non-root-user.md
  zh/deploy-ticdc.md
  zh/enable-tls-for-ticdc-sink.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.2
