Repository pingcap/docs-tidb-operator, pull requests merged in 2022-05, with the labels that each got.

#1615 Add doc for replace TiDB cluster nodes
  en/TOC.md
  en/replace-nodes-for-cloud-disk.md
  en/replace-nodes-for-local-disk.md
  zh/replace-nodes-for-local-disk.md
Labels: status/can-merge, status/LGT2, translation/from-zh, size/XL, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1821 fix 2 broken links
  en/monitor-kubernetes.md
  zh/monitor-kubernetes.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/done, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1827 en,zh; Bump tidb components to v5.4.1
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-restore-cr.md
  en/configure-a-tidb-cluster.md
  en/deploy-cluster-on-arm64.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  en/deploy-tidb-dm.md
  en/enable-tls-between-components.md
  en/enable-tls-for-dm.md
  en/enable-tls-for-mysql-client.md
  en/get-started.md
  en/monitor-a-tidb-cluster.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-cluster-on-arm64.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-dm.md
  zh/deploy-tidb-monitor-across-multiple-kubernetes.md
  zh/enable-monitor-shards.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-dm.md
  zh/enable-tls-for-mysql-client.md
  zh/get-started.md
  zh/monitor-a-tidb-cluster.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/done, size/XL, needs-cherry-pick-release-1.3

#1826 en,zh: add release note 1.3.3
  en/TOC.md
  en/releases/release-1.3.3.md
  zh/TOC.md
  zh/releases/release-1.3.3.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, needs-cherry-pick-release-1.3

#1829 en,zh: Bump operator version to v1.3.3
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/done, require-LGT1, size/L, needs-cherry-pick-release-1.3

#1786 en: add faq about configUpdateStrategy
  en/configure-a-tidb-cluster.md
  en/faq.md
  zh/configure-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/from-zh, size/S, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1798 en: improve TLS docs
  en/enable-tls-between-components.md
  en/enable-tls-for-dm.md
  en/enable-tls-for-mysql-client.md
  zh/enable-tls-for-mysql-client.md
Labels: type/enhancement, status/can-merge, status/LGT2, translation/from-zh, size/S, needs-cherry-pick-release-1.3

#1819 add two docs about clinic user guide for operator
  media/clinic-get-token.png
  zh/TOC.md
  zh/clinic-data-instruction.md
  zh/clinic-user-guide.md
Labels: status/can-merge, status/LGT2, translation/doing, first-time-contributor, size/XXL, needs-cherry-pick-release-1.3, area/clinic

#1836 Add Technical Preview for PingCAP Clinic
  zh/TOC.md
Labels: type/enhancement, status/can-merge, status/LGT2, translation/no-need, size/XS, needs-cherry-pick-release-1.3, area/clinic

#1839 Add exclude-links
  .github/exclude-links.txt
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/no-need, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1791 en: add fields in br crd
  en/backup-restore-cr.md
  zh/backup-restore-cr.md
Labels: status/can-merge, status/LGT2, translation/from-zh, size/M, needs-cherry-pick-release-1.3, area/br
