Repository pingcap/docs-tidb-operator, pull requests merged in 2022-09, with the labels that each got.

#1995 en,zh: release notes for 1.3.8
  en/TOC.md
  en/releases/release-1.3.8.md
  zh/TOC.md
  zh/releases/release-1.3.8.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, needs-cherry-pick-release-1.3

#1992 bump operator to v1.3.8
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, translation/done, size/L

#1993 bump operator to v1.3.8 for release-1.3
  en/advanced-statefulset.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-gcs.md
  en/backup-to-pv-using-br.md
  en/backup-to-s3.md
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/initialize-a-cluster.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs-using-br.md
  en/restore-from-gcs.md
  en/restore-from-pv-using-br.md
  en/restore-from-s3.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/advanced-statefulset.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-gcs.md
  zh/backup-to-pv-using-br.md
  zh/backup-to-s3.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/initialize-a-cluster.md
  zh/monitor-a-tidb-cluster.md
  zh/restore-from-aws-s3-using-br.md
  zh/restore-from-gcs-using-br.md
  zh/restore-from-gcs.md
  zh/restore-from-pv-using-br.md
  zh/restore-from-s3.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/done, size/XL

#1998 Fix broken links
  en/configure-a-tidb-cluster.md
  en/deploy-failures.md
  en/deploy-ticdc.md
  en/deploy-tidb-binlog.md
  en/enable-tls-for-mysql-client.md
  en/faq.md
  en/monitor-a-tidb-cluster.md
  en/pd-recover.md
  en/tidb-toolkit.md
Labels: status/can-merge, status/LGT1, translation/no-need, type/bug-fix, require-LGT1, size/M, needs-cherry-pick-release-1.3

#1973 add clusterScoped for monitor multiple clusters
  en/monitor-a-tidb-cluster.md
  zh/monitor-a-tidb-cluster.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/done, require-LGT1, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1951 ticdc: add docs about TiCDC graceful upgrade
  en/configure-a-tidb-cluster.md
  en/tips.md
  zh/configure-a-tidb-cluster.md
  zh/tips.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, needs-cherry-pick-release-1.3, area/ticdc, tidb/v6.3

#1775 en: add doc for multi-cluster prometheus monitor
  en/TOC.md
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  en/deploy-tidb-monitor-across-multiple-kubernetes.md
  zh/deploy-tidb-monitor-across-multiple-kubernetes.md
Labels: status/can-merge, status/LGT2, translation/from-zh, size/XL, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#2010 en,zh: add release note for 1.4.0-alpha.1
  .github/pull_request_template.md
  en/TOC.md
  en/_index.md
  en/releases/release-1.4.0-alpha.1.md
  en/tidb-operator-overview.md
  zh/TOC.md
  zh/_index.md
  zh/releases/release-1.4.0-alpha.1.md
  zh/tidb-operator-overview.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, v1.4, needs-cherry-pick-release-1.4

#1990 set labels for tidb
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/done, first-time-contributor, size/M, v1.4, tidb/v6.3, needs-cherry-pick-release-1.4

#2018 *: fix minor issues for v1.4
  en/TOC.md
  en/_index.md
  en/releases/release-1.4.0-alpha.1.md
  en/whats-new-in-v1.3.md
  zh/TOC.md
  zh/_index.md
  zh/releases/release-1.4.0-alpha.1.md
  zh/whats-new-in-v1.3.md
Labels: status/can-merge, status/LGT1, translation/no-need, size/L, v1.4

#2019 Fix admonition format
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-azure-aks.md
  en/deploy-tiflash.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-tiflash.md
Labels: status/can-merge, status/LGT2, translation/done, type/bug-fix, size/S, needs-cherry-pick-release-1.3

#2012 en, zh: Update recommended instance type
  en/deploy-on-aws-eks.md
  en/deploy-on-gcp-gke.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/done, size/S, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2025 Update deploy-on-aws-eks.md
  en/deploy-on-aws-eks.md
  zh/deploy-on-aws-eks.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/S
