Repository pingcap/docs-tidb-operator, pull requests merged in 2022-07, with the labels that each got.

#1900 clinic: update Clinic TOC and user guide
  media/clinic-get-token.png
  zh/TOC.md
  zh/clinic-user-guide.md
Labels: type/enhancement, status/can-merge, status/LGT2, translation/done, require-LGT1, size/XL, needs-cherry-pick-release-1.3, area/clinic

#1927 ci: use concurrency to cancel previous workflow
  .github/workflows/ci.yaml
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1932 en,zh: release note for 1.3.6
  en/TOC.md
  en/releases/release-1.3.6.md
  zh/TOC.md
  zh/releases/release-1.3.6.md
Labels: status/can-merge, status/LGT2, translation/done, size/S, needs-cherry-pick-release-1.3

#1934 bump operator to v1.3.6 for release-1.3
  en/advanced-statefulset.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-gcs.md
  en/backup-to-pv-using-br.md
  en/backup-to-s3.md
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-cluster-on-arm64.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/initialize-a-cluster.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs-using-br.md
  en/restore-from-gcs.md
  en/restore-from-pv-using-br.md
  en/restore-from-s3.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/advanced-statefulset.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-gcs.md
  zh/backup-to-pv-using-br.md
  zh/backup-to-s3.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/initialize-a-cluster.md
  zh/monitor-a-tidb-cluster.md
  zh/restore-from-aws-s3-using-br.md
  zh/restore-from-gcs-using-br.md
  zh/restore-from-gcs.md
  zh/restore-from-pv-using-br.md
  zh/restore-from-s3.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/done, size/XL

#1926 Fix broken link
  en/backup-restore-overview.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-azblob-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-pv-using-br.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-azblob-using-br.md
  en/restore-from-gcs-using-br.md
  en/restore-from-pv-using-br.md
Labels: status/can-merge, status/LGT1, translation/no-need, type/bug-fix, require-LGT1, size/S

#1933 bump operator to 1.3.6
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, missing-translation-status, size/L

#1936 fix back-up-incremental-data link
  en/backup-to-aws-s3-using-br.md
  en/backup-to-azblob-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-pv-using-br.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/no-need, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, area/br

#1890 clinic: add Troubleshoot TiDB cluster using PingCAP Clinic and PingCAP Clinic Diagnostic Data
  en/TOC.md
  en/clinic-data-collection.md
  en/clinic-user-guide.md
  zh/TOC.md
  zh/clinic-data-collection.md
  zh/clinic-user-guide.md
Labels: status/can-merge, status/LGT2, translation/from-zh, size/XXL, needs-cherry-pick-release-1.3, area/clinic

#1942 add content for clinic us
  en/TOC.md
  en/clinic-data-collection.md
  en/clinic-user-guide.md
  zh/TOC.md
  zh/clinic-data-collection.md
  zh/clinic-user-guide.md
Labels: type/enhancement, status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.3, area/clinic

#1945 add cleanPolicy for BackupSchedule
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
Labels: type/enhancement, needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/done, size/S, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1944 fix simpletab issues
  en/_index.md
  en/clinic-user-guide.md
  en/configure-a-tidb-cluster.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/get-started.md
  zh/_index.md
  zh/clinic-user-guide.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-tidb-monitor-across-multiple-kubernetes.md
  zh/get-started.md
  zh/tidb-operator-overview.md
Labels: status/can-merge, status/LGT2, translation/no-need, size/L, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3
