Repository pingcap/docs-tidb-operator, pull requests merged in 2022-10, with the labels that each got.

#2026 fix-release-1.3.8-zh
  zh/releases/release-1.3.8.md
Labels: status/can-merge, status/LGT1, translation/no-need, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#1941 add aliases for 8 docs
  en/backup-and-restore-using-helm-charts.md
  en/configure-backup.md
  en/notes-tidb-operator-v1.1.md
  en/tidb-cluster-chart-config.md
  zh/backup-and-restore-using-helm-charts.md
  zh/configure-backup.md
  zh/notes-tidb-operator-v1.1.md
  zh/tidb-cluster-chart-config.md
Labels: status/can-merge, status/LGT1, translation/no-need, type/bug-fix, size/S

#2029 en,zh: release note for 1.3.9
  en/TOC.md
  en/releases/release-1.3.9.md
  zh/TOC.md
  zh/releases/release-1.3.9.md
Labels: status/can-merge, status/LGT2, translation/done, size/S, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2030 en,zh: bump operator to v1.3.9
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, translation/done, size/L

#2031 bump operator to v1.3.9 for release-1.3
  en/advanced-statefulset.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-gcs.md
  en/backup-to-pv-using-br.md
  en/backup-to-s3.md
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/initialize-a-cluster.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs-using-br.md
  en/restore-from-gcs.md
  en/restore-from-pv-using-br.md
  en/restore-from-s3.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/advanced-statefulset.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-gcs.md
  zh/backup-to-pv-using-br.md
  zh/backup-to-s3.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/initialize-a-cluster.md
  zh/monitor-a-tidb-cluster.md
  zh/restore-from-aws-s3-using-br.md
  zh/restore-from-gcs-using-br.md
  zh/restore-from-gcs.md
  zh/restore-from-pv-using-br.md
  zh/restore-from-s3.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT1, missing-translation-status, size/XL

#2000 fix-spelling in restore-from-aws-s3-using-br
  en/restore-from-aws-s3-using-br.md
  zh/restore-from-aws-s3-using-br.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/done, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#2011 fix-configure-storage-class
  en/configure-storage-class.md
  zh/configure-storage-class.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/done, require-LGT1, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2005 Add a step to check asts is deployed
  en/advanced-statefulset.md
  zh/advanced-statefulset.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/done, size/M, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#1874 update all old links for docs.pingcap.com
  README.md
  en/releases/release-1.0-ga.md
  en/releases/release-1.0.4.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-failures.md
  zh/deploy-ticdc.md
  zh/deploy-tidb-binlog.md
  zh/enable-tls-for-mysql-client.md
  zh/faq.md
  zh/monitor-a-tidb-cluster.md
  zh/pd-recover.md
  zh/prerequisites.md
  zh/releases/release-1.0-ga.md
  zh/releases/release-1.0.4.md
  zh/restore-data-using-tidb-lightning.md
  zh/restore-from-aws-s3-using-br.md
  zh/tidb-toolkit.md
Labels: status/can-merge, status/LGT1, translation/done, require-LGT1, size/M, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2048 en: add pitr docs
  en/backup-restore-cr.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-azblob-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-pv-using-br.md
  en/restore-from-azblob-using-br.md
Labels: status/can-merge, status/LGT2, translation/from-zh, size/XXL, v1.4, needs-cherry-pick-release-1.4, tidb/v6.4

#2052 bump operator to v1.4.0-beta.1 for release-1.4
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/done, first-time-contributor, size/L, v1.4

#2050 en,zh: add 1.4.0-beta.1 release notes
  en/TOC.md
  en/releases/release-1.4.0-beta.1.md
  zh/TOC.md
  zh/releases/release-1.4.0-beta.1.md
Labels: status/can-merge, status/LGT2, translation/done, first-time-contributor, size/M, v1.4, needs-cherry-pick-release-1.4

#2046 zh: add doc about PITR on azure blob storage
  zh/backup-restore-cr.md
  zh/backup-restore-overview.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-azblob-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-pv-using-br.md
  zh/restore-from-azblob-using-br.md
Labels: status/can-merge, status/LGT2, translation/done, first-time-contributor, size/XXL, needs-cherry-pick-release-1.4

#2049 support aws ebs snapshot based backup and restore
  media/volume-snapshot-backup-restore-overview.png
  media/volume-snapshot-backup-workflow.png
  media/volume-snapshot-restore-workflow.png
  zh/TOC.md
  zh/backup-restore-cr.md
  zh/backup-restore-overview.md
  zh/backup-to-aws-s3-by-snapshot.md
  zh/grant-permissions-to-remote-storage.md
  zh/restore-from-aws-s3-by-snapshot.md
  zh/volume-snapshot-backup-restore.md
Labels: status/can-merge, status/LGT1, status/LGT2, translation/doing, first-time-contributor, size/XL, tidb/v6.4

#2059 en,zh: Bump version 1.4.0 beta.1
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/done, require-LGT1, size/L

#2060 en,zh: update old links
  en/faq.md
  en/modify-tidb-configuration.md
  en/prerequisites.md
  zh/backup-to-gcs.md
  zh/backup-to-s3.md
  zh/benchmark-sysbench.md
  zh/modify-tidb-configuration.md
  zh/restore-from-azblob-using-br.md
  zh/restore-from-gcs-using-br.md
Labels: status/can-merge, status/LGT1, translation/done, require-LGT1, size/S, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2063 zh: fix typos of config
  zh/backup-to-azblob-using-br.md
  zh/restore-from-azblob-using-br.md
Labels: status/can-merge, status/LGT2, missing-translation-status, size/M

#2051 improve pd recover doc
  en/pd-recover.md
  zh/pd-recover.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/done, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2064 *: changed to learning path style
  en/_index.md
  zh/_index.md
Labels: status/can-merge, status/LGT1, translation/done, require-LGT1, size/L, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4
