Repository pingcap/docs-tidb-operator, pull requests merged in 2022-06, with the labels that each got.

#1848 add aliases for kind doc in v1.0
  en/get-started.md
  zh/get-started.md
Labels: status/can-merge, status/LGT1, translation/no-need, size/XS

#1847 remove outdated docs
  en/TOC.md
  en/_index.md
  en/deploy-tidb-from-kubernetes-kind.md
  en/deploy-tidb-from-kubernetes-minikube.md
  en/deploy-tidb-operator.md
  en/tidb-operator-overview.md
  zh/TOC.md
  zh/_index.md
  zh/deploy-tidb-from-kubernetes-kind.md
  zh/deploy-tidb-from-kubernetes-minikube.md
  zh/deploy-tidb-operator.md
  zh/tidb-operator-overview.md
Labels: status/can-merge, status/LGT1, translation/no-need, size/XL

#1793 en, zh: Update version of docker
  en/get-started.md
  zh/get-started.md
Labels: status/can-merge, status/LGT2, translation/done, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1854 ci: download exclude-links.txt from docs repo
  .github/exclude-links.txt
  .github/workflows/link.yml
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/M

#1857 ci: update node-version to 16
  .github/workflows/ci.yaml
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1862 ci: update node version (again)
  .github/workflows/ci.yaml
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/M

#1866 Fix 404 link: Kubernetes scheduler extender
  en/tidb-scheduler.md
  zh/tidb-scheduler.md
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/no-need, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1876 fix quote missed error
  en/pd-recover.md
  zh/pd-recover.md
Labels: contribution, status/can-merge, status/LGT2, translation/done, first-time-contributor, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1881 generate_pdf.sh: change file mode to be executable
  scripts/generate_pdf.sh
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/no-need, size/XS

#1885 en, zh: fix a typo in release notes
  en/releases/release-1.2.7.md
  en/releases/release-1.3.0.md
  zh/releases/release-1.2.7.md
  zh/releases/release-1.3.0.md
Labels: status/can-merge, status/LGT2, translation/done, type/bug-fix, size/XS, v1.2

#1875 Update clinic-data-instruction.md
  zh/clinic-data-instruction.md
Labels: status/can-merge, status/LGT2, translation/done, size/XS, area/clinic

#1887 en,zh: release note for 1.3.4
  en/TOC.md
  en/releases/release-1.3.4.md
  zh/TOC.md
  zh/releases/release-1.3.4.md
Labels: status/can-merge, status/LGT2, translation/done, size/S, needs-cherry-pick-release-1.3

#1888 en,zh: Bump operator to v1.3.4
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.3

#1884 Dumpling: fix broken link
  en/backup-to-s3.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1894 zh: Support BR on Azure Blob Storage
  zh/backup-restore-cr.md
  zh/backup-to-azblob-using-br.md
  zh/grant-permissions-to-remote-storage.md
  zh/restore-from-azblob-using-br.md
Labels: contribution, status/can-merge, status/LGT2, translation/doing, first-time-contributor, size/XXL, needs-cherry-pick-release-1.3, area/br
