Repository pingcap/docs-tidb-operator, pull requests merged in 2022-03, with the labels that each got.

#1696 fix backup rbac link in v1.1 and v1.2 operator doc
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-gcs.md
  en/backup-to-pv-using-br.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs-using-br.md
  en/restore-from-gcs.md
  en/restore-from-pv-using-br.md
  en/restore-from-s3.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-gcs.md
  zh/backup-to-pv-using-br.md
  zh/restore-from-aws-s3-using-br.md
  zh/restore-from-gcs-using-br.md
  zh/restore-from-gcs.md
  zh/restore-from-pv-using-br.md
  zh/restore-from-s3.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/done, size/M

#1686 en,zh: add GKE instance type recommendation
  en/deploy-on-gcp-gke.md
  zh/deploy-on-gcp-gke.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1715 add redirects for deploy-tidb-operator.md
  en/deploy-tidb-operator.md
  zh/deploy-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/done, require-LGT1, size/XS

#1716 remove redirects
  en/deploy-tidb-operator.md
  zh/deploy-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/done, require-LGT1, size/XS

#1710 en,zh: use 1.2.7 rbac link for v1.2 docs
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-gcs.md
  en/backup-to-pv-using-br.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs-using-br.md
  en/restore-from-gcs.md
  en/restore-from-pv-using-br.md
  en/restore-from-s3.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-gcs.md
  zh/backup-to-pv-using-br.md
  zh/restore-from-aws-s3-using-br.md
  zh/restore-from-gcs-using-br.md
  zh/restore-from-gcs.md
  zh/restore-from-pv-using-br.md
  zh/restore-from-s3.md
Labels: status/can-merge, status/LGT1, translation/done, require-LGT1, size/M

#1720 zh: add more config description
  zh/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/doing, size/M, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1708 en,zh: add descrption about cluster domain
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
Labels: status/can-merge, status/LGT2, translation/done, size/S, needs-cherry-pick-release-1.3

#1718 zh: add FAQ about configUpdateStrategy
  zh/configure-a-tidb-cluster.md
  zh/faq.md
Labels: status/can-merge, status/LGT2, translation/doing, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1677 en,zh: Optimize doc about Lightning
  en/TOC.md
  en/backup-and-restore-using-helm-charts.md
  en/configure-backup.md
  en/notes-tidb-operator-v1.1.md
  en/restore-data-using-tidb-lightning.md
  en/tidb-cluster-chart-config.md
  zh/TOC.md
  zh/backup-and-restore-using-helm-charts.md
  zh/configure-backup.md
  zh/notes-tidb-operator-v1.1.md
  zh/restore-data-using-tidb-lightning.md
  zh/tidb-cluster-chart-config.md
Labels: status/can-merge, status/LGT2, translation/done, size/XXL, needs-cherry-pick-release-1.3

#1719 Correct path in doc about NFS restore
  en/restore-from-pv-using-br.md
  zh/restore-from-pv-using-br.md
Labels: status/can-merge, status/LGT2, translation/done, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1732 monitor: bump prometheus version to v2.27.1 and grafana to 7.5.11
  en/deploy-heterogeneous-tidb-cluster.md
  en/monitor-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/monitor-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, needs-cherry-pick-release-1.3

#1731 feat(monitor): update docs
  en/aggregate-multiple-cluster-monitor-data.md
  en/deploy-cluster-on-arm64.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/enable-monitor-dynamic-configuration.md
  en/enable-monitor-shards.md
  en/enable-tls-between-components.md
  en/monitor-a-tidb-cluster.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/deploy-cluster-on-arm64.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/enable-monitor-dynamic-configuration.md
  zh/enable-monitor-shards.md
  zh/enable-tls-between-components.md
  zh/monitor-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.3

#1692 en: optimize backup/restore overview
  en/TOC.md
  en/backup-restore-cr.md
  en/backup-restore-overview.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-gcs.md
  en/backup-to-pv-using-br.md
  en/backup-to-s3.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-tiflash.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs-using-br.md
  en/restore-from-gcs.md
  en/restore-from-pv-using-br.md
  en/restore-from-s3.md
  zh/backup-restore-cr.md
Labels: type/enhancement, status/can-merge, status/LGT2, translation/from-zh, size/XXL, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1736 Add desc abot discovery and update arch image
  en/architecture.md
  media/tidb-operator-overview-1.2.png
  zh/architecture.md
Labels: status/can-merge, status/LGT2, translation/done, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1733 add volume mount docs for ticdc
  en/configure-a-tidb-cluster.md
  en/deploy-ticdc.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-ticdc.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.3

#1725 en,zh: add doc about recreate TiKV Pod
  en/maintain-a-kubernetes-node.md
  zh/maintain-a-kubernetes-node.md
Labels: status/can-merge, status/LGT2, translation/done, size/XL, needs-cherry-pick-release-1.3

#1707 en,zh: add a tip for configure a TiKV Pod
  en/deploy-failures.md
  en/tidb-toolkit.md
  en/tips.md
  zh/tips.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1690 en,zh: optimize doc about local pv
  en/configure-storage-class.md
  zh/configure-storage-class.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/done, size/XXL, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1711 en,zh: add backup examples to backup using br docs
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-pv-using-br.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-pv-using-br.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/done, size/XXL, requires-version-specific-changes, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1691 en: update doc for canary upgrade
  en/canary-upgrade-tidb-operator.md
  en/upgrade-tidb-operator.md
Labels: type/enhancement, status/can-merge, status/LGT2, translation/from-zh, size/L, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1738 add all fields in crd to br docs
  zh/backup-restore-cr.md
Labels: status/can-merge, status/LGT2, translation/doing, size/M, needs-cherry-pick-release-1.3

#1761 en,zh: add release notes for v1.3.2
  en/TOC.md
  en/releases/release-1.3.1.md
  en/releases/release-1.3.2.md
  zh/TOC.md
  zh/releases/release-1.3.1.md
  zh/releases/release-1.3.2.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, needs-cherry-pick-release-1.3

#1762 en,zh: bump operator version to v1.3.2
  en/cheat-sheet.md
  en/deploy-cluster-on-arm64.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-cluster-on-arm64.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.3

#1757 Improve TLS docs
  zh/enable-tls-between-components.md
  zh/enable-tls-for-dm.md
  zh/enable-tls-for-mysql-client.md
Labels: status/can-merge, status/LGT2, translation/doing, size/S, needs-cherry-pick-release-1.3

#1490 Add docs about multi cluster prom monitoring
  media/pull-prom-federation.png
  media/pull-thanos-query.png
  media/push-thanos-receive.png
  zh/TOC.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-monitor-across-multiple-kubernetes.md
Labels: status/can-merge, status/LGT2, translation/doing, first-time-contributor, size/XL, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1770 en,zh: replace "master/manifest" to "v1.3.2/manifest" in URLs
  en/advanced-statefulset.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-gcs.md
  en/backup-to-pv-using-br.md
  en/backup-to-s3.md
  en/configure-storage-class.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/initialize-a-cluster.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs-using-br.md
  en/restore-from-gcs.md
  en/restore-from-pv-using-br.md
  en/restore-from-s3.md
  zh/advanced-statefulset.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-gcs.md
  zh/backup-to-pv-using-br.md
  zh/backup-to-s3.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/initialize-a-cluster.md
  zh/monitor-a-tidb-cluster.md
  zh/restore-from-aws-s3-using-br.md
  zh/restore-from-gcs-using-br.md
  zh/restore-from-gcs.md
  zh/restore-from-pv-using-br.md
  zh/restore-from-s3.md
Labels: status/can-merge, status/LGT1, translation/done, size/M
