Repository pingcap/docs-tidb-operator, pull requests merged in 2022-02, with the labels that each got.

#1580 en: add doc for migrate pd/tikv pod
  en/maintain-a-kubernetes-node.md
  zh/maintain-a-kubernetes-node.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/from-zh, size/XL, needs-cherry-pick-release-1.2, type/compatibility-or-feature-change

#1614 en: update scale tidb-binlog
  en/deploy-tidb-binlog.md
  zh/deploy-tidb-binlog.md
Labels: status/can-merge, status/LGT2, translation/from-zh, size/M, needs-cherry-pick-release-1.2

#1618 en: update steps for migrating TiKV Pod
  en/maintain-a-kubernetes-node.md
Labels: status/can-merge, status/LGT2, translation/from-zh, size/M, v1.3

#1620 en: update doc for auto failover
  en/use-auto-failover.md
Labels: status/can-merge, status/LGT2, translation/from-zh, size/M, v1.3

#1612 zh: update minikube default installation using docker
  zh/get-started.md
Labels: status/can-merge, status/LGT1, translation/from-en, require-LGT1, size/M, needs-cherry-pick-release-1.2

#1508 zh: optimize canary upgrade
  zh/canary-upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, translation/doing, size/L, needs-cherry-pick-release-1.2

#1605 en,zh: optimize docs for TiKV upgrade configuration
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/done, size/XS, v1.3

#1627 en,zh: Revert some change about upgrade
  en/upgrade-tidb-operator.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/done, size/M

#1628 .github: update ci for release-1.3 branch
  .github/exclude-links.txt
  .github/workflows/ci.yaml
  .github/workflows/link.yml
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/M

#1619 en: add doc for tidbmonitor shards
  en/TOC.md
  en/enable-monitor-shards.md
Labels: status/can-merge, status/LGT2, translation/from-zh, size/M, v1.3, type/compatibility-or-feature-change, needs-cherry-pick-release-1.3

#1477 en: fix typos and refine style
  en/benchmark-sysbench.md
  en/build-multi-aws-eks.md
  en/cheat-sheet.md
  en/configure-a-tidb-cluster.md
  en/configure-backup.md
  en/configure-tidb-binlog-drainer.md
  en/deploy-failures.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/initialize-a-cluster.md
  en/migrate-to-helm3.md
  en/monitor-a-tidb-cluster.md
  en/notes-tidb-operator-v1.1.md
  en/releases/release-0.3.1.md
  en/releases/release-1.0.0-beta.3.md
  en/releases/release-1.1.0-beta.2.md
  en/releases/release-1.1.0-rc.4.md
  en/releases/release-1.1.8.md
  en/releases/release-1.3.0-beta.1.md
  zh/build-multi-aws-eks.md
  zh/build-multi-gcp-gke.md
  zh/cheat-sheet.md
  zh/monitor-a-tidb-cluster.md
Labels: status/can-merge, status/LGT1, translation/no-need, type/bug-fix, require-LGT1, size/L, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1636 en,zh; bump tidb components and dm to v5.4.0
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-restore-overview.md
  en/configure-a-tidb-cluster.md
  en/deploy-cluster-on-arm64.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-dm.md
  en/deploy-tidb-enterprise-edition.md
  en/enable-tls-between-components.md
  en/enable-tls-for-dm.md
  en/enable-tls-for-mysql-client.md
  en/get-started.md
  en/monitor-a-tidb-cluster.md
  en/notes-tidb-operator-v1.1.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-restore-overview.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-cluster-on-arm64.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-dm.md
  zh/deploy-tidb-enterprise-edition.md
  zh/enable-monitor-shards.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-dm.md
  zh/enable-tls-for-mysql-client.md
  zh/get-started.md
  zh/monitor-a-tidb-cluster.md
  zh/notes-tidb-operator-v1.1.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-data-using-tidb-lightning.md
Labels: status/can-merge, status/LGT2, translation/done, size/XL, needs-cherry-pick-release-1.3

#1641 en,zh; add rolling update changes missed in v1.3.0-beta.1
  en/releases/release-1.3.0-beta.1.md
  zh/releases/release-1.3.0-beta.1.md
Labels: status/can-merge, status/LGT2, translation/done, size/XS, needs-cherry-pick-release-1.3

#1638 en,zh; bump tidb operator to v1.3.0
  en/cheat-sheet.md
  en/deploy-cluster-on-arm64.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-cluster-on-arm64.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/done, require-LGT1, size/L, needs-cherry-pick-release-1.3

#1640 zh: add what's new doc for v1.3
  zh/TOC.md
  zh/_index.md
  zh/upgrade-tidb-operator.md
  zh/whats-new-in-v1.1.md
  zh/whats-new-in-v1.2.md
  zh/whats-new-in-v1.3.md
Labels: status/can-merge, status/LGT2, translation/doing, size/L, needs-cherry-pick-release-1.3

#1637 en,zh: Add release notes for v1.3.0
  en/TOC.md
  en/releases/release-1.3.0.md
  zh/TOC.md
  zh/releases/release-1.3.0.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, needs-cherry-pick-release-1.3

#1633 update support versions
  en/_index.md
  en/tidb-operator-overview.md
  zh/_index.md
  zh/tidb-operator-overview.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, needs-cherry-pick-release-1.3

#1646 en: add whats new in v1.3
  en/TOC.md
  en/_index.md
  en/whats-new-in-v1.1.md
  en/whats-new-in-v1.2.md
  en/whats-new-in-v1.3.md
Labels: status/can-merge, status/LGT2, translation/from-zh, size/L, needs-cherry-pick-release-1.3

#1559 en, zh: refine docs: back up and restore data using BR
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs-using-br.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/restore-from-aws-s3-using-br.md
  zh/restore-from-gcs-using-br.md
Labels: status/can-merge, status/LGT2, translation/done, size/XXL, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1543 en, zh: refine docs: deploying TiFlash and heterogeneous clusters in Kubernetes
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-tiflash.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-tiflash.md
Labels: status/can-merge, status/LGT2, translation/doing, size/XXL, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1630 Add Amazon Linux 2 AMI recommendation.
  en/deploy-on-aws-eks.md
  zh/deploy-on-aws-eks.md
Labels: contribution, needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/done, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1660 en,zh: add missed change to v1.3.0-beta.1 change log
  en/releases/release-1.3.0-beta.1.md
  en/whats-new-in-v1.3.md
  zh/releases/release-1.3.0-beta.1.md
  zh/whats-new-in-v1.3.md
Labels: status/can-merge, status/LGT2, translation/done, size/S, type/compatibility-or-feature-change, needs-cherry-pick-release-1.3

#1664 en,zh; bump operator version to v1.2.7
  en/cheat-sheet.md
  en/deploy-cluster-on-arm64.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-cluster-on-arm64.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/done, require-LGT1, size/L

#1661 en,zh; Add release notes for v1.2.7
  en/TOC.md
  en/releases/release-1.2.7.md
  zh/TOC.md
  zh/releases/release-1.2.7.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1665 en,zh; bump operator version to v1.1.15
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/done, require-LGT1, size/XL

#1658 en,zh; bump tidb components to v5.0.6
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/backup-restore-overview.md
  en/configure-a-tidb-cluster.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-enterprise-edition.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/get-started.md
  en/monitor-a-tidb-cluster.md
  en/notes-tidb-operator-v1.1.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-data-using-tidb-lightning.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/backup-restore-overview.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-enterprise-edition.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
  zh/get-started.md
  zh/monitor-a-tidb-cluster.md
  zh/notes-tidb-operator-v1.1.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-data-using-tidb-lightning.md
  zh/upgrade-a-tidb-cluster.md
Labels: status/can-merge, status/LGT1, translation/done, size/XL

#1662 en,zh; add release notes for v1.1.15
  en/TOC.md
  en/releases/release-1.1.15.md
  zh/TOC.md
  zh/releases/release-1.1.15.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/done, size/S, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1672 en,zh: optimize changelog about 1.3.0
  en/releases/release-1.3.0-beta.1.md
  en/whats-new-in-v1.3.md
  zh/releases/release-1.3.0-beta.1.md
  zh/whats-new-in-v1.3.md
Labels: status/can-merge, status/LGT2, translation/done, size/XS, needs-cherry-pick-release-1.3

#1657 en,zh: optmize doc about deploy tidb cluster across kubernetes
  en/build-multi-aws-eks.md
  en/build-multi-gcp-gke.md
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/build-multi-aws-eks.md
  zh/build-multi-gcp-gke.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
Labels: status/can-merge, status/LGT2, translation/done, size/XXL, needs-cherry-pick-release-1.3

#1678 en,zh: update tidb & operator version choice
  en/_index.md
  en/tidb-operator-overview.md
  zh/_index.md
  zh/tidb-operator-overview.md
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/done, require-LGT1, size/M, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1685 en, zh: update description for the alpha features
  en/TOC.md
  en/advanced-statefulset.md
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  en/enable-admission-webhook.md
  en/enable-tidb-cluster-auto-scaling.md
  zh/TOC.md
  zh/advanced-statefulset.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/enable-admission-webhook.md
  zh/enable-tidb-cluster-auto-scaling.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/done, size/XL, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1693 en,zh: Bump operator to v1.3.1
  en/cheat-sheet.md
  en/deploy-cluster-on-arm64.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-cluster-on-arm64.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.3

#1694 en, zh: add release notes for v1.3.1
  en/TOC.md
  en/releases/release-1.3.0-beta.1.md
  en/releases/release-1.3.0.md
  en/releases/release-1.3.1.md
  en/whats-new-in-v1.3.md
  zh/TOC.md
  zh/releases/release-1.3.0-beta.1.md
  zh/releases/release-1.3.0.md
  zh/releases/release-1.3.1.md
  zh/whats-new-in-v1.3.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.3

#1535 en, zh: update index and TOC organization
  en/TOC.md
  en/_index.md
  en/scale-a-tidb-cluster.md
  zh/TOC.md
  zh/_index.md
  zh/scale-a-tidb-cluster.md
Labels: status/can-merge, status/LGT1, translation/done, require-LGT1, size/M, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1625 CI: add vale linter
  .github/workflows/vale.yaml
  .vale.ini
  styles/PingCAP/AMPM.yml
  styles/PingCAP/EmDash.yml
  styles/PingCAP/EnDash.yml
  styles/PingCAP/Exclamation.yml
  styles/PingCAP/Gender.yml
  styles/PingCAP/GenderBias.yml
  styles/PingCAP/HeadingPunctuation.yml
  styles/PingCAP/Latin.yml
  styles/PingCAP/LyHyphens.yml
  styles/PingCAP/OptionalPlurals.yml
  styles/PingCAP/Ordinal.yml
  styles/PingCAP/Slang.yml
  styles/PingCAP/Spacing.yml
  styles/PingCAP/Units.yml
  styles/Vocab/PingCAP/accept.txt
  styles/Vocab/PingCAP/reject.txt
  styles/vocab.txt
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1695 en,zh: add s3 fields description for br doc
  en/backup-restore-overview.md
  zh/backup-restore-cr.md
Labels: status/can-merge, status/LGT2, translation/done, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3
