Repository pingcap/docs-tidb-operator, pull requests merged in 2022-04, with the labels that each got.

#1776 delete deploy-tidb-enterprise-edition.md
  en/TOC.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-enterprise-edition.md
  zh/TOC.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-enterprise-edition.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/no-need, version-specific-changes-required, require-LGT1, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1780 en, zh: delete "enterprise" content from docs
  en/configure-a-tidb-cluster.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-ticdc.md
  en/deploy-tidb-binlog.md
  en/deploy-tiflash.md
  en/upgrade-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-ticdc.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tiflash.md
  zh/upgrade-a-tidb-cluster.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/no-need, size/L, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1767 Update storage class description for GKE deploy
  en/deploy-on-gcp-gke.md
  zh/deploy-on-gcp-gke.md
Labels: contribution, needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/done, first-time-contributor, size/S, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1792 ci: update ci path
  .github/workflows/ci.yaml
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/S, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1800 ci: Run jobs in parallel with GitHub Actions
  .github/workflows/ci.yaml
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/no-need, require-LGT1, first-time-contributor, size/L, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1806 Actions: Remove rebase.yml
  .github/workflows/rebase.yml
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/no-need, type/bug-fix, require-LGT1, size/S, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3
