Repository pingcap/docs-tidb-operator, pull requests merged in 2022-08, with the labels that each got.

#1955 bump operator to v1.3.7
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, translation/done, size/L

#1954 release note for 1.3.7
  en/TOC.md
  en/releases/release-1.3.7.md
  zh/TOC.md
  zh/releases/release-1.3.7.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, needs-cherry-pick-release-1.3

#1958 Fix typo
  zh/restore-data-using-tidb-lightning.md
Labels: status/can-merge, status/LGT1, translation/no-need, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-1.3

#1962 en,zh: Bump tidb components to v6.1.0
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-restore-cr.md
  en/configure-a-tidb-cluster.md
  en/deploy-cluster-on-arm64.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  en/deploy-tidb-dm.md
  en/enable-tls-between-components.md
  en/enable-tls-for-dm.md
  en/enable-tls-for-mysql-client.md
  en/get-started.md
  en/monitor-a-tidb-cluster.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-dm.md
  zh/deploy-tidb-monitor-across-multiple-kubernetes.md
  zh/enable-monitor-shards.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-dm.md
  zh/enable-tls-for-mysql-client.md
  zh/get-started.md
  zh/monitor-a-tidb-cluster.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/done, size/XL, needs-cherry-pick-release-1.3

#1960 Update dispatch.yml
  .github/workflows/dispatch.yml
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/no-need, first-time-contributor, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1970 operator: updated video link
  en/get-started.md
Labels: type/enhancement, status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS, needs-cherry-pick-release-1.3

#1974 ci: add prevent deletion
  .github/workflows/prevent-deletion.yaml
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/M, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#1979 CI: fix prevent-deletion
  .github/workflows/prevent-deletion.yaml
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/S
