Repository pingcap/docs-tidb-operator, pull requests merged in 2022-01, with the labels that each got.

#1516 en, zh: add azure in overview
  en/tidb-operator-overview.md
  zh/tidb-operator-overview.md
Labels: status/can-merge, status/LGT1, translation/done, require-LGT1, size/S, needs-cherry-pick-release-1.2

#1460 zh: Add doc about deploy tidb across GKE and EKS
  zh/TOC.md
  zh/build-multi-aws-eks.md
  zh/build-multi-gcp-gke.md
  zh/deploy-on-aws-eks.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
Labels: type/enhancement, status/can-merge, status/LGT2, translation/doing, size/XXL, needs-cherry-pick-release-1.2

#1573 en,zh: add release notes for v1.2.6
  en/TOC.md
  en/releases/release-1.2.6.md
  zh/TOC.md
  zh/releases/release-1.2.6.md
Labels: status/can-merge, status/LGT2, translation/done, first-time-contributor, size/S, needs-cherry-pick-release-1.2

#1576 en,zh: Bump Operator version to v1.2.6
  en/cheat-sheet.md
  en/deploy-cluster-on-arm64.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-cluster-on-arm64.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.2

#1521 zh: update migrate TiKV Pod
  zh/maintain-a-kubernetes-node.md
Labels: status/can-merge, status/LGT2, missing-translation-status, size/M, v1.3

#1565 zh,en;replace `kubectl edit` to `kubectl patch`
  en/backup-restore-overview.md
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tiflash.md
  en/enable-tls-between-components.md
  en/grant-permissions-to-remote-storage.md
  en/pause-sync-of-tidb-cluster.md
  en/pd-recover.md
  en/use-auto-failover.md
  zh/backup-restore-overview.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tiflash.md
  zh/enable-tls-between-components.md
  zh/grant-permissions-to-remote-storage.md
  zh/pause-sync-of-tidb-cluster.md
  zh/pd-recover.md
  zh/use-auto-failover.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.2

#1502 en, zh: optimize upgrade-a-tidb-cluster
  en/TOC.md
  en/modify-tidb-configuration.md
  en/tidb-operator-overview.md
  en/upgrade-a-tidb-cluster.md
  zh/TOC.md
  zh/modify-tidb-configuration.md
  zh/tidb-operator-overview.md
  zh/upgrade-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/done, size/XL, needs-cherry-pick-release-1.2

#1581 zh: Add description about continue profile
  media/dashboard-conprof-start.png
  zh/access-dashboard.md
Labels: status/can-merge, status/LGT2, translation/doing, size/M, sig/diagnosis

#1572 zh: update scale tidb-binlog
  zh/deploy-tidb-binlog.md
Labels: status/can-merge, status/LGT2, translation/doing, size/M, needs-cherry-pick-release-1.2

#1585 zh: fix the description about continue profile
  zh/access-dashboard.md
Labels: status/can-merge, status/LGT2, translation/doing, size/XS, sig/diagnosis

#1583 update dm deploy
  en/deploy-tidb-dm.md
  zh/deploy-tidb-dm.md
Labels: status/can-merge, status/LGT2, translation/done, size/S

#1544 minikube default installation using Docker can be used for TiDB
  en/get-started.md
Labels: status/can-merge, status/LGT2, translation/doing, first-time-contributor, size/M, needs-cherry-pick-release-1.2

#1589 en,zh: Add release notes for v1.3.0-beta.1
  en/TOC.md
  en/releases/release-1.3.0-beta.1.md
  zh/TOC.md
  zh/releases/release-1.3.0-beta.1.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, v1.3

#1590 en,zh: Bump Operator version to v1.3.0-beta.1
  en/cheat-sheet.md
  en/deploy-cluster-on-arm64.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-cluster-on-arm64.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/done, require-LGT1, size/L

#1591 zh: use internal link
  zh/releases/release-1.3.0-beta.1.md
Labels: status/can-merge, status/LGT1, translation/doing, require-LGT1, size/XS

#1551 zh: add replace-nodes-for-localdisk-tidb.md
  zh/TOC.md
  zh/replace-nodes-for-local-disk.md
Labels: status/can-merge, status/LGT2, translation/doing, size/L, needs-cherry-pick-release-1.2

#1595 zh: Fix ngm example
  zh/access-dashboard.md
Labels: status/can-merge, status/LGT2, translation/doing, type/bug-fix, size/XS

#1596 zh: remove extra spaces
  zh/replace-nodes-for-local-disk.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS, needs-cherry-pick-release-1.2

#1602 en,zh: fix broken links caused by logstash
  en/logs-collection.md
  zh/logs-collection.md
Labels: status/can-merge, status/LGT1, translation/done, type/bug-fix, require-LGT1, size/XS

#1597 en: Add description about continue profile
  en/access-dashboard.md
Labels: status/can-merge, status/LGT2, translation/from-zh, first-time-contributor, size/M, sig/diagnosis

#1594 zh: update auto failover recover
  zh/use-auto-failover.md
Labels: status/can-merge, status/LGT2, translation/doing, size/M

#1608 en, zh: update the upgrade doc
  en/upgrade-a-tidb-cluster.md
  zh/upgrade-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/done, size/XS, needs-cherry-pick-release-1.2

#1599 en,zh: add note for upgrade cmd after v1.3.0
  en/upgrade-tidb-operator.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, translation/done, size/L

#1613 en: add continous profiling link to release notes
  en/releases/release-1.3.0-beta.1.md
Labels: status/can-merge, status/LGT1, translation/from-zh, require-LGT1, size/XS, v1.3

#1611 en, zh: Add pd nslookup issue
  en/deploy-failures.md
  zh/deploy-failures.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, v1.3

#1610 .github: add v1.3 to pr template
  .github/pull_request_template.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/S
