Repository pingcap/docs-tidb-operator, pull requests merged in 2022-12, with the labels that each got.

#2109 bump v1.4.0-beta.2 to v1.4.0-beta.3
  en/TOC.md
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/releases/release-1.4.0-beta.3.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/TOC.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/releases/release-1.4.0-beta.3.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, translation/done, first-time-contributor, size/XL, needs-cherry-pick-release-1.4

#2086 en,zh: add descriptions about start script configuration
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, needs-cherry-pick-release-1.4

#2105 [zh] Docs for seperated tidb-dashboard deployment
  zh/access-dashboard.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/get-started.md
Labels: status/can-merge, status/LGT2, translation/done, first-time-contributor, size/L, tidb/v6.5

#2106 en: docs for separated tidb-dashboard deployment
  en/access-dashboard.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/get-started.md
Labels: status/can-merge, status/LGT1, status/LGT2, translation/from-zh, size/L, v1.4, needs-cherry-pick-release-1.4, tidb/v6.5

#1851 fix note for lb in deploy-on-azure-aks.md
  en/deploy-on-azure-aks.md
  zh/deploy-on-azure-aks.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/done, size/S, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3

#2117 feat: update permission for ebs backup and restore
  en/grant-permissions-to-remote-storage.md
  zh/grant-permissions-to-remote-storage.md
Labels: status/can-merge, status/LGT2, translation/done, size/S, needs-cherry-pick-release-1.4

#2107 fix missing \ in create cluster command
  en/build-multi-gcp-gke.md
Labels: contribution, status/can-merge, status/LGT2, translation/no-need, type/bug-fix, first-time-contributor, size/XS, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#1963 en,zh: Optimize the doc about arm64 deployment
  en/deploy-cluster-on-arm64.md
  zh/deploy-cluster-on-arm64.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2108 zh: snapshot-volume backup and restore
  media/volume-snapshot-backup-impact.jpg
  media/volume-snapshot-backup-perf.png
  media/volume-snapshot-backup-restore-overview.png
  media/volume-snapshot-restore-perf.png
  zh/TOC.md
  zh/backup-restore-faq.md
  zh/backup-restore-snapshot-perf.md
  zh/restore-from-aws-s3-by-snapshot.md
Labels: status/can-merge, status/LGT2, translation/done, size/XL, v1.4, needs-cherry-pick-release-1.4

#2131 en: snapshot-volume backup and restore
  en/TOC.md
  en/backup-restore-faq.md
  en/backup-restore-snapshot-perf.md
  en/restore-from-aws-s3-by-snapshot.md
Labels: status/can-merge, status/LGT1, status/LGT2, translation/from-zh, size/XL, needs-cherry-pick-release-1.4

#2136 Fix separate dashboard
  en/access-dashboard.md
  zh/access-dashboard.md
Labels: status/can-merge, status/LGT1, status/LGT2, translation/done, type/bug-fix, size/XS, needs-cherry-pick-release-1.4

#2125 add-tiflash-in-upgrade-doc
  en/upgrade-a-tidb-cluster.md
  zh/upgrade-a-tidb-cluster.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/done, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2144 en,zh: add v1.4 GA release notes and whats new
  en/TOC.md
  en/releases/release-1.4.0.md
  en/tidb-operator-overview.md
  en/whats-new-in-v1.3.md
  en/whats-new-in-v1.4.md
  zh/TOC.md
  zh/releases/release-1.4.0.md
  zh/tidb-operator-overview.md
  zh/whats-new-in-v1.3.md
  zh/whats-new-in-v1.4.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, v1.4, needs-cherry-pick-release-1.4

#2148 en,zh: Bump tidb components to v6.5.0
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-restore-cr.md
  en/configure-a-tidb-cluster.md
  en/deploy-cluster-on-arm64.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  en/deploy-tidb-dm.md
  en/deploy-tidb-monitor-across-multiple-kubernetes.md
  en/enable-tls-between-components.md
  en/enable-tls-for-dm.md
  en/enable-tls-for-mysql-client.md
  en/get-started.md
  en/monitor-a-tidb-cluster.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-dm.md
  zh/deploy-tidb-monitor-across-multiple-kubernetes.md
  zh/enable-monitor-shards.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-dm.md
  zh/enable-tls-for-mysql-client.md
  zh/get-started.md
  zh/monitor-a-tidb-cluster.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
Labels: status/can-merge, status/LGT1, translation/done, require-LGT1, size/XL, v1.4, needs-cherry-pick-release-1.4

#2149 bump operator to v1.4.0 for release-1.4
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-to-s3.md
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-to-s3.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/done, size/XL, type/cherry-pick-for-release-1.4

#2147 en,zh: bump operator to v1.4.0
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, translation/done, size/L

#2154 trigger pdf on 1.3
  en/_index.md
Labels: status/can-merge, status/LGT1, translation/no-need, size/XS

#2151 zh,en: update tidb-operator upgrade
  en/upgrade-tidb-operator.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, translation/done, size/S, v1.4, needs-cherry-pick-release-1.4

#2157 release-1.2: update CRD link to v1.2
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-to-s3.md
  en/configure-storage-class.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/enable-tidb-cluster-auto-scaling.md
  en/get-started.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-to-s3.md
  zh/configure-storage-class.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/enable-tidb-cluster-auto-scaling.md
  zh/get-started.md
Labels: status/can-merge, status/LGT1, translation/done, size/L

#2156 release-1.3: update CRD link to v1.3
  en/aggregate-multiple-cluster-monitor-data.md
  en/configure-storage-class.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/enable-tidb-cluster-auto-scaling.md
  en/get-started.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/configure-storage-class.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/enable-tidb-cluster-auto-scaling.md
  zh/get-started.md
Labels: status/can-merge, status/LGT1, missing-translation-status, size/M

#2158 release-1.1: update CRD link to v1.1
  en/advanced-statefulset.md
  en/backup-to-s3.md
  en/configure-storage-class.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/enable-tidb-cluster-auto-scaling.md
  en/get-started.md
  zh/advanced-statefulset.md
  zh/backup-to-s3.md
  zh/configure-storage-class.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/enable-tidb-cluster-auto-scaling.md
  zh/get-started.md
Labels: status/can-merge, status/LGT1, missing-translation-status, size/M

#2159 zh,en: fix 1.4.0 release notes format
  en/releases/release-1.4.0.md
  zh/releases/release-1.4.0.md
Labels: status/can-merge, status/LGT2, translation/done, size/XS
