Repository pingcap/docs-tidb-operator, pull requests merged in 2023-11, with the labels that each got.

#2464 Clarify use of topologySpreadConstraints
  zh/configure-a-tidb-cluster.md
Labels: translation/from-en, size/XS, needs-cherry-pick-release-1.5, lgtm, approved

#2461 deprecated-tikv-importer-in-operator
  en/restore-data-using-tidb-lightning.md
  en/tidb-toolkit.md
  zh/restore-data-using-tidb-lightning.md
  zh/tidb-toolkit.md
Labels: contribution, translation/done, first-time-contributor, size/S, needs-cherry-pick-release-1.5, lgtm, approved

#2470 zh, en: remove tkctl
  en/TOC.md
  en/maintain-a-kubernetes-node.md
  en/network-issues.md
  en/tidb-operator-overview.md
  en/use-tkctl.md
  zh/TOC.md
  zh/network-issues.md
  zh/tidb-operator-overview.md
  zh/use-tkctl.md
Labels: translation/done, size/XXL, needs-cherry-pick-release-1.5, lgtm, approved, needs-1-more-lgtm
