Repository pingcap/docs-tidb-operator, pull requests merged in 2023-01, with the labels that each got.

#2162 Bump version v1.4
  en/_index.md
  zh/_index.md
Labels: status/can-merge, status/LGT1, translation/done, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-1.4

#2166 fix: wrong crd fields under br in crd example
  en/restore-from-aws-s3-by-snapshot.md
  zh/restore-from-aws-s3-by-snapshot.md
Labels: status/can-merge, status/LGT1, status/LGT2, translation/done, size/S, needs-cherry-pick-release-1.4

#2146 zh: add aws and gcp pitr docs
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-azblob-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/restore-from-aws-s3-using-br.md
  zh/restore-from-azblob-using-br.md
  zh/restore-from-gcs-using-br.md
Labels: status/can-merge, status/LGT2, translation/doing, size/XXL, v1.4, needs-cherry-pick-release-1.4

#2130 add-port-forward-in-clinic-doc
  en/clinic-user-guide.md
  zh/clinic-user-guide.md
Labels: status/can-merge, status/LGT2, translation/done, size/XS, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2163 fix-annotate-command
  en/grant-permissions-to-remote-storage.md
  en/restore-data-using-tidb-lightning.md
  zh/grant-permissions-to-remote-storage.md
  zh/restore-data-using-tidb-lightning.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/done, size/S, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2169 refactor the volume-snapshot restore performance description
  zh/backup-restore-snapshot-perf.md
  zh/grant-permissions-to-remote-storage.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, needs-cherry-pick-release-1.4

#2176 en: refactor the volume-snapshot restore performance description
  en/backup-restore-snapshot-perf.md
  en/grant-permissions-to-remote-storage.md
Labels: status/can-merge, status/LGT1, status/LGT2, translation/from-zh, size/M, needs-cherry-pick-release-1.4

#2177 en,zh: add v1.4.1 release notes
  en/TOC.md
  en/releases/release-1.4.1.md
  zh/TOC.md
  zh/releases/release-1.4.1.md
Labels: status/can-merge, status/LGT2, translation/done, size/M, needs-cherry-pick-release-1.4

#2178 bump operator to v1.4.1 for master
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, translation/done, size/L

#2179 bump operator to v1.4.1 for release-1.4
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-to-s3.md
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-to-s3.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/done, size/XL

#2175 en: add aws and gcp pitr docs
  en/backup-to-aws-s3-using-br.md
  en/backup-to-azblob-using-br.md
  en/backup-to-gcs-using-br.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-azblob-using-br.md
  en/restore-from-gcs-using-br.md
Labels: status/can-merge, status/LGT2, translation/from-zh, size/XXL, needs-cherry-pick-release-1.4

#2196 en/configure-a-tidb-cluster.md: Fix formatting
  en/configure-a-tidb-cluster.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4
