Repository pingcap/docs-tidb-operator, pull requests merged in 2023-03, with the labels that each got.

#2238 en,zh: fix dead external links
  en/clinic-user-guide.md
  en/deploy-tidb-operator.md
  zh/clinic-user-guide.md
  zh/deploy-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/no-need, type/bug-fix, require-LGT1, size/S, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, area/clinic, needs-cherry-pick-release-1.4

#2195 improve pd recover step
  en/pd-recover.md
  zh/pd-recover.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/M, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2215 en,zh: fix command in multi aws eks
  en/build-multi-aws-eks.md
  zh/build-multi-aws-eks.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/S, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2189 fix-upgrade-tidb-operator
  en/upgrade-tidb-operator.md
  zh/upgrade-tidb-operator.md
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2252 en: fix a typo in upgrading steps
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2259 en,zh: Add doc for IPv6
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/no-need, size/S, needs-cherry-pick-release-1.4

#2261 en,zh: release note for 1.4.4
  en/TOC.md
  en/releases/release-1.4.4.md
  zh/TOC.md
  zh/releases/release-1.4.4.md
Labels: status/can-merge, status/LGT2, translation/no-need, size/M, needs-cherry-pick-release-1.4

#2263 en,zh: bump operator to v1.4.4 for release-1.4
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-to-s3.md
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-to-s3.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/no-need, size/XL

#2264 en,zh: bump operator to v1.4.4
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/L

#2236 br: zh: add docs about `backoffRetryPolicy` and auto truncate log backup by backupschedule
  zh/backup-restore-cr.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-azblob-using-br.md
  zh/backup-to-gcs-using-br.md
Labels: status/can-merge, status/LGT2, translation/done, size/XL, area/br, needs-cherry-pick-release-1.4

#2258 en: add doc for Backoff retry policy and auto truncate log backup by backupschedule
  en/backup-restore-cr.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-azblob-using-br.md
  en/backup-to-gcs-using-br.md
Labels: status/can-merge, status/LGT2, translation/from-zh, size/XL, area/br, needs-cherry-pick-release-1.4

#2268 update the copyright date to 2023
  templates/copyright.tex
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS

#2275 fix the typo in copyright.tex
  templates/copyright.tex
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2283 Typo in the kubectl edit command
  en/deploy-tiflash.md
Labels: contribution, needs-cherry-pick-release-1.1, status/can-merge, status/LGT2, translation/no-need, first-time-contributor, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4
