Repository pingcap/docs-tidb-operator, pull requests merged in 2023-02, with the labels that each got.

#2202 bump operator to v1.4.2
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, translation/no-need, size/L

#2203 Bump operator to v1.4.2 for release 1.4
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-to-s3.md
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-to-s3.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/no-need, size/XL

#2201 en,zh: release note for 1.4.2
  en/TOC.md
  en/releases/release-1.4.2.md
  zh/TOC.md
  zh/releases/release-1.4.2.md
Labels: status/can-merge, status/LGT2, translation/done, size/S, needs-cherry-pick-release-1.4

#2204 chore: stop uploading media and pdf to aws
  .github/workflows/media.yml
  scripts/upload.py
Labels: needs-cherry-pick-release-1.1, status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/S, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2214 *: disable telemetry by default
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/upgrade-a-tidb-cluster.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/upgrade-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/no-need, size/S

#2212 br: add a upgrade issue for ebs volume-snapshot backup
  en/backup-restore-faq.md
  en/backup-to-aws-s3-by-snapshot.md
  zh/backup-restore-faq.md
  zh/backup-to-aws-s3-by-snapshot.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, area/br, needs-cherry-pick-release-1.4

#2219 add-en-suspend-tidb-cluster
  en/suspend-tidb-cluster.md
  zh/suspend-tidb-cluster.md
Labels: status/can-merge, status/LGT1, translation/from-zh, require-LGT1, size/L, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2226 en,zh: bump operator to v1.4.3
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, translation/no-need, size/L

#2227 en,zh: bump operator to v1.4.3 for release-1.4
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-to-s3.md
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-to-s3.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/no-need, size/XL

#2228 en,zh: release note for 1.4.3
  en/TOC.md
  en/releases/release-1.4.3.md
  zh/TOC.md
  zh/releases/release-1.4.3.md
Labels: status/can-merge, status/LGT2, translation/no-need, size/M, needs-cherry-pick-release-1.4

#2231 en,zh: release note for 1.3.10
  en/TOC.md
  en/releases/release-1.3.10.md
  zh/TOC.md
  zh/releases/release-1.3.10.md
Labels: status/can-merge, status/LGT2, missing-translation-status, size/S, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2230 en,zh: bump operator version to v1.3.10
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-gcs.md
  en/backup-to-pv-using-br.md
  en/backup-to-s3.md
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/enable-tidb-cluster-auto-scaling.md
  en/get-started.md
  en/initialize-a-cluster.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs-using-br.md
  en/restore-from-gcs.md
  en/restore-from-pv-using-br.md
  en/restore-from-s3.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-gcs.md
  zh/backup-to-pv-using-br.md
  zh/backup-to-s3.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/enable-tidb-cluster-auto-scaling.md
  zh/get-started.md
  zh/initialize-a-cluster.md
  zh/monitor-a-tidb-cluster.md
  zh/restore-from-aws-s3-using-br.md
  zh/restore-from-gcs-using-br.md
  zh/restore-from-gcs.md
  zh/restore-from-pv-using-br.md
  zh/restore-from-s3.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT1, translation/no-need, size/XL

#2225 zh/en: add br notes to remind user of KMS TiKV encryption at rest
  en/backup-to-aws-s3-by-snapshot.md
  en/restore-from-aws-s3-by-snapshot.md
  zh/backup-to-aws-s3-by-snapshot.md
  zh/restore-from-aws-s3-by-snapshot.md
Labels: type/enhancement, status/can-merge, status/LGT2, translation/done, size/S, area/br, needs-cherry-pick-release-1.4
