Repository pingcap/docs-tidb-operator, pull requests merged in 2023-06, with the labels that each got.

#2367 en,zh: Bump tidb components to v7.1.0
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-restore-cr.md
  en/backup-restore-faq.md
  en/backup-to-aws-s3-by-snapshot.md
  en/configure-a-tidb-cluster.md
  en/deploy-cluster-on-arm64.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  en/deploy-tidb-dm.md
  en/deploy-tidb-monitor-across-multiple-kubernetes.md
  en/enable-tls-between-components.md
  en/enable-tls-for-dm.md
  en/enable-tls-for-mysql-client.md
  en/get-started.md
  en/monitor-a-tidb-cluster.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-from-aws-s3-by-snapshot.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-restore-faq.md
  zh/backup-to-aws-s3-by-snapshot.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-dm.md
  zh/deploy-tidb-monitor-across-multiple-kubernetes.md
  zh/enable-monitor-shards.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-dm.md
  zh/enable-tls-for-mysql-client.md
  zh/get-started.md
  zh/monitor-a-tidb-cluster.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-from-aws-s3-by-snapshot.md
Labels: status/can-merge, status/LGT2, translation/done, size/XL, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5

#2370 *: unify terms
  en/_index.md
  en/clinic-user-guide.md
  en/tidb-operator-overview.md
  zh/_index.md
  zh/tidb-operator-overview.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/S, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5

#2388 fix table header for tidb/operator versions
  zh/_index.md
  zh/tidb-operator-overview.md
Labels: translation/no-need, size/XS, lgtm, approved, needs-1-more-lgtm

#2389 en,zh: use variable to indicate clinic version
  en/clinic-user-guide.md
  zh/clinic-user-guide.md
Labels: translation/no-need, size/M, lgtm, approved, needs-1-more-lgtm

#2379 en,zh: release note for 1.4.5
  en/TOC.md
  en/releases/release-1.4.5.md
  zh/TOC.md
  zh/releases/release-1.4.5.md
Labels: translation/done, size/M, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved, needs-1-more-lgtm

#2393 en,zh: bump operator to v1.4.5 for release-1.4
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-to-s3.md
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-to-s3.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: translation/no-need, size/XL, lgtm, approved, needs-1-more-lgtm
