Repository pingcap/docs-tidb-operator, pull requests merged in 2023-04, with the labels that each got.

#2216 add-note-for-aws-gp2
  en/deploy-on-aws-eks.md
  zh/deploy-on-aws-eks.md
Labels: status/can-merge, status/LGT2, translation/no-need, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2292 remove dispatching to website-docs
  .github/workflows/dispatch.yml
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2298 update the deprecated set-output command
  .github/pull_request_template.md
  .github/workflows/dispatch.yml
  .github/workflows/link.yml
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2306 *: wrap links in backticks
  en/access-dashboard.md
  en/get-started.md
  zh/access-dashboard.md
  zh/get-started.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/S, needs-cherry-pick-release-1.4

#2311 ci: update specified actions to the latest
  .github/workflows/link.yml
  .github/workflows/media.yml
  .github/workflows/vale.yaml
Labels: type/enhancement, status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2302 en,zh: release notes for 1.5.0-beta.1
  en/TOC.md
  en/releases/release-1.5.0-beta.1.md
  zh/TOC.md
  zh/releases/release-1.5.0-beta.1.md
Labels: status/can-merge, status/LGT2, translation/no-need, size/L, needs-cherry-pick-release-1.5, v1.5

#2303 en,zh: bump operator to v1.5.0-beta.1
  en/cheat-sheet.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: status/can-merge, status/LGT2, translation/no-need, size/L, needs-cherry-pick-release-1.5, v1.5

#2304 *: update license to CC BY-SA 3.0
  .github/pull_request_template.md
  LICENSE
  README.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XXL, needs-cherry-pick-release-1.5, v1.5

#2322 *: fix toc for 1.5
  en/TOC.md
  en/whats-new-in-v1.4.md
  zh/TOC.md
  zh/whats-new-in-v1.4.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/M, needs-cherry-pick-release-1.5

#2327 fix tls link
  zh/enable-tls-for-mysql-client.md
Labels: status/can-merge, status/LGT1, translation/no-need, require-LGT1, size/XS, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5
