Repository pingcap/docs-tidb-operator, pull requests merged in 2023-05, with the labels that each got.

#2256 Improve pd recover
  en/pd-recover.md
  zh/pd-recover.md
Labels: status/can-merge, status/LGT2, translation/no-need, size/XL, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5

#2339 fix typo in deploy-heterogeneous-tidb-cluster
  en/deploy-heterogeneous-tidb-cluster.md
Labels: status/can-merge, status/LGT1, translation/no-need, type/bug-fix, require-LGT1, size/XS, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5

#2342 br: change the permission for external storage when do restore
  en/restore-from-azblob-using-br.md
  zh/restore-from-azblob-using-br.md
Labels: status/can-merge, status/LGT2, translation/no-need, size/XS, needs-cherry-pick-release-1.5

#2344 *: fix 1.4 release notes
  en/releases/release-1.4.0.md
  zh/releases/release-1.4.0.md
Labels: status/can-merge, status/LGT2, translation/no-need, size/XS, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5

#2348 add compatibility notes in upgrade doc
  en/upgrade-a-tidb-cluster.md
  zh/upgrade-a-tidb-cluster.md
Labels: status/can-merge, status/LGT2, translation/done, size/S, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5

#2347 fix-HostNetwork-link
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: status/can-merge, status/LGT1, translation/done, require-LGT1, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5

#2193 en: improve heterog naming convention
  en/deploy-heterogeneous-tidb-cluster.md
  en/get-started.md
  zh/get-started.md
Labels: status/can-merge, status/LGT1, translation/from-en, require-LGT1, size/S, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4

#2297 chore: migrate to new prow reviewing
  OWNERS
Labels: status/can-merge, status/LGT2, translation/no-need, first-time-contributor, size/M, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5

#2365 fix ticdc docs
  en/deploy-ticdc.md
  zh/deploy-ticdc.md
Labels: status/can-merge, status/LGT2, translation/done, size/S, needs-cherry-pick-release-1.5

#2368 en, zh: update GCP name to Google Cloud
  en/TOC.md
  en/_index.md
  en/access-tidb.md
  en/backup-restore-cr.md
  en/benchmark-sysbench.md
  en/build-multi-gcp-gke.md
  en/configure-a-tidb-cluster.md
  en/configure-storage-class.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/grant-permissions-to-remote-storage.md
  en/replace-nodes-for-cloud-disk.md
  en/tidb-operator-overview.md
  zh/TOC.md
  zh/_index.md
  zh/access-tidb.md
  zh/backup-restore-cr.md
  zh/benchmark-sysbench.md
  zh/build-multi-gcp-gke.md
  zh/configure-a-tidb-cluster.md
  zh/configure-storage-class.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/grant-permissions-to-remote-storage.md
  zh/replace-nodes-for-cloud-disk.md
  zh/tidb-operator-overview.md
Labels: status/can-merge, status/LGT2, translation/done, size/L, needs-cherry-pick-release-1.5
