Repository pingcap/docs-tidb-operator, pull requests merged in 2023-07, with the labels that each got.

#2399 fix the configuration format in multiple disks mounting
  en/configure-a-tidb-cluster.md
  zh/configure-a-tidb-cluster.md
Labels: translation/done, type/bug-fix, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved, needs-1-more-lgtm

#2396 en: optimize 2 docs
  en/configure-storage-class.md
  en/get-started.md
Labels: translation/doing, size/XL, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved, needs-1-more-lgtm

#2407 Fix typo
  en/deploy-tidb-monitor-across-multiple-kubernetes.md
  zh/deploy-tidb-monitor-across-multiple-kubernetes.md
Labels: contribution, translation/no-need, first-time-contributor, size/S, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved

#2412 en: fix a typo and update format
  en/advanced-statefulset.md
  en/backup-restore-cr.md
Labels: translation/no-need, size/S, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved

#2417 ci: update the git diff command in the prevent deletion workflow to improve accuracy
  .github/workflows/prevent-deletion.yaml
Labels: translation/done, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved

#2416 en,zh: bump operator to v1.4.6
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-to-s3.md
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-to-s3.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: translation/no-need, first-time-contributor, size/XL, lgtm, approved

#2422 en,zh: release note for v1.4.6
  en/TOC.md
  en/releases/release-1.4.6.md
  zh/TOC.md
  zh/releases/release-1.4.6.md
Labels: translation/no-need, first-time-contributor, size/M, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved

#2425 en,zh: add resolved-ts configuration to EBS backup limitations
  en/backup-to-aws-s3-by-snapshot.md
  zh/backup-to-aws-s3-by-snapshot.md
Labels: translation/done, size/XS, needs-cherry-pick-release-1.5, lgtm, approved

#2427 en,zh: release note for v1.4.7
  en/TOC.md
  en/releases/release-1.4.7.md
  zh/TOC.md
  zh/releases/release-1.4.7.md
Labels: translation/done, size/S, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved

#2428 en,zh: bump operator to v1.4.7
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-to-s3.md
  en/cheat-sheet.md
  en/configure-storage-class.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-to-s3.md
  zh/cheat-sheet.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: translation/no-need, size/XL, lgtm, approved
