Repository pingcap/docs-tidb-operator, pull requests merged in 2024-05, with the labels that each got.

#2565 zh, en: bump KIND version
  en/get-started.md
  zh/get-started.md
Labels: translation/done, size/S, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6

#2562 fix typos in docs
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  en/releases/release-1.0.0-rc.1.md
  en/releases/release-1.0.4.md
  en/releases/release-1.1.0-beta.1.md
  en/releases/release-1.3.0-beta.1.md
  en/releases/release-1.3.8.md
  en/releases/release-1.4.5.md
  en/restore-data-using-tidb-lightning.md
  en/suspend-tidb-cluster.md
  en/tidb-toolkit.md
  zh/access-dashboard.md
  zh/benchmark-sysbench.md
  zh/build-multi-gcp-gke.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/get-started.md
  zh/releases/release-1.0.0-rc.1.md
  zh/releases/release-1.0.4.md
  zh/releases/release-1.1.0-beta.1.md
  zh/releases/release-1.3.0-beta.1.md
  zh/restore-from-azblob-using-br.md
  zh/tidb-toolkit.md
Labels: translation/no-need, size/M, needs-cherry-pick-release-1.5, lgtm, approved, needs-cherry-pick-release-1.6

#2568 en,zh: Bump tidb components to v8.1.0
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-restore-cr.md
  en/backup-restore-faq.md
  en/configure-a-tidb-cluster.md
  en/deploy-cluster-on-arm64.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  en/deploy-tidb-dm.md
  en/deploy-tidb-monitor-across-multiple-kubernetes.md
  en/enable-tls-between-components.md
  en/enable-tls-for-dm.md
  en/enable-tls-for-mysql-client.md
  en/get-started.md
  en/monitor-a-tidb-cluster.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-from-aws-s3-by-snapshot.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-restore-faq.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-dm.md
  zh/deploy-tidb-monitor-across-multiple-kubernetes.md
  zh/enable-monitor-shards.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-dm.md
  zh/enable-tls-for-mysql-client.md
  zh/get-started.md
  zh/monitor-a-tidb-cluster.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-from-aws-s3-by-snapshot.md
Labels: translation/done, size/XL, lgtm, approved, needs-cherry-pick-release-1.6

#2567 en,zh: add v1.6 GA release notes and whats new
  en/TOC.md
  en/releases/release-1.6.0.md
  en/whats-new-in-v1.6.md
  zh/TOC.md
  zh/releases/release-1.6.0.md
  zh/whats-new-in-v1.6.md
Labels: translation/done, size/L, lgtm, approved, needs-cherry-pick-release-1.6

#2579 ci: upgrade actions from v3 to v4
  .github/workflows/ci.yaml
  .github/workflows/link-fail-fast.yaml
  .github/workflows/link.yml
  .github/workflows/media.yml
  .github/workflows/prevent-deletion.yaml
  .github/workflows/vale.yaml
Labels: translation/no-need, size/M, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6
