Repository pingcap/docs-tidb-operator, pull requests merged in 2024-07, with the labels that each got.

#2587 DM: Revise wrong syntax for command example on get into the pod in eng doc
  en/use-tidb-dm.md
Labels: contribution, translation/no-need, type/bug-fix, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved, needs-cherry-pick-release-1.6

#2588 CI: fix vale runs
  .github/workflows/vale.yaml
  styles/Vocab/PingCAP/accept.txt
  styles/config/vocabularies/PingCAP/accept.txt
  styles/config/vocabularies/PingCAP/reject.txt
Labels: translation/no-need, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6

#2600 add hint for log collect and k8s prometheus monitor in deploy doc
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
Labels: translation/done, size/L, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved, needs-cherry-pick-release-1.6
