Repository pingcap/docs-tidb-operator, pull requests merged in 2024-08, with the labels that each got.

#2606 en, zh: add descriptions for TiDB Binlog deprecation
  en/configure-tidb-binlog-drainer.md
  en/deploy-tidb-binlog.md
  zh/configure-tidb-binlog-drainer.md
  zh/deploy-tidb-binlog.md
Labels: translation/done, size/S, needs-cherry-pick-release-1.5, lgtm, approved, needs-cherry-pick-release-1.6, tidb/v8.3, for-release

#2614 zh,en: remove spec.from for Backup and spec.to for Restore
  en/backup-to-aws-s3-using-br.md
  en/backup-to-azblob-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-pv-using-br.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-azblob-using-br.md
  en/restore-from-gcs-using-br.md
  en/restore-from-pv-using-br.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-azblob-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/backup-to-pv-using-br.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
  zh/restore-from-aws-s3-using-br.md
  zh/restore-from-azblob-using-br.md
  zh/restore-from-gcs-using-br.md
  zh/restore-from-pv-using-br.md
Labels: translation/done, size/XL, needs-cherry-pick-release-1.5, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6

#2615 zh, en: comment out spec.from for Backup and spec.to for Restore in v1.4
  en/backup-to-aws-s3-using-br.md
  en/backup-to-azblob-using-br.md
  en/backup-to-gcs-using-br.md
  en/enable-tls-between-components.md
  en/enable-tls-for-mysql-client.md
  en/restore-from-aws-s3-using-br.md
  zh/backup-to-aws-s3-using-br.md
  zh/backup-to-azblob-using-br.md
  zh/backup-to-gcs-using-br.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-mysql-client.md
  zh/restore-from-aws-s3-using-br.md
Labels: translation/done, size/XL, lgtm, approved, needs-1-more-lgtm
