Repository pingcap/docs-tidb-operator, pull requests merged in 2024-09, with the labels that each got.

#2618 en: unify product terms
  en/_index.md
  en/clinic-user-guide.md
  en/tidb-operator-overview.md
Labels: translation/no-need, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6

#2620 en,zh: add v1.5.4 release notes
  en/TOC.md
  en/releases/release-1.5.4.md
  zh/TOC.md
  zh/releases/release-1.5.4.md
Labels: translation/done, size/M, needs-cherry-pick-release-1.5, lgtm, approved, needs-cherry-pick-release-1.6

#2619 en,zh: Bump tidb components to v7.5.3
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-restore-cr.md
  en/backup-restore-faq.md
  en/configure-a-tidb-cluster.md
  en/deploy-cluster-on-arm64.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  en/deploy-tidb-dm.md
  en/deploy-tidb-monitor-across-multiple-kubernetes.md
  en/enable-monitor-shards.md
  en/enable-tls-between-components.md
  en/enable-tls-for-dm.md
  en/enable-tls-for-mysql-client.md
  en/get-started.md
  en/monitor-a-tidb-cluster.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-from-aws-s3-by-snapshot.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-restore-cr.md
  zh/backup-restore-faq.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-cluster-on-arm64.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-dm.md
  zh/deploy-tidb-monitor-across-multiple-kubernetes.md
  zh/enable-monitor-shards.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-dm.md
  zh/enable-tls-for-mysql-client.md
  zh/get-started.md
  zh/monitor-a-tidb-cluster.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-from-aws-s3-by-snapshot.md
  zh/upgrade-a-tidb-cluster.md
Labels: translation/done, size/XXL, lgtm, approved, needs-1-more-lgtm

#2630 v1.3 en, zh: remove the auto scaling doc
  en/enable-tidb-cluster-auto-scaling.md
  en/tidb-operator-overview.md
  zh/enable-tidb-cluster-auto-scaling.md
  zh/tidb-operator-overview.md
Labels: translation/done, size/XL, lgtm, approved

#2631 v1.2 en, zh: remove the auto scaling doc
  en/TOC.md
  en/enable-admission-webhook.md
  en/enable-tidb-cluster-auto-scaling.md
  en/tidb-operator-overview.md
  en/whats-new-in-v1.1.md
  zh/TOC.md
  zh/enable-admission-webhook.md
  zh/enable-tidb-cluster-auto-scaling.md
  zh/tidb-operator-overview.md
  zh/whats-new-in-v1.1.md
Labels: translation/done, size/XL, lgtm, approved
