Repository pingcap/docs-tidb-operator, pull requests merged in 2024-10, with the labels that each got.

#2633 update CentOS 7 related description
  en/deploy-on-gcp-gke.md
  en/prerequisites.md
  zh/deploy-on-gcp-gke.md
  zh/prerequisites.md
Labels: translation/done, size/S, lgtm, approved, needs-1-more-lgtm

#2634 pdms: correct scale command
  en/scale-a-tidb-cluster.md
  zh/scale-a-tidb-cluster.md
Labels: translation/done, type/bugfix, size/XS, needs-cherry-pick-release-1.5, lgtm, approved, needs-cherry-pick-release-1.6

#2637 Update the version of local-volume-provisioner
  en/configure-storage-class.md
  zh/configure-storage-class.md
Labels: translation/done, size/S, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6, ONCALL
