Repository pingcap/docs-tidb-operator, pull requests merged in 2024-01, with the labels that each got.

#2477 tiproxy: add basic document
  zh/TOC.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-failures.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tiproxy.md
  zh/enable-tls-between-components.md
  zh/faq.md
  zh/modify-tidb-configuration.md
  zh/renew-tls-certificate.md
  zh/scale-a-tidb-cluster.md
  zh/suspend-tidb-cluster.md
  zh/upgrade-a-tidb-cluster.md
Labels: translation/done, size/L, needs-cherry-pick-release-1.5, lgtm, approved

#2480 en: add tiproxy docs
  en/TOC.md
  en/configure-a-tidb-cluster.md
  en/deploy-failures.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  en/deploy-tiproxy.md
  en/enable-tls-between-components.md
  en/faq.md
  en/modify-tidb-configuration.md
  en/renew-tls-certificate.md
  en/scale-a-tidb-cluster.md
  en/suspend-tidb-cluster.md
  en/upgrade-a-tidb-cluster.md
Labels: translation/from-zh, size/L, needs-cherry-pick-release-1.5, lgtm, approved, needs-1-more-lgtm

#2475 fix-pd-recover
  en/pd-recover.md
  zh/pd-recover.md
Labels: translation/done, size/S, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved

#2466 Update mountOptions to separate options
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
Labels: contribution, translation/done, size/M, needs-cherry-pick-release-1.5, lgtm, approved, needs-1-more-lgtm

#2485 en,zh: add v1.5.2 release notes
  en/TOC.md
  en/releases/release-1.5.2.md
  zh/TOC.md
  zh/releases/release-1.5.2.md
Labels: translation/done, size/M, needs-cherry-pick-release-1.5, lgtm, approved

#2486 en,zh: bump operator to v1.5.2
  en/cheat-sheet.md
  en/deploy-br-federation.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/tidb-toolkit.md
  en/upgrade-tidb-operator.md
  zh/cheat-sheet.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/tidb-toolkit.md
  zh/upgrade-tidb-operator.md
Labels: translation/no-need, size/L, lgtm, approved, needs-1-more-lgtm

#2496 en: fix release 1.5.2
  en/releases/release-1.5.2.md
Labels: translation/no-need, size/XS, lgtm, approved, needs-1-more-lgtm

#2484 install the ebs-csi-driver addon when creating aws eks cluster
  en/deploy-on-aws-eks.md
  zh/deploy-on-aws-eks.md
Labels: contribution, translation/done, first-time-contributor, size/L, needs-cherry-pick-release-1.5, lgtm, approved

#2500 tiproxy: fix broken links
  en/deploy-tiproxy.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-tiproxy.md
Labels: translation/done, type/bug-fix, size/XS, needs-cherry-pick-release-1.5, lgtm, approved, needs-1-more-lgtm

#2503 tiproxy: add description on graceful-wait and signing-cert
  en/configure-a-tidb-cluster.md
  en/deploy-tiproxy.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-tiproxy.md
Labels: translation/done, size/M, needs-cherry-pick-release-1.5, lgtm, approved
