Repository pingcap/docs-tidb-operator, pull requests merged in 2024-12, with the labels that each got.

#2652 zh, en: update EOS for 1.2
  en/tidb-operator-overview.md
  zh/tidb-operator-overview.md
Labels: translation/done, size/XS, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6

#2653 en,zh: add v1.6.1 release notes
  en/TOC.md
  en/releases/release-1.6.1.md
  zh/TOC.md
  zh/releases/release-1.6.1.md
Labels: translation/done, size/M, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6

#2665 archive v1.2
  .github/pull_request_template.md
  README.md
Labels: translation/no-need, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved, needs-cherry-pick-release-1.6

#2656 en,zh: Bump tidb components to v8.5.0
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-restore-cr.md
  en/backup-restore-faq.md
  en/configure-a-tidb-cluster.md
  en/deploy-cluster-on-arm64.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  en/deploy-tidb-dm.md
  en/deploy-tidb-monitor-across-multiple-kubernetes.md
  en/enable-tls-between-components.md
  en/enable-tls-for-dm.md
  en/enable-tls-for-mysql-client.md
  en/get-started.md
  en/monitor-a-tidb-cluster.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-from-aws-s3-by-snapshot.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-restore-faq.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-dm.md
  zh/deploy-tidb-monitor-across-multiple-kubernetes.md
  zh/enable-monitor-shards.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-dm.md
  zh/enable-tls-for-mysql-client.md
  zh/get-started.md
  zh/monitor-a-tidb-cluster.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-from-aws-s3-by-snapshot.md
Labels: translation/done, size/XL, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6
