Repository pingcap/docs-tidb-operator, pull requests merged in 2024-03, with the labels that each got.

#2478 zh: support PD micro service
  zh/configure-a-tidb-cluster.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/enable-tls-between-components.md
  zh/get-started.md
  zh/modify-tidb-configuration.md
  zh/scale-a-tidb-cluster.md
  zh/suspend-tidb-cluster.md
  zh/upgrade-a-tidb-cluster.md
Labels: translation/done, first-time-contributor, size/L, lgtm, approved, tidb/v8.0

#2517 en: support PD micro service
  en/configure-a-tidb-cluster.md
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  en/enable-tls-between-components.md
  en/get-started.md
  en/modify-tidb-configuration.md
  en/scale-a-tidb-cluster.md
  en/suspend-tidb-cluster.md
  en/upgrade-a-tidb-cluster.md
Labels: translation/from-zh, size/L, lgtm, approved, needs-1-more-lgtm, tidb/v8.0

#2518 init v1.6
  .github/pull_request_template.md
  README.md
Labels: translation/no-need, size/XS, lgtm, approved, needs-1-more-lgtm

#2525 *: fix toc for 1.6
  en/TOC.md
  en/whats-new-in-v1.5.md
  zh/TOC.md
  zh/whats-new-in-v1.5.md
Labels: translation/done, size/M, lgtm, approved, needs-1-more-lgtm

#2526 scale-a-tidb-cluster: fix pd micro service indent
  en/scale-a-tidb-cluster.md
  zh/scale-a-tidb-cluster.md
Labels: translation/done, size/XS, lgtm, approved, needs-1-more-lgtm

#2519 en,zh: release notes for 1.6.0-beta.1
  en/TOC.md
  en/releases/release-1.6.0-beta.1.md
  en/tidb-operator-overview.md
  en/tidb-scheduler.md
  zh/TOC.md
  zh/releases/release-1.6.0-beta.1.md
  zh/tidb-operator-overview.md
  zh/tidb-scheduler.md
Labels: translation/done, size/M, lgtm, approved, needs-cherry-pick-release-1.6

#2520 en,zh: Bump tidb components to v8.0.0
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-restore-cr.md
  en/backup-restore-faq.md
  en/configure-a-tidb-cluster.md
  en/deploy-cluster-on-arm64.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  en/deploy-tidb-dm.md
  en/deploy-tidb-monitor-across-multiple-kubernetes.md
  en/enable-tls-between-components.md
  en/enable-tls-for-dm.md
  en/enable-tls-for-mysql-client.md
  en/get-started.md
  en/monitor-a-tidb-cluster.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-from-aws-s3-by-snapshot.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-restore-faq.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-dm.md
  zh/deploy-tidb-monitor-across-multiple-kubernetes.md
  zh/enable-monitor-shards.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-dm.md
  zh/enable-tls-for-mysql-client.md
  zh/get-started.md
  zh/monitor-a-tidb-cluster.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-from-aws-s3-by-snapshot.md
Labels: translation/done, size/XL, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6

#2529 bump k8s version to v1.24
  en/advanced-statefulset.md
  en/clinic-user-guide.md
  en/configure-a-tidb-cluster.md
  en/configure-storage-class.md
  en/deploy-br-federation.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-on-azure-aks.md
  en/deploy-tidb-dm.md
  en/deploy-tidb-from-kubernetes-gke.md
  en/deploy-tidb-operator.md
  en/enable-admission-webhook.md
  en/get-started.md
  en/prerequisites.md
  en/upgrade-tidb-operator.md
  zh/advanced-statefulset.md
  zh/clinic-user-guide.md
  zh/configure-a-tidb-cluster.md
  zh/configure-storage-class.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-on-azure-aks.md
  zh/deploy-tidb-dm.md
  zh/deploy-tidb-from-kubernetes-gke.md
  zh/deploy-tidb-operator.md
  zh/enable-admission-webhook.md
  zh/get-started.md
  zh/prerequisites.md
  zh/upgrade-tidb-operator.md
Labels: translation/done, size/XL, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6

#2535 zh, en: remove docs about deploy on ACK
  en/TOC.md
  en/_index.md
  en/access-tidb.md
  en/deploy-on-alibaba-cloud.md
  en/deploy-tidb-operator.md
  en/get-started.md
  en/replace-nodes-for-cloud-disk.md
  en/tidb-operator-overview.md
  zh/TOC.md
  zh/_index.md
  zh/access-tidb.md
  zh/deploy-on-alibaba-cloud.md
  zh/deploy-tidb-operator.md
  zh/get-started.md
  zh/replace-nodes-for-cloud-disk.md
  zh/tidb-operator-overview.md
Labels: translation/done, size/XXL, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6

#2536 _index: update links for deploy-on-azure-aks
  en/_index.md
  zh/_index.md
Labels: translation/done, size/XS, needs-cherry-pick-release-1.2, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved, needs-1-more-lgtm
