Repository pingcap/docs-tidb-operator, pull requests merged in 2025-02, with the labels that each got.

#2699 ci: upload media to cos
  .github/workflows/media.yml
Labels: translation/no-need, size/M, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved, needs-cherry-pick-release-1.6

#2704 fix(ci): cdn refresh
  .github/workflows/media.yml
Labels: translation/no-need, size/XS, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved, needs-cherry-pick-release-1.6

#2710 pd/tls: add upgrade tls description
  en/configure-a-tidb-cluster.md
  en/enable-tls-between-components.md
  en/restore-data-using-tidb-lightning.md
  zh/enable-tls-between-components.md
Labels: translation/from-zh, size/L, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6
