Repository pingcap/docs-tidb-operator, pull requests merged in 2025-01, with the labels that each got.

#2677 en, zh: update the version number of advanced-statefulset
  en/deploy-tidb-operator.md
  zh/deploy-tidb-operator.md
Labels: translation/done, size/S, needs-cherry-pick-release-1.5, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6

#2651 Add serivce account requirement for tiflash pod while restore
  en/grant-permissions-to-remote-storage.md
  en/renew-tls-certificate.md
  zh/grant-permissions-to-remote-storage.md
Labels: translation/done, first-time-contributor, size/S, needs-cherry-pick-release-1.5, lgtm, approved, needs-cherry-pick-release-1.6

#2658 Fix heading indentation
  en/restore-from-aws-s3-using-br.md
  en/restore-from-gcs-using-br.md
  zh/restore-from-aws-s3-using-br.md
  zh/restore-from-gcs-using-br.md
Labels: contribution, translation/done, size/S, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6

#2678 remove unnecessary white space
  en/releases/release-1.3.0-beta.1.md
  zh/releases/release-1.1-ga.md
Labels: translation/done, size/XS, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved, needs-cherry-pick-release-1.6

#2673 en,zh: add v1.5.5 release notes
  en/TOC.md
  en/releases/release-1.5.5.md
  zh/TOC.md
  zh/releases/release-1.5.5.md
Labels: translation/done, size/M, needs-cherry-pick-release-1.5, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6

#2674 en,zh: Bump tidb components to v7.5.5
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-restore-cr.md
  en/backup-restore-faq.md
  en/configure-a-tidb-cluster.md
  en/deploy-cluster-on-arm64.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-binlog.md
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  en/deploy-tidb-dm.md
  en/deploy-tidb-monitor-across-multiple-kubernetes.md
  en/enable-monitor-shards.md
  en/enable-tls-between-components.md
  en/enable-tls-for-dm.md
  en/enable-tls-for-mysql-client.md
  en/get-started.md
  en/monitor-a-tidb-cluster.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-from-aws-s3-by-snapshot.md
  en/upgrade-a-tidb-cluster.md
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-restore-cr.md
  zh/backup-restore-faq.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-cluster-on-arm64.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-aws-eks.md
  zh/deploy-on-azure-aks.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-binlog.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-dm.md
  zh/deploy-tidb-monitor-across-multiple-kubernetes.md
  zh/enable-monitor-shards.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-dm.md
  zh/enable-tls-for-mysql-client.md
  zh/get-started.md
  zh/monitor-a-tidb-cluster.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-from-aws-s3-by-snapshot.md
  zh/upgrade-a-tidb-cluster.md
Labels: translation/done, size/XL, lgtm, approved, needs-1-more-lgtm

#2693 zh,en: remove tidb-scheduler in get-started
  en/get-started.md
  zh/get-started.md
Labels: translation/done, size/XS, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6

#2692 zh: add security notes
  zh/tidb-operator-overview.md
Labels: translation/doing, size/XS, needs-cherry-pick-release-1.4, lgtm, approved, needs-1-more-lgtm
