Repository pingcap/docs-tidb-operator, pull requests merged in 2025-04, with the labels that each got.

#2728 zh,en: remove deprecated Helm charts
  en/tidb-toolkit.md
  zh/tidb-toolkit.md
Labels: translation/done, size/S, needs-cherry-pick-release-1.5, lgtm, approved, needs-cherry-pick-release-1.6

#2731 toc: fix links
  en/TOC.md
  zh/TOC.md
Labels: translation/done, size/XS, lgtm, approved, needs-1-more-lgtm

#2734 workflow: add doc_review.yml
  .github/workflows/doc_review.yml
  doc-review-prompt-en.txt
  doc-review-prompt-zh.txt
Labels: translation/done, size/XL, lgtm, approved, needs-1-more-lgtm

#2735 doc_review.yml: update the AI model
  .github/workflows/doc_review.yml
  doc-review-prompt-en.txt
  doc-review-prompt-zh.txt
Labels: translation/no-need, size/XS, lgtm, approved

#2740 pull_request_template.md: add v2
  .github/pull_request_template.md
Labels: translation/no-need, size/XS, lgtm, approved

#2738 Add a doc about how to run as non root user
  zh/TOC.md
  zh/containers-run-as-non-root-user.md
Labels: translation/doing, size/M, lgtm, approved, v2.0

#2742 en: Add a doc about how to run as non root user
  en/TOC.md
  en/containers-run-as-non-root-user.md
Labels: translation/from-zh, size/M, lgtm, approved, needs-1-more-lgtm, v2.0

#2732 add dumpling-lightning-job
  zh/TOC.md
  zh/backup-to-blob-using-job.md
  zh/backup-to-gcs-using-job.md
  zh/backup-to-gcs.md
  zh/backup-to-s3-using-job.md
  zh/backup-to-s3.md
  zh/restore-from-blob-using-job.md
  zh/restore-from-gcs-using-job.md
  zh/restore-from-gcs.md
  zh/restore-from-s3-using-job.md
  zh/restore-from-s3.md
Labels: translation/doing, size/XXL, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved, needs-cherry-pick-release-1.6

#2743 zh: Add docs about how to destroy a tidb cluster and how to view logs
  zh/TOC.md
  zh/destroy-a-tidb-cluster.md
  zh/view-logs.md
Labels: translation/from-en, size/M, lgtm, approved, v2.0

#2746 en: Add docs about how to destroy a tidb cluster and how to view logs
  en/TOC.md
  en/destroy-a-tidb-cluster.md
  en/view-logs.md
Labels: translation/from-zh, size/M, lgtm, approved, needs-1-more-lgtm, v2.0

#2751 zh: how to restart a tidb cluster
  zh/TOC.md
  zh/restart-a-tidb-cluster.md
Labels: translation/doing, size/M, lgtm, approved, v2.0
