Repository pingcap/docs-tidb-operator, pull requests merged in 2025-07, with the labels that each got.

#2739 zh: add a doc about how to use overlay
  zh/TOC.md
  zh/overlay.md
  zh/tidb-operator-overview.md
  zh/volume-configuration.md
Labels: translation/done, size/L, lgtm, approved, v2.0

#2822 en: upgrade a tidb cluster
  en/TOC.md
  en/upgrade-a-tidb-cluster.md
Labels: translation/from-zh, size/M, lgtm, approved, needs-1-more-lgtm, v2.0

#2828 en: add a doc about how to use overlay
  en/TOC.md
  en/overlay.md
Labels: translation/from-zh, size/L, lgtm, approved, needs-1-more-lgtm, v2.0

#2838 en: upgrade tidb operator
  en/TOC.md
  en/upgrade-tidb-operator.md
Labels: translation/from-zh, size/L, lgtm, approved, needs-1-more-lgtm, v2.0

#2823 en: deploy tidb operator
  en/TOC.md
  en/deploy-tidb-operator.md
Labels: translation/from-zh, size/L, lgtm, approved, needs-1-more-lgtm, v2.0

#2824 en: renew tls certificate
  en/TOC.md
  en/renew-tls-certificate.md
  zh/renew-tls-certificate.md
Labels: translation/from-zh, size/L, lgtm, approved, v2.0

#2841 zh, en: v2 vs v1
  en/TOC.md
  en/releases/release-2.0.0-beta.0.md
  en/tidb-operator-overview.md
  en/tidb-operator-v2-vs-v1.md
  en/v2-vs-v1.md
  zh/TOC.md
  zh/releases/release-2.0.0-beta.0.md
  zh/tidb-operator-overview.md
  zh/tidb-operator-v2-vs-v1.md
  zh/v2-vs-v1.md
Labels: translation/done, size/L, lgtm, approved, needs-1-more-lgtm, v2.0, needs-cherry-pick-release-2.0

#2744 zh: how to deploy tidb cluster
  zh/TOC.md
  zh/deploy-tidb-cluster.md
Labels: translation/done, size/XL, lgtm, approved, v2.0, needs-cherry-pick-release-2.0

#2844 release: init v2
  .github/pull_request_template.md
  README.md
  en/TOC.md
  en/releases/release-2.0.0-beta.0.md
  zh/TOC.md
  zh/releases/release-2.0.0-beta.0.md
Labels: translation/no-need, size/L, lgtm, approved, needs-1-more-lgtm, v2.0, needs-cherry-pick-release-2.0

#2859 zh, en: remove HotReload policy in doc
  en/component-configuration.md
  zh/component-configuration.md
Labels: translation/no-need, size/S, lgtm, approved, needs-1-more-lgtm, v2.0, needs-cherry-pick-release-2.0

#2860 zh, en: add notes for in place pod resize
  en/scale-a-tidb-cluster.md
  zh/scale-a-tidb-cluster.md
Labels: translation/no-need, size/XS, lgtm, approved, needs-1-more-lgtm, v2.0, needs-cherry-pick-release-2.0

#2857 en, zh: fix some issues
  en/access-tidb.md
  en/deploy-tidb-cluster.md
  en/scale-a-tidb-cluster.md
  zh/access-tidb.md
  zh/deploy-tidb-cluster.md
  zh/scale-a-tidb-cluster.md
Labels: translation/no-need, size/L, lgtm, approved, v2.0, needs-cherry-pick-release-2.0

#2872 variables: update tidb_operator_version to v2.0.0-beta.0
  en/TOC.md
  variables.json
  zh/TOC.md
Labels: translation/no-need, size/XS, lgtm, approved, v2.0, needs-cherry-pick-release-2.0

#2874 ci: add variable replacement and custom ID handling
  scripts/merge_by_toc.py
Labels: translation/no-need, needs-cherry-pick-master, size/M, lgtm, approved, v2.0, needs-cherry-pick-release-2.0

#2833 en,zh: Bump tidb components to v8.5.2
  en/access-dashboard.md
  en/advanced-statefulset.md
  en/aggregate-multiple-cluster-monitor-data.md
  en/backup-restore-cr.md
  en/backup-restore-faq.md
  en/backup-to-blob-using-job.md
  en/backup-to-gcs-using-job.md
  en/backup-to-s3-using-job.md
  en/configure-a-tidb-cluster.md
  en/deploy-cluster-on-arm64.md
  en/deploy-heterogeneous-tidb-cluster.md
  en/deploy-on-aws-eks.md
  en/deploy-on-azure-aks.md
  en/deploy-on-gcp-gke.md
  en/deploy-on-general-kubernetes.md
  en/deploy-tidb-cluster-across-multiple-kubernetes.md
  en/deploy-tidb-dm.md
  en/deploy-tidb-monitor-across-multiple-kubernetes.md
  en/enable-tls-between-components.md
  en/enable-tls-for-dm.md
  en/enable-tls-for-mysql-client.md
  en/get-started.md
  en/monitor-a-tidb-cluster.md
  en/pd-recover.md
  en/restart-a-tidb-cluster.md
  en/restore-from-aws-s3-by-snapshot.md
  en/restore-from-blob-using-job.md
  en/restore-from-gcs-using-job.md
  en/restore-from-s3-using-job.md
  en/upgrade-a-tidb-cluster.md
  variables.json
  zh/access-dashboard.md
  zh/advanced-statefulset.md
  zh/aggregate-multiple-cluster-monitor-data.md
  zh/backup-restore-faq.md
  zh/backup-to-blob-using-job.md
  zh/backup-to-gcs-using-job.md
  zh/backup-to-s3-using-job.md
  zh/configure-a-tidb-cluster.md
  zh/deploy-heterogeneous-tidb-cluster.md
  zh/deploy-on-gcp-gke.md
  zh/deploy-on-general-kubernetes.md
  zh/deploy-tidb-cluster-across-multiple-kubernetes.md
  zh/deploy-tidb-dm.md
  zh/deploy-tidb-monitor-across-multiple-kubernetes.md
  zh/enable-monitor-shards.md
  zh/enable-tls-between-components.md
  zh/enable-tls-for-dm.md
  zh/enable-tls-for-mysql-client.md
  zh/get-started.md
  zh/monitor-a-tidb-cluster.md
  zh/pd-recover.md
  zh/restart-a-tidb-cluster.md
  zh/restore-from-aws-s3-by-snapshot.md
  zh/restore-from-blob-using-job.md
  zh/restore-from-gcs-using-job.md
  zh/restore-from-s3-using-job.md
Labels: translation/done, size/XL, lgtm, approved, needs-cherry-pick-release-1.6

#2834 en,zh: add v1.6.2 release notes
  en/TOC.md
  en/releases/release-1.6.2.md
  zh/TOC.md
  zh/releases/release-1.6.2.md
Labels: translation/done, size/M, lgtm, approved, needs-cherry-pick-release-1.6

#2884 ci: add feature/v2 branch to push triggers
  .github/workflows/media.yml
Labels: translation/no-need, size/XS, lgtm, approved, needs-1-more-lgtm, v2.0

#2886 en: fix format of release-1.6.2
  en/releases/release-1.6.2.md
Labels: translation/no-need, type/bugfix, size/XS, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6

#2888 en: fix format in renew-tls-certificate.md
  en/renew-tls-certificate.md
Labels: translation/no-need, type/bugfix, size/XS, lgtm, approved, needs-cherry-pick-release-2.0

#2891 en,zh: bump operator to v1.6.3 and add release notes
  en/TOC.md
  en/releases/release-1.6.3.md
  variables.json
  zh/TOC.md
  zh/releases/release-1.6.3.md
Labels: translation/done, size/M, lgtm, approved, needs-cherry-pick-release-1.6

#2893 fix: update CLA link to correct URL
  .github/pull_request_template.md
Labels: translation/no-need, size/XS, needs-cherry-pick-release-1.3, needs-cherry-pick-release-1.4, needs-cherry-pick-release-1.5, lgtm, approved, needs-1-more-lgtm, needs-cherry-pick-release-1.6, needs-cherry-pick-release-2.0
