Repository pingcap/docs-tidb-operator, pull requests merged in 2025-06, with the labels that each got.

#2776 zh: introduce backup and restore CRs
  zh/backup-restore-cr.md
Labels: translation/doing, size/L, lgtm, approved, needs-1-more-lgtm, v2.0

#2787 en: tidb toolkit
  en/TOC.md
  en/tidb-toolkit.md
Labels: translation/from-zh, size/M, lgtm, approved, needs-1-more-lgtm, v2.0

#2799 Update doc_review.yml
  .github/workflows/doc_review.yml
Labels: translation/no-need, size/M, lgtm, approved

#2767 zh: enable tls between components
  zh/TOC.md
  zh/enable-tls-between-components.md
  zh/renew-tls-certificate.md
Labels: translation/doing, size/XXL, lgtm, approved, v2.0

#2765 zh: enable tls for mysql client
  zh/TOC.md
  zh/enable-tls-for-mysql-client.md
Labels: translation/doing, size/XL, lgtm, approved, v2.0

#2783 en: how to access tidb
  en/TOC.md
  en/access-tidb.md
  zh/TOC.md
Labels: translation/from-zh, size/L, lgtm, approved, needs-1-more-lgtm, v2.0

#2786 en: k8s observability
  en/TOC.md
  en/kubernetes-observability.md
Labels: translation/from-zh, size/M, lgtm, approved, needs-1-more-lgtm, v2.0

#2775 zh: monitor a tidb cluster
  media/overview-of-monitoring-tidb-clusters.png
  zh/TOC.md
  zh/monitor-a-tidb-cluster.md
Labels: translation/doing, size/L, lgtm, approved, v2.0

#2792 zh: restore from azure
  zh/backup-to-azblob-using-br.md
  zh/restore-from-azblob-using-br.md
Labels: translation/doing, size/L, lgtm, approved, v2.0

#2784 zh: backup to aws s3 using br
  zh/backup-to-aws-s3-using-br.md
  zh/restore-from-aws-s3-using-br.md
Labels: translation/doing, size/XXL, lgtm, approved, v2.0

#2785 zh: restore from aws s3 using br
  zh/restore-from-aws-s3-using-br.md
Labels: translation/doing, size/XL, lgtm, approved, v2.0

#2789 zh: restore from gcs using br
  zh/restore-from-gcs-using-br.md
Labels: translation/doing, size/L, lgtm, approved, v2.0

#2801 zh: upgrade a tidb cluster
  zh/TOC.md
  zh/upgrade-a-tidb-cluster.md
Labels: translation/doing, size/M, lgtm, approved, v2.0

#2800 zh: tidb operator architecture
  media/tidb-operator-architecture.png
  media/tidb-operator-control-flow.png
  zh/architecture.md
Labels: translation/doing, size/M, lgtm, approved, v2.0

#2803 zh: configure and modify volumes
  zh/configure-volume.md
Labels: translation/doing, size/XL, lgtm, approved, v2.0

#2809 en: enable tls for mysql client
  en/TOC.md
  en/enable-tls-for-mysql-client.md
  en/renew-tls-certificate.md
  zh/TOC.md
  zh/enable-tls-for-mysql-client.md
Labels: translation/from-zh, size/XL, lgtm, approved, needs-1-more-lgtm, v2.0

#2772 en: how to suspend a tidb cluster
  en/TOC.md
  en/suspend-tidb-cluster.md
Labels: translation/from-zh, size/M, lgtm, approved, needs-1-more-lgtm, v2.0

#2808 en: backup restore overview
  en/TOC.md
  en/backup-restore-cr.md
  en/backup-restore-overview.md
  en/backup-to-aws-s3-using-br.md
  en/backup-to-azblob-using-br.md
  en/backup-to-gcs-using-br.md
  en/backup-to-pv-using-br.md
  en/restore-from-aws-s3-using-br.md
  en/restore-from-azblob-using-br.md
  en/restore-from-gcs-using-br.md
  en/restore-from-pv-using-br.md
Labels: translation/from-zh, size/L, lgtm, approved, v2.0

#2782 en: scale a tidb cluster
  en/TOC.md
  en/deploy-failures.md
  en/exceptions.md
  en/scale-a-tidb-cluster.md
Labels: translation/from-zh, size/L, lgtm, approved, needs-1-more-lgtm, v2.0

#2820 en: restore from azure
  en/backup-to-azblob-using-br.md
  en/restore-from-azblob-using-br.md
  zh/restore-from-azblob-using-br.md
Labels: translation/from-zh, size/L, lgtm, approved, needs-1-more-lgtm, v2.0

#2826 en: configure and modify volumes
  en/TOC.md
  en/volume-configuration.md
  zh/configure-volume.md
Labels: translation/from-zh, size/XL, lgtm, approved, needs-1-more-lgtm, v2.0

#2804 zh: get started
  zh/TOC.md
  zh/get-started.md
Labels: translation/doing, size/XL, lgtm, approved, v2.0

#2819 en: backup to azblob
  en/backup-to-azblob-using-br.md
  zh/backup-to-azblob-using-br.md
Labels: translation/from-zh, size/XXL, lgtm, approved, needs-1-more-lgtm, v2.0

#2807 en: add tidb operator overview
  en/TOC.md
  en/deploy-tidb-cluster.md
  en/deploy-tidb-operator.md
  en/faq.md
  en/get-started.md
  en/tidb-operator-overview.md
  en/tidb-operator-v2-vs-v1.md
  en/tips.md
  en/upgrade-tidb-operator.md
  zh/tidb-operator-v2-vs-v1.md
Labels: translation/from-zh, size/L, lgtm, approved, needs-1-more-lgtm, v2.0

#2818 en: restore from gcs using br
  en/restore-from-gcs-using-br.md
  zh/restore-from-gcs-using-br.md
Labels: translation/from-zh, size/L, lgtm, approved, needs-1-more-lgtm, v2.0

#2831 zh: add learning path
  zh/_index.md
Labels: translation/done, size/M, lgtm, approved, v2.0

#2832 en: add learning path
  en/_index.md
Labels: translation/from-zh, size/M, lgtm, approved, needs-1-more-lgtm, v2.0
