Repository pingcap/docs-tidb-operator, pull requests merged in 2025-05, with the labels that each got.

#2759 zh: add two TODO doc to make the linter happy
  zh/TOC.md
  zh/configure-volume.md
  zh/overlay.md
Labels: translation/doing, size/S, lgtm, approved, needs-1-more-lgtm, v2.0

#2757 en: how to restart a tidb cluster
  en/TOC.md
  en/restart-a-tidb-cluster.md
Labels: translation/from-en, size/M, lgtm, approved, needs-1-more-lgtm, v2.0

#2756 zh: scale a tidb cluster
  zh/TOC.md
  zh/access-tidb.md
  zh/deploy-failures.md
  zh/exceptions.md
  zh/scale-a-tidb-cluster.md
Labels: translation/doing, size/L, lgtm, approved, v2.0

#2745 zh: how to access tidb
  zh/TOC.md
  zh/access-tidb.md
Labels: translation/doing, size/L, lgtm, approved, v2.0

#2761 zh: k8s observability
  zh/TOC.md
  zh/kubernetes-observability.md
Labels: translation/doing, size/M, lgtm, approved, v2.0
